"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.any_pb2
import google.protobuf.descriptor
import google.protobuf.field_mask_pb2
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.timestamp_pb2
import google.rpc.status_pb2
from ...nest import messages_pb2
import sys
import typing
from ... import wdl_event_importance_pb2

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class TraitStateNotification(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _NotificationContext:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _NotificationContextEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[TraitStateNotification._NotificationContext.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        NOTIFICATION_CONTEXT_UNSPECIFIED: TraitStateNotification._NotificationContext.ValueType  # 0
        INITIAL_OBSERVE_RESPONSE: TraitStateNotification._NotificationContext.ValueType  # 1

    class NotificationContext(_NotificationContext, metaclass=_NotificationContextEnumTypeWrapper): ...
    NOTIFICATION_CONTEXT_UNSPECIFIED: TraitStateNotification.NotificationContext.ValueType  # 0
    INITIAL_OBSERVE_RESPONSE: TraitStateNotification.NotificationContext.ValueType  # 1

    STATE_FIELD_NUMBER: builtins.int
    STATEMASK_FIELD_NUMBER: builtins.int
    MONOTONICVERSION_FIELD_NUMBER: builtins.int
    NOTIFICATIONCONTEXT_FIELD_NUMBER: builtins.int
    PUBLISHERVERSION_FIELD_NUMBER: builtins.int
    monotonicVersion: builtins.int
    notificationContext: global___TraitStateNotification.NotificationContext.ValueType
    publisherVersion: builtins.int
    @property
    def state(self) -> google.protobuf.any_pb2.Any: ...
    @property
    def stateMask(self) -> google.protobuf.field_mask_pb2.FieldMask: ...
    def __init__(
        self,
        *,
        state: google.protobuf.any_pb2.Any | None = ...,
        stateMask: google.protobuf.field_mask_pb2.FieldMask | None = ...,
        monotonicVersion: builtins.int = ...,
        notificationContext: global___TraitStateNotification.NotificationContext.ValueType = ...,
        publisherVersion: builtins.int = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["state", b"state", "stateMask", b"stateMask"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["monotonicVersion", b"monotonicVersion", "notificationContext", b"notificationContext", "publisherVersion", b"publisherVersion", "state", b"state", "stateMask", b"stateMask"]) -> None: ...

global___TraitStateNotification = TraitStateNotification

@typing.final
class TraitEventsNotification(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    EVENTS_FIELD_NUMBER: builtins.int
    REQUESTUTCTIMESTAMP_FIELD_NUMBER: builtins.int
    REQUESTSYSTEMTIMEOFFSETMILLIS_FIELD_NUMBER: builtins.int
    SERVICERECEIVEDTIMESTAMP_FIELD_NUMBER: builtins.int
    requestSystemTimeOffsetMillis: builtins.int
    @property
    def events(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Event]: ...
    @property
    def requestUtcTimestamp(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def serviceReceivedTimestamp(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        events: collections.abc.Iterable[global___Event] | None = ...,
        requestUtcTimestamp: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        requestSystemTimeOffsetMillis: builtins.int = ...,
        serviceReceivedTimestamp: google.protobuf.timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["requestUtcTimestamp", b"requestUtcTimestamp", "serviceReceivedTimestamp", b"serviceReceivedTimestamp"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["events", b"events", "requestSystemTimeOffsetMillis", b"requestSystemTimeOffsetMillis", "requestUtcTimestamp", b"requestUtcTimestamp", "serviceReceivedTimestamp", b"serviceReceivedTimestamp"]) -> None: ...

global___TraitEventsNotification = TraitEventsNotification

@typing.final
class Event(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DATA_FIELD_NUMBER: builtins.int
    IMPORTANCE_FIELD_NUMBER: builtins.int
    EVENTID_FIELD_NUMBER: builtins.int
    RELATEDEVENTIMPORTANCE_FIELD_NUMBER: builtins.int
    RELATEDEVENTID_FIELD_NUMBER: builtins.int
    UTCTIMESTAMP_FIELD_NUMBER: builtins.int
    SYSTEMTIMEOFFSETMILLIS_FIELD_NUMBER: builtins.int
    RELAYBYRESOURCEID_FIELD_NUMBER: builtins.int
    SUBJECTRESOURCEID_FIELD_NUMBER: builtins.int
    SUBJECTPAIRERID_FIELD_NUMBER: builtins.int
    SUBJECTTYPENAME_FIELD_NUMBER: builtins.int
    SUBJECTINSTANCEID_FIELD_NUMBER: builtins.int
    SCHEMAVERSION_FIELD_NUMBER: builtins.int
    importance: wdl_event_importance_pb2.EventImportance.ValueType
    eventId: builtins.int
    relatedEventImportance: wdl_event_importance_pb2.EventImportance.ValueType
    relatedEventId: builtins.int
    systemTimeOffsetMillis: builtins.int
    relaybyResourceId: builtins.str
    subjectResourceId: builtins.str
    subjectPairerId: builtins.str
    subjectTypeName: builtins.str
    subjectInstanceId: builtins.str
    @property
    def data(self) -> google.protobuf.any_pb2.Any: ...
    @property
    def utcTimestamp(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def schemaVersion(self) -> nest.messages_pb2.SchemaVersion: ...
    def __init__(
        self,
        *,
        data: google.protobuf.any_pb2.Any | None = ...,
        importance: wdl_event_importance_pb2.EventImportance.ValueType = ...,
        eventId: builtins.int = ...,
        relatedEventImportance: wdl_event_importance_pb2.EventImportance.ValueType = ...,
        relatedEventId: builtins.int = ...,
        utcTimestamp: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        systemTimeOffsetMillis: builtins.int = ...,
        relaybyResourceId: builtins.str = ...,
        subjectResourceId: builtins.str = ...,
        subjectPairerId: builtins.str = ...,
        subjectTypeName: builtins.str = ...,
        subjectInstanceId: builtins.str = ...,
        schemaVersion: nest.messages_pb2.SchemaVersion | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["data", b"data", "schemaVersion", b"schemaVersion", "utcTimestamp", b"utcTimestamp"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["data", b"data", "eventId", b"eventId", "importance", b"importance", "relatedEventId", b"relatedEventId", "relatedEventImportance", b"relatedEventImportance", "relaybyResourceId", b"relaybyResourceId", "schemaVersion", b"schemaVersion", "subjectInstanceId", b"subjectInstanceId", "subjectPairerId", b"subjectPairerId", "subjectResourceId", b"subjectResourceId", "subjectTypeName", b"subjectTypeName", "systemTimeOffsetMillis", b"systemTimeOffsetMillis", "utcTimestamp", b"utcTimestamp"]) -> None: ...

global___Event = Event

@typing.final
class TraitRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RESOURCEID_FIELD_NUMBER: builtins.int
    TRAITLABEL_FIELD_NUMBER: builtins.int
    REQUESTID_FIELD_NUMBER: builtins.int
    resourceId: builtins.str
    traitLabel: builtins.str
    requestId: builtins.str
    def __init__(
        self,
        *,
        resourceId: builtins.str = ...,
        traitLabel: builtins.str = ...,
        requestId: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["requestId", b"requestId", "resourceId", b"resourceId", "traitLabel", b"traitLabel"]) -> None: ...

global___TraitRequest = TraitRequest

@typing.final
class TraitOperation(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _RequestCase:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _RequestCaseEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[TraitOperation._RequestCase.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        REQUEST_NOT_SET: TraitOperation._RequestCase.ValueType  # 0
        COMMAND: TraitOperation._RequestCase.ValueType  # 6
        UPDATE: TraitOperation._RequestCase.ValueType  # 7

    class RequestCase(_RequestCase, metaclass=_RequestCaseEnumTypeWrapper): ...
    REQUEST_NOT_SET: TraitOperation.RequestCase.ValueType  # 0
    COMMAND: TraitOperation.RequestCase.ValueType  # 6
    UPDATE: TraitOperation.RequestCase.ValueType  # 7

    class _State:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _StateEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[TraitOperation._State.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        STATE_UNSPECIFIED: TraitOperation._State.ValueType  # 0
        QUEUED: TraitOperation._State.ValueType  # 1
        PENDING: TraitOperation._State.ValueType  # 2
        STARTED: TraitOperation._State.ValueType  # 3
        COMPLETE: TraitOperation._State.ValueType  # 4

    class State(_State, metaclass=_StateEnumTypeWrapper): ...
    STATE_UNSPECIFIED: TraitOperation.State.ValueType  # 0
    QUEUED: TraitOperation.State.ValueType  # 1
    PENDING: TraitOperation.State.ValueType  # 2
    STARTED: TraitOperation.State.ValueType  # 3
    COMPLETE: TraitOperation.State.ValueType  # 4

    TRAITREQUEST_FIELD_NUMBER: builtins.int
    PROGRESS_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    EVENT_FIELD_NUMBER: builtins.int
    PUBLISHERACCEPTEDSTATEVERSION_FIELD_NUMBER: builtins.int
    COMMAND_FIELD_NUMBER: builtins.int
    UPDATE_FIELD_NUMBER: builtins.int
    progress: global___TraitOperation.State.ValueType
    publisherAcceptedStateVersion: builtins.int
    @property
    def traitRequest(self) -> global___TraitRequest: ...
    @property
    def status(self) -> google.rpc.status_pb2.Status: ...
    @property
    def event(self) -> global___TraitEvent: ...
    @property
    def command(self) -> global___TraitCommand: ...
    @property
    def update(self) -> global___TraitUpdateStateRequest: ...
    def __init__(
        self,
        *,
        traitRequest: global___TraitRequest | None = ...,
        progress: global___TraitOperation.State.ValueType = ...,
        status: google.rpc.status_pb2.Status | None = ...,
        event: global___TraitEvent | None = ...,
        publisherAcceptedStateVersion: builtins.int = ...,
        command: global___TraitCommand | None = ...,
        update: global___TraitUpdateStateRequest | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["command", b"command", "event", b"event", "status", b"status", "traitRequest", b"traitRequest", "update", b"update"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["command", b"command", "event", b"event", "progress", b"progress", "publisherAcceptedStateVersion", b"publisherAcceptedStateVersion", "status", b"status", "traitRequest", b"traitRequest", "update", b"update"]) -> None: ...

global___TraitOperation = TraitOperation

@typing.final
class TraitObserveRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TRAITREQUEST_FIELD_NUMBER: builtins.int
    FIELDMASK_FIELD_NUMBER: builtins.int
    MONOTONICVERSIONFILTER_FIELD_NUMBER: builtins.int
    INCLUDECONFIRMEDSTATE_FIELD_NUMBER: builtins.int
    INCLUDEPENDINGOPERATIONS_FIELD_NUMBER: builtins.int
    monotonicVersionFilter: builtins.int
    includeConfirmedState: builtins.bool
    includePendingOperations: builtins.bool
    @property
    def traitRequest(self) -> global___TraitRequest: ...
    @property
    def fieldMask(self) -> google.protobuf.field_mask_pb2.FieldMask: ...
    def __init__(
        self,
        *,
        traitRequest: global___TraitRequest | None = ...,
        fieldMask: google.protobuf.field_mask_pb2.FieldMask | None = ...,
        monotonicVersionFilter: builtins.int = ...,
        includeConfirmedState: builtins.bool = ...,
        includePendingOperations: builtins.bool = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["fieldMask", b"fieldMask", "traitRequest", b"traitRequest"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["fieldMask", b"fieldMask", "includeConfirmedState", b"includeConfirmedState", "includePendingOperations", b"includePendingOperations", "monotonicVersionFilter", b"monotonicVersionFilter", "traitRequest", b"traitRequest"]) -> None: ...

global___TraitObserveRequest = TraitObserveRequest

@typing.final
class TraitObserveResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TRAITREQUEST_FIELD_NUMBER: builtins.int
    ACCEPTEDSTATE_FIELD_NUMBER: builtins.int
    TRAITINFO_FIELD_NUMBER: builtins.int
    CONFIRMEDSTATE_FIELD_NUMBER: builtins.int
    PENDINGOPERATIONS_FIELD_NUMBER: builtins.int
    @property
    def traitRequest(self) -> global___TraitRequest: ...
    @property
    def acceptedState(self) -> global___TraitStateNotification: ...
    @property
    def traitInfo(self) -> global___TraitInfo: ...
    @property
    def confirmedState(self) -> global___TraitStateNotification: ...
    @property
    def pendingOperations(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___TraitOperation]: ...
    def __init__(
        self,
        *,
        traitRequest: global___TraitRequest | None = ...,
        acceptedState: global___TraitStateNotification | None = ...,
        traitInfo: global___TraitInfo | None = ...,
        confirmedState: global___TraitStateNotification | None = ...,
        pendingOperations: collections.abc.Iterable[global___TraitOperation] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["acceptedState", b"acceptedState", "confirmedState", b"confirmedState", "traitInfo", b"traitInfo", "traitRequest", b"traitRequest"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["acceptedState", b"acceptedState", "confirmedState", b"confirmedState", "pendingOperations", b"pendingOperations", "traitInfo", b"traitInfo", "traitRequest", b"traitRequest"]) -> None: ...

global___TraitObserveResponse = TraitObserveResponse

@typing.final
class TraitGetStateRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TRAITREQUEST_FIELD_NUMBER: builtins.int
    FIELDMASK_FIELD_NUMBER: builtins.int
    MONOTONICVERSIONFILTER_FIELD_NUMBER: builtins.int
    INCLUDECONFIRMEDSTATE_FIELD_NUMBER: builtins.int
    INCLUDEPENDINGOPERATIONS_FIELD_NUMBER: builtins.int
    monotonicVersionFilter: builtins.int
    includeConfirmedState: builtins.bool
    includePendingOperations: builtins.bool
    @property
    def traitRequest(self) -> global___TraitRequest: ...
    @property
    def fieldMask(self) -> google.protobuf.field_mask_pb2.FieldMask: ...
    def __init__(
        self,
        *,
        traitRequest: global___TraitRequest | None = ...,
        fieldMask: google.protobuf.field_mask_pb2.FieldMask | None = ...,
        monotonicVersionFilter: builtins.int = ...,
        includeConfirmedState: builtins.bool = ...,
        includePendingOperations: builtins.bool = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["fieldMask", b"fieldMask", "traitRequest", b"traitRequest"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["fieldMask", b"fieldMask", "includeConfirmedState", b"includeConfirmedState", "includePendingOperations", b"includePendingOperations", "monotonicVersionFilter", b"monotonicVersionFilter", "traitRequest", b"traitRequest"]) -> None: ...

global___TraitGetStateRequest = TraitGetStateRequest

@typing.final
class TraitGetStateResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TRAITREQUEST_FIELD_NUMBER: builtins.int
    ACCEPTEDSTATE_FIELD_NUMBER: builtins.int
    TRAITINFO_FIELD_NUMBER: builtins.int
    CONFIRMEDSTATE_FIELD_NUMBER: builtins.int
    @property
    def traitRequest(self) -> global___TraitRequest: ...
    @property
    def acceptedState(self) -> global___TraitStateNotification: ...
    @property
    def traitInfo(self) -> global___TraitInfo: ...
    @property
    def confirmedState(self) -> global___TraitStateNotification: ...
    def __init__(
        self,
        *,
        traitRequest: global___TraitRequest | None = ...,
        acceptedState: global___TraitStateNotification | None = ...,
        traitInfo: global___TraitInfo | None = ...,
        confirmedState: global___TraitStateNotification | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["acceptedState", b"acceptedState", "confirmedState", b"confirmedState", "traitInfo", b"traitInfo", "traitRequest", b"traitRequest"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["acceptedState", b"acceptedState", "confirmedState", b"confirmedState", "traitInfo", b"traitInfo", "traitRequest", b"traitRequest"]) -> None: ...

global___TraitGetStateResponse = TraitGetStateResponse

@typing.final
class TraitInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TRAITTYPE_FIELD_NUMBER: builtins.int
    SCHEMAVERSION_FIELD_NUMBER: builtins.int
    traitType: builtins.str
    @property
    def schemaVersion(self) -> nest.messages_pb2.SchemaVersion: ...
    def __init__(
        self,
        *,
        traitType: builtins.str = ...,
        schemaVersion: nest.messages_pb2.SchemaVersion | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["schemaVersion", b"schemaVersion"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["schemaVersion", b"schemaVersion", "traitType", b"traitType"]) -> None: ...

global___TraitInfo = TraitInfo

@typing.final
class TraitUpdateStateRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TRAITREQUEST_FIELD_NUMBER: builtins.int
    STATE_FIELD_NUMBER: builtins.int
    STATEMASK_FIELD_NUMBER: builtins.int
    MATCHPUBLISHERVERSION_FIELD_NUMBER: builtins.int
    SCHEMAVERSION_FIELD_NUMBER: builtins.int
    matchPublisherVersion: builtins.int
    @property
    def traitRequest(self) -> global___TraitRequest: ...
    @property
    def state(self) -> google.protobuf.any_pb2.Any: ...
    @property
    def stateMask(self) -> google.protobuf.field_mask_pb2.FieldMask: ...
    @property
    def schemaVersion(self) -> nest.messages_pb2.SchemaVersion: ...
    def __init__(
        self,
        *,
        traitRequest: global___TraitRequest | None = ...,
        state: google.protobuf.any_pb2.Any | None = ...,
        stateMask: google.protobuf.field_mask_pb2.FieldMask | None = ...,
        matchPublisherVersion: builtins.int = ...,
        schemaVersion: nest.messages_pb2.SchemaVersion | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["schemaVersion", b"schemaVersion", "state", b"state", "stateMask", b"stateMask", "traitRequest", b"traitRequest"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["matchPublisherVersion", b"matchPublisherVersion", "schemaVersion", b"schemaVersion", "state", b"state", "stateMask", b"stateMask", "traitRequest", b"traitRequest"]) -> None: ...

global___TraitUpdateStateRequest = TraitUpdateStateRequest

@typing.final
class TraitNotifyRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TRAITREQUEST_FIELD_NUMBER: builtins.int
    CONFIRMEDSTATE_FIELD_NUMBER: builtins.int
    EVENTS_FIELD_NUMBER: builtins.int
    @property
    def traitRequest(self) -> global___TraitRequest: ...
    @property
    def confirmedState(self) -> global___TraitStateNotification: ...
    @property
    def events(self) -> global___TraitEventsNotification: ...
    def __init__(
        self,
        *,
        traitRequest: global___TraitRequest | None = ...,
        confirmedState: global___TraitStateNotification | None = ...,
        events: global___TraitEventsNotification | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["confirmedState", b"confirmedState", "events", b"events", "traitRequest", b"traitRequest"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["confirmedState", b"confirmedState", "events", b"events", "traitRequest", b"traitRequest"]) -> None: ...

global___TraitNotifyRequest = TraitNotifyRequest

@typing.final
class TraitNotifyResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TRAITREQUEST_FIELD_NUMBER: builtins.int
    @property
    def traitRequest(self) -> global___TraitRequest: ...
    def __init__(
        self,
        *,
        traitRequest: global___TraitRequest | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["traitRequest", b"traitRequest"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["traitRequest", b"traitRequest"]) -> None: ...

global___TraitNotifyResponse = TraitNotifyResponse

@typing.final
class TraitEvent(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    EVENT_FIELD_NUMBER: builtins.int
    @property
    def event(self) -> google.protobuf.any_pb2.Any: ...
    def __init__(
        self,
        *,
        event: google.protobuf.any_pb2.Any | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["event", b"event"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["event", b"event"]) -> None: ...

global___TraitEvent = TraitEvent

@typing.final
class TraitCommand(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TRAITREQUEST_FIELD_NUMBER: builtins.int
    COMMAND_FIELD_NUMBER: builtins.int
    EXPIRYTIME_FIELD_NUMBER: builtins.int
    AUTHENTICATOR_FIELD_NUMBER: builtins.int
    MATCHPUBLISHERVERSION_FIELD_NUMBER: builtins.int
    SCHEMAVERSION_FIELD_NUMBER: builtins.int
    NAMESPACEID_FIELD_NUMBER: builtins.int
    authenticator: builtins.bytes
    matchPublisherVersion: builtins.int
    namespaceId: builtins.str
    @property
    def traitRequest(self) -> global___TraitRequest: ...
    @property
    def command(self) -> google.protobuf.any_pb2.Any: ...
    @property
    def expiryTime(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def schemaVersion(self) -> nest.messages_pb2.SchemaVersion: ...
    def __init__(
        self,
        *,
        traitRequest: global___TraitRequest | None = ...,
        command: google.protobuf.any_pb2.Any | None = ...,
        expiryTime: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        authenticator: builtins.bytes = ...,
        matchPublisherVersion: builtins.int = ...,
        schemaVersion: nest.messages_pb2.SchemaVersion | None = ...,
        namespaceId: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["command", b"command", "expiryTime", b"expiryTime", "schemaVersion", b"schemaVersion", "traitRequest", b"traitRequest"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["authenticator", b"authenticator", "command", b"command", "expiryTime", b"expiryTime", "matchPublisherVersion", b"matchPublisherVersion", "namespaceId", b"namespaceId", "schemaVersion", b"schemaVersion", "traitRequest", b"traitRequest"]) -> None: ...

global___TraitCommand = TraitCommand

@typing.final
class WeaveStatusReport(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PROFILEID_FIELD_NUMBER: builtins.int
    STATUSCODE_FIELD_NUMBER: builtins.int
    profileId: builtins.int
    statusCode: builtins.int
    def __init__(
        self,
        *,
        profileId: builtins.int = ...,
        statusCode: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["profileId", b"profileId", "statusCode", b"statusCode"]) -> None: ...

global___WeaveStatusReport = WeaveStatusReport

@typing.final
class ResourceRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RESOURCEID_FIELD_NUMBER: builtins.int
    REQUESTID_FIELD_NUMBER: builtins.int
    NAMESPACEID_FIELD_NUMBER: builtins.int
    resourceId: builtins.str
    requestId: builtins.str
    namespaceId: builtins.str
    def __init__(
        self,
        *,
        resourceId: builtins.str = ...,
        requestId: builtins.str = ...,
        namespaceId: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["namespaceId", b"namespaceId", "requestId", b"requestId", "resourceId", b"resourceId"]) -> None: ...

global___ResourceRequest = ResourceRequest

@typing.final
class ResourceObserveRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RESOURCEREQUEST_FIELD_NUMBER: builtins.int
    TRAITSTATEOBSERVES_FIELD_NUMBER: builtins.int
    INCLUDECONFIRMEDSTATE_FIELD_NUMBER: builtins.int
    INCLUDEPENDINGOPERATIONS_FIELD_NUMBER: builtins.int
    includeConfirmedState: builtins.bool
    includePendingOperations: builtins.bool
    @property
    def resourceRequest(self) -> global___ResourceRequest: ...
    @property
    def traitStateObserves(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___TraitStateObserve]: ...
    def __init__(
        self,
        *,
        resourceRequest: global___ResourceRequest | None = ...,
        traitStateObserves: collections.abc.Iterable[global___TraitStateObserve] | None = ...,
        includeConfirmedState: builtins.bool = ...,
        includePendingOperations: builtins.bool = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["resourceRequest", b"resourceRequest"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["includeConfirmedState", b"includeConfirmedState", "includePendingOperations", b"includePendingOperations", "resourceRequest", b"resourceRequest", "traitStateObserves", b"traitStateObserves"]) -> None: ...

global___ResourceObserveRequest = ResourceObserveRequest

@typing.final
class TraitStateObserve(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TRAITLABEL_FIELD_NUMBER: builtins.int
    FIELDMASK_FIELD_NUMBER: builtins.int
    MONOTONICVERSIONFILTER_FIELD_NUMBER: builtins.int
    traitLabel: builtins.str
    monotonicVersionFilter: builtins.int
    @property
    def fieldMask(self) -> google.protobuf.field_mask_pb2.FieldMask: ...
    def __init__(
        self,
        *,
        traitLabel: builtins.str = ...,
        fieldMask: google.protobuf.field_mask_pb2.FieldMask | None = ...,
        monotonicVersionFilter: builtins.int = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["fieldMask", b"fieldMask"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["fieldMask", b"fieldMask", "monotonicVersionFilter", b"monotonicVersionFilter", "traitLabel", b"traitLabel"]) -> None: ...

global___TraitStateObserve = TraitStateObserve

@typing.final
class ResourceObserveResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RESOURCEREQUEST_FIELD_NUMBER: builtins.int
    RESOURCEINFO_FIELD_NUMBER: builtins.int
    TRAITRESPONSES_FIELD_NUMBER: builtins.int
    @property
    def resourceRequest(self) -> global___ResourceRequest: ...
    @property
    def resourceInfo(self) -> global___ResourceInfo: ...
    @property
    def traitResponses(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___TraitObserveResponse]: ...
    def __init__(
        self,
        *,
        resourceRequest: global___ResourceRequest | None = ...,
        resourceInfo: global___ResourceInfo | None = ...,
        traitResponses: collections.abc.Iterable[global___TraitObserveResponse] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["resourceInfo", b"resourceInfo", "resourceRequest", b"resourceRequest"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["resourceInfo", b"resourceInfo", "resourceRequest", b"resourceRequest", "traitResponses", b"traitResponses"]) -> None: ...

global___ResourceObserveResponse = ResourceObserveResponse

@typing.final
class ResourceInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class TraitInfosEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        @property
        def value(self) -> global___TraitInfo: ...
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: global___TraitInfo | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["value", b"value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    RESOURCETYPE_FIELD_NUMBER: builtins.int
    TRAITINFOS_FIELD_NUMBER: builtins.int
    IFACEINFOS_FIELD_NUMBER: builtins.int
    CURRENTSCHEMAVERSION_FIELD_NUMBER: builtins.int
    resourceType: builtins.str
    currentSchemaVersion: builtins.int
    @property
    def traitInfos(self) -> google.protobuf.internal.containers.MessageMap[builtins.str, global___TraitInfo]: ...
    @property
    def ifaceInfos(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___IfaceInfo]: ...
    def __init__(
        self,
        *,
        resourceType: builtins.str = ...,
        traitInfos: collections.abc.Mapping[builtins.str, global___TraitInfo] | None = ...,
        ifaceInfos: collections.abc.Iterable[global___IfaceInfo] | None = ...,
        currentSchemaVersion: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["currentSchemaVersion", b"currentSchemaVersion", "ifaceInfos", b"ifaceInfos", "resourceType", b"resourceType", "traitInfos", b"traitInfos"]) -> None: ...

global___ResourceInfo = ResourceInfo

@typing.final
class IfaceInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    IFACETYPE_FIELD_NUMBER: builtins.int
    IFACETRAITINFOS_FIELD_NUMBER: builtins.int
    SCHEMAVERSION_FIELD_NUMBER: builtins.int
    ifaceType: builtins.str
    @property
    def ifaceTraitInfos(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___IfaceTraitInfo]: ...
    @property
    def schemaVersion(self) -> nest.messages_pb2.SchemaVersion: ...
    def __init__(
        self,
        *,
        ifaceType: builtins.str = ...,
        ifaceTraitInfos: collections.abc.Iterable[global___IfaceTraitInfo] | None = ...,
        schemaVersion: nest.messages_pb2.SchemaVersion | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["schemaVersion", b"schemaVersion"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["ifaceTraitInfos", b"ifaceTraitInfos", "ifaceType", b"ifaceType", "schemaVersion", b"schemaVersion"]) -> None: ...

global___IfaceInfo = IfaceInfo

@typing.final
class IfaceTraitInfo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    IFACETRAITLABEL_FIELD_NUMBER: builtins.int
    RESOURCETRAITLABEL_FIELD_NUMBER: builtins.int
    ifaceTraitLabel: builtins.str
    resourceTraitLabel: builtins.str
    def __init__(
        self,
        *,
        ifaceTraitLabel: builtins.str = ...,
        resourceTraitLabel: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["ifaceTraitLabel", b"ifaceTraitLabel", "resourceTraitLabel", b"resourceTraitLabel"]) -> None: ...

global___IfaceTraitInfo = IfaceTraitInfo

@typing.final
class ResourceGetStateRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RESOURCEREQUEST_FIELD_NUMBER: builtins.int
    RESOURCEGETSTATES_FIELD_NUMBER: builtins.int
    INCLUDECONFIRMEDSTATE_FIELD_NUMBER: builtins.int
    INCLUDEPENDINGOPERATIONS_FIELD_NUMBER: builtins.int
    includeConfirmedState: builtins.bool
    includePendingOperations: builtins.bool
    @property
    def resourceRequest(self) -> global___ResourceRequest: ...
    @property
    def resourceGetStates(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ResourceGetState]: ...
    def __init__(
        self,
        *,
        resourceRequest: global___ResourceRequest | None = ...,
        resourceGetStates: collections.abc.Iterable[global___ResourceGetState] | None = ...,
        includeConfirmedState: builtins.bool = ...,
        includePendingOperations: builtins.bool = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["resourceRequest", b"resourceRequest"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["includeConfirmedState", b"includeConfirmedState", "includePendingOperations", b"includePendingOperations", "resourceGetStates", b"resourceGetStates", "resourceRequest", b"resourceRequest"]) -> None: ...

global___ResourceGetStateRequest = ResourceGetStateRequest

@typing.final
class ResourceGetState(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TRAITLABEL_FIELD_NUMBER: builtins.int
    FIELDMASK_FIELD_NUMBER: builtins.int
    MONOTONICVERSIONFILTER_FIELD_NUMBER: builtins.int
    traitLabel: builtins.str
    monotonicVersionFilter: builtins.int
    @property
    def fieldMask(self) -> google.protobuf.field_mask_pb2.FieldMask: ...
    def __init__(
        self,
        *,
        traitLabel: builtins.str = ...,
        fieldMask: google.protobuf.field_mask_pb2.FieldMask | None = ...,
        monotonicVersionFilter: builtins.int = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["fieldMask", b"fieldMask"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["fieldMask", b"fieldMask", "monotonicVersionFilter", b"monotonicVersionFilter", "traitLabel", b"traitLabel"]) -> None: ...

global___ResourceGetState = ResourceGetState

@typing.final
class ResourceGetStateResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RESOURCEREQUEST_FIELD_NUMBER: builtins.int
    RESOURCEINFO_FIELD_NUMBER: builtins.int
    TRAITRESPONSES_FIELD_NUMBER: builtins.int
    @property
    def resourceRequest(self) -> global___ResourceRequest: ...
    @property
    def resourceInfo(self) -> global___ResourceInfo: ...
    @property
    def traitResponses(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___TraitGetStateResponse]: ...
    def __init__(
        self,
        *,
        resourceRequest: global___ResourceRequest | None = ...,
        resourceInfo: global___ResourceInfo | None = ...,
        traitResponses: collections.abc.Iterable[global___TraitGetStateResponse] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["resourceInfo", b"resourceInfo", "resourceRequest", b"resourceRequest"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["resourceInfo", b"resourceInfo", "resourceRequest", b"resourceRequest", "traitResponses", b"traitResponses"]) -> None: ...

global___ResourceGetStateResponse = ResourceGetStateResponse

@typing.final
class ResourceNotifyRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RESOURCEREQUEST_FIELD_NUMBER: builtins.int
    RESOURCESTATENOTIFIES_FIELD_NUMBER: builtins.int
    RESOURCEEVENTSNOTIFIES_FIELD_NUMBER: builtins.int
    @property
    def resourceRequest(self) -> global___ResourceRequest: ...
    @property
    def resourceStateNotifies(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ResourceStateNotify]: ...
    @property
    def resourceEventsNotifies(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ResourceEventsNotify]: ...
    def __init__(
        self,
        *,
        resourceRequest: global___ResourceRequest | None = ...,
        resourceStateNotifies: collections.abc.Iterable[global___ResourceStateNotify] | None = ...,
        resourceEventsNotifies: collections.abc.Iterable[global___ResourceEventsNotify] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["resourceRequest", b"resourceRequest"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["resourceEventsNotifies", b"resourceEventsNotifies", "resourceRequest", b"resourceRequest", "resourceStateNotifies", b"resourceStateNotifies"]) -> None: ...

global___ResourceNotifyRequest = ResourceNotifyRequest

@typing.final
class ResourceStateNotify(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TRAITLABEL_FIELD_NUMBER: builtins.int
    CONFIRMEDSTATE_FIELD_NUMBER: builtins.int
    traitLabel: builtins.str
    @property
    def confirmedState(self) -> global___TraitStateNotification: ...
    def __init__(
        self,
        *,
        traitLabel: builtins.str = ...,
        confirmedState: global___TraitStateNotification | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["confirmedState", b"confirmedState"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["confirmedState", b"confirmedState", "traitLabel", b"traitLabel"]) -> None: ...

global___ResourceStateNotify = ResourceStateNotify

@typing.final
class ResourceEventsNotify(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TRAITLABEL_FIELD_NUMBER: builtins.int
    EVENTS_FIELD_NUMBER: builtins.int
    traitLabel: builtins.str
    @property
    def events(self) -> global___TraitEventsNotification: ...
    def __init__(
        self,
        *,
        traitLabel: builtins.str = ...,
        events: global___TraitEventsNotification | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["events", b"events"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["events", b"events", "traitLabel", b"traitLabel"]) -> None: ...

global___ResourceEventsNotify = ResourceEventsNotify

@typing.final
class ResourceNotifyResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RESOURCEREQUEST_FIELD_NUMBER: builtins.int
    TRAITRESPONSES_FIELD_NUMBER: builtins.int
    @property
    def resourceRequest(self) -> global___ResourceRequest: ...
    @property
    def traitResponses(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___TraitNotifyResponse]: ...
    def __init__(
        self,
        *,
        resourceRequest: global___ResourceRequest | None = ...,
        traitResponses: collections.abc.Iterable[global___TraitNotifyResponse] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["resourceRequest", b"resourceRequest"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["resourceRequest", b"resourceRequest", "traitResponses", b"traitResponses"]) -> None: ...

global___ResourceNotifyResponse = ResourceNotifyResponse

@typing.final
class ResourceCommand(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TRAITLABEL_FIELD_NUMBER: builtins.int
    COMMAND_FIELD_NUMBER: builtins.int
    EXPIRYTIME_FIELD_NUMBER: builtins.int
    AUTHENTICATOR_FIELD_NUMBER: builtins.int
    MATCHPUBLISHERVERSION_FIELD_NUMBER: builtins.int
    SCHEMAVERSION_FIELD_NUMBER: builtins.int
    RESOURCETYPE_FIELD_NUMBER: builtins.int
    traitLabel: builtins.str
    authenticator: builtins.bytes
    matchPublisherVersion: builtins.int
    resourceType: builtins.str
    @property
    def command(self) -> google.protobuf.any_pb2.Any: ...
    @property
    def expiryTime(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def schemaVersion(self) -> nest.messages_pb2.SchemaVersion: ...
    def __init__(
        self,
        *,
        traitLabel: builtins.str = ...,
        command: google.protobuf.any_pb2.Any | None = ...,
        expiryTime: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        authenticator: builtins.bytes = ...,
        matchPublisherVersion: builtins.int = ...,
        schemaVersion: nest.messages_pb2.SchemaVersion | None = ...,
        resourceType: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["command", b"command", "expiryTime", b"expiryTime", "schemaVersion", b"schemaVersion"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["authenticator", b"authenticator", "command", b"command", "expiryTime", b"expiryTime", "matchPublisherVersion", b"matchPublisherVersion", "resourceType", b"resourceType", "schemaVersion", b"schemaVersion", "traitLabel", b"traitLabel"]) -> None: ...

global___ResourceCommand = ResourceCommand

@typing.final
class SendCommandRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RESOURCEREQUEST_FIELD_NUMBER: builtins.int
    RESOURCECOMMANDS_FIELD_NUMBER: builtins.int
    @property
    def resourceRequest(self) -> global___ResourceRequest: ...
    @property
    def resourceCommands(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ResourceCommand]: ...
    def __init__(
        self,
        *,
        resourceRequest: global___ResourceRequest | None = ...,
        resourceCommands: collections.abc.Iterable[global___ResourceCommand] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["resourceRequest", b"resourceRequest"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["resourceCommands", b"resourceCommands", "resourceRequest", b"resourceRequest"]) -> None: ...

global___SendCommandRequest = SendCommandRequest

@typing.final
class SendCommandResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class ResourceCommandResponse(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        RESOURCEREQUEST_FIELD_NUMBER: builtins.int
        TRAITOPERATIONS_FIELD_NUMBER: builtins.int
        @property
        def resourceRequest(self) -> global___ResourceRequest: ...
        @property
        def traitOperations(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___TraitOperation]: ...
        def __init__(
            self,
            *,
            resourceRequest: global___ResourceRequest | None = ...,
            traitOperations: collections.abc.Iterable[global___TraitOperation] | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["resourceRequest", b"resourceRequest"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["resourceRequest", b"resourceRequest", "traitOperations", b"traitOperations"]) -> None: ...

    SENDCOMMANDRESPONSE_FIELD_NUMBER: builtins.int
    @property
    def sendCommandResponse(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___SendCommandResponse.ResourceCommandResponse]: ...
    def __init__(
        self,
        *,
        sendCommandResponse: collections.abc.Iterable[global___SendCommandResponse.ResourceCommandResponse] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["sendCommandResponse", b"sendCommandResponse"]) -> None: ...

global___SendCommandResponse = SendCommandResponse

@typing.final
class BatchUpdateStateRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BATCHUPDATESTATEREQUEST_FIELD_NUMBER: builtins.int
    @property
    def batchUpdateStateRequest(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___TraitUpdateStateRequest]: ...
    def __init__(
        self,
        *,
        batchUpdateStateRequest: collections.abc.Iterable[global___TraitUpdateStateRequest] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["batchUpdateStateRequest", b"batchUpdateStateRequest"]) -> None: ...

global___BatchUpdateStateRequest = BatchUpdateStateRequest

@typing.final
class BatchUpdateStateResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class TraitOperationStateResponse(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        TRAITOPERATIONS_FIELD_NUMBER: builtins.int
        @property
        def traitOperations(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___TraitOperation]: ...
        def __init__(
            self,
            *,
            traitOperations: collections.abc.Iterable[global___TraitOperation] | None = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["traitOperations", b"traitOperations"]) -> None: ...

    BATCHUPDATESTATERESPONSE_FIELD_NUMBER: builtins.int
    @property
    def batchUpdateStateResponse(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___BatchUpdateStateResponse.TraitOperationStateResponse]: ...
    def __init__(
        self,
        *,
        batchUpdateStateResponse: collections.abc.Iterable[global___BatchUpdateStateResponse.TraitOperationStateResponse] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["batchUpdateStateResponse", b"batchUpdateStateResponse"]) -> None: ...

global___BatchUpdateStateResponse = BatchUpdateStateResponse
