"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.any_pb2
import google.protobuf.descriptor
import google.protobuf.field_mask_pb2
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.timestamp_pb2
from ...nest import messages_pb2
from ...nestlabs.gateway import v1_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _ResourceStatus:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _ResourceStatusEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ResourceStatus.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    NORMAL: _ResourceStatus.ValueType  # 0
    ADDED: _ResourceStatus.ValueType  # 1
    REMOVED: _ResourceStatus.ValueType  # 2

class ResourceStatus(_ResourceStatus, metaclass=_ResourceStatusEnumTypeWrapper): ...

NORMAL: ResourceStatus.ValueType  # 0
ADDED: ResourceStatus.ValueType  # 1
REMOVED: ResourceStatus.ValueType  # 2
global___ResourceStatus = ResourceStatus

class _StateType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _StateTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_StateType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    STATE_TYPE_UNSPECIFIED: _StateType.ValueType  # 0
    CONFIRMED: _StateType.ValueType  # 1
    ACCEPTED: _StateType.ValueType  # 2

class StateType(_StateType, metaclass=_StateTypeEnumTypeWrapper): ...

STATE_TYPE_UNSPECIFIED: StateType.ValueType  # 0
CONFIRMED: StateType.ValueType  # 1
ACCEPTED: StateType.ValueType  # 2
global___StateType = StateType

@typing.final
class TraitMeta(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TRAITLABEL_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    SCHEMAVERSION_FIELD_NUMBER: builtins.int
    traitLabel: builtins.str
    type: builtins.str
    @property
    def schemaVersion(self) -> nest.messages_pb2.SchemaVersion: ...
    def __init__(
        self,
        *,
        traitLabel: builtins.str = ...,
        type: builtins.str = ...,
        schemaVersion: nest.messages_pb2.SchemaVersion | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["schemaVersion", b"schemaVersion"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["schemaVersion", b"schemaVersion", "traitLabel", b"traitLabel", "type", b"type"]) -> None: ...

global___TraitMeta = TraitMeta

@typing.final
class IfaceMeta(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class TraitLabelMappingEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    IFACELABEL_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    TRAITLABELMAPPING_FIELD_NUMBER: builtins.int
    SCHEMAVERSION_FIELD_NUMBER: builtins.int
    ifaceLabel: builtins.str
    type: builtins.str
    @property
    def traitLabelMapping(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]: ...
    @property
    def schemaVersion(self) -> nest.messages_pb2.SchemaVersion: ...
    def __init__(
        self,
        *,
        ifaceLabel: builtins.str = ...,
        type: builtins.str = ...,
        traitLabelMapping: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
        schemaVersion: nest.messages_pb2.SchemaVersion | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["schemaVersion", b"schemaVersion"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["ifaceLabel", b"ifaceLabel", "schemaVersion", b"schemaVersion", "traitLabelMapping", b"traitLabelMapping", "type", b"type"]) -> None: ...

global___IfaceMeta = IfaceMeta

@typing.final
class ResourceMeta(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RESOURCEID_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    TRAITMETAS_FIELD_NUMBER: builtins.int
    CURRENTSCHEMAVERSION_FIELD_NUMBER: builtins.int
    IFACEMETAS_FIELD_NUMBER: builtins.int
    resourceId: builtins.str
    type: builtins.str
    status: global___ResourceStatus.ValueType
    currentSchemaVersion: builtins.int
    @property
    def traitMetas(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___TraitMeta]: ...
    @property
    def ifaceMetas(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___IfaceMeta]: ...
    def __init__(
        self,
        *,
        resourceId: builtins.str = ...,
        type: builtins.str = ...,
        status: global___ResourceStatus.ValueType = ...,
        traitMetas: collections.abc.Iterable[global___TraitMeta] | None = ...,
        currentSchemaVersion: builtins.int = ...,
        ifaceMetas: collections.abc.Iterable[global___IfaceMeta] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["currentSchemaVersion", b"currentSchemaVersion", "ifaceMetas", b"ifaceMetas", "resourceId", b"resourceId", "status", b"status", "traitMetas", b"traitMetas", "type", b"type"]) -> None: ...

global___ResourceMeta = ResourceMeta

@typing.final
class TraitId(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RESOURCEID_FIELD_NUMBER: builtins.int
    TRAITLABEL_FIELD_NUMBER: builtins.int
    resourceId: builtins.str
    traitLabel: builtins.str
    def __init__(
        self,
        *,
        resourceId: builtins.str = ...,
        traitLabel: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["resourceId", b"resourceId", "traitLabel", b"traitLabel"]) -> None: ...

global___TraitId = TraitId

@typing.final
class Patch(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VALUES_FIELD_NUMBER: builtins.int
    @property
    def values(self) -> google.protobuf.any_pb2.Any: ...
    def __init__(
        self,
        *,
        values: google.protobuf.any_pb2.Any | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["values", b"values"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["values", b"values"]) -> None: ...

global___Patch = Patch

@typing.final
class TraitState(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TRAITID_FIELD_NUMBER: builtins.int
    STATETYPES_FIELD_NUMBER: builtins.int
    PATCH_FIELD_NUMBER: builtins.int
    MONOTONICVERSION_FIELD_NUMBER: builtins.int
    PUBLISHERVERSION_FIELD_NUMBER: builtins.int
    monotonicVersion: builtins.int
    publisherVersion: builtins.int
    @property
    def traitId(self) -> global___TraitId: ...
    @property
    def stateTypes(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[global___StateType.ValueType]: ...
    @property
    def patch(self) -> global___Patch: ...
    def __init__(
        self,
        *,
        traitId: global___TraitId | None = ...,
        stateTypes: collections.abc.Iterable[global___StateType.ValueType] | None = ...,
        patch: global___Patch | None = ...,
        monotonicVersion: builtins.int = ...,
        publisherVersion: builtins.int = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["patch", b"patch", "traitId", b"traitId"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["monotonicVersion", b"monotonicVersion", "patch", b"patch", "publisherVersion", b"publisherVersion", "stateTypes", b"stateTypes", "traitId", b"traitId"]) -> None: ...

global___TraitState = TraitState

@typing.final
class TraitTypeObserveParams(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TRAITTYPE_FIELD_NUMBER: builtins.int
    STATEFIELDMASK_FIELD_NUMBER: builtins.int
    OBSERVERSCHEMAVERSION_FIELD_NUMBER: builtins.int
    traitType: builtins.str
    observerSchemaVersion: builtins.int
    @property
    def stateFieldMask(self) -> google.protobuf.field_mask_pb2.FieldMask: ...
    def __init__(
        self,
        *,
        traitType: builtins.str = ...,
        stateFieldMask: google.protobuf.field_mask_pb2.FieldMask | None = ...,
        observerSchemaVersion: builtins.int = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["stateFieldMask", b"stateFieldMask"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["observerSchemaVersion", b"observerSchemaVersion", "stateFieldMask", b"stateFieldMask", "traitType", b"traitType"]) -> None: ...

global___TraitTypeObserveParams = TraitTypeObserveParams

@typing.final
class TraitInstanceObserveParams(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TRAITID_FIELD_NUMBER: builtins.int
    MONOTONICVERSIONFILTERS_FIELD_NUMBER: builtins.int
    @property
    def traitId(self) -> global___TraitId: ...
    @property
    def monotonicVersionFilters(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    def __init__(
        self,
        *,
        traitId: global___TraitId | None = ...,
        monotonicVersionFilters: collections.abc.Iterable[builtins.int] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["traitId", b"traitId"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["monotonicVersionFilters", b"monotonicVersionFilters", "traitId", b"traitId"]) -> None: ...

global___TraitInstanceObserveParams = TraitInstanceObserveParams

@typing.final
class ObserveRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STATETYPES_FIELD_NUMBER: builtins.int
    RESOURCEIDS_FIELD_NUMBER: builtins.int
    TRAITTYPEPARAMS_FIELD_NUMBER: builtins.int
    TRAITINSTANCEPARAMS_FIELD_NUMBER: builtins.int
    USERID_FIELD_NUMBER: builtins.int
    userId: builtins.str
    @property
    def stateTypes(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[global___StateType.ValueType]: ...
    @property
    def resourceIds(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
    @property
    def traitTypeParams(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___TraitTypeObserveParams]: ...
    @property
    def traitInstanceParams(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___TraitInstanceObserveParams]: ...
    def __init__(
        self,
        *,
        stateTypes: collections.abc.Iterable[global___StateType.ValueType] | None = ...,
        resourceIds: collections.abc.Iterable[builtins.str] | None = ...,
        traitTypeParams: collections.abc.Iterable[global___TraitTypeObserveParams] | None = ...,
        traitInstanceParams: collections.abc.Iterable[global___TraitInstanceObserveParams] | None = ...,
        userId: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["resourceIds", b"resourceIds", "stateTypes", b"stateTypes", "traitInstanceParams", b"traitInstanceParams", "traitTypeParams", b"traitTypeParams", "userId", b"userId"]) -> None: ...

global___ObserveRequest = ObserveRequest

@typing.final
class TraitOperationList(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TRAITID_FIELD_NUMBER: builtins.int
    TRAITOPERATIONS_FIELD_NUMBER: builtins.int
    @property
    def traitId(self) -> global___TraitId: ...
    @property
    def traitOperations(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[nestlabs.gateway.v1_pb2.TraitOperation]: ...
    def __init__(
        self,
        *,
        traitId: global___TraitId | None = ...,
        traitOperations: collections.abc.Iterable[nestlabs.gateway.v1_pb2.TraitOperation] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["traitId", b"traitId"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["traitId", b"traitId", "traitOperations", b"traitOperations"]) -> None: ...

global___TraitOperationList = TraitOperationList

@typing.final
class ObserveResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class ObserveResponse(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        RESOURCEMETAS_FIELD_NUMBER: builtins.int
        INITIALRESOURCEMETASCONTINUE_FIELD_NUMBER: builtins.int
        TRAITSTATES_FIELD_NUMBER: builtins.int
        TRAITOPERATIONLISTS_FIELD_NUMBER: builtins.int
        CURRENTTIME_FIELD_NUMBER: builtins.int
        initialResourceMetasContinue: builtins.bool
        @property
        def resourceMetas(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ResourceMeta]: ...
        @property
        def traitStates(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___TraitState]: ...
        @property
        def traitOperationLists(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___TraitOperationList]: ...
        @property
        def currentTime(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
        def __init__(
            self,
            *,
            resourceMetas: collections.abc.Iterable[global___ResourceMeta] | None = ...,
            initialResourceMetasContinue: builtins.bool = ...,
            traitStates: collections.abc.Iterable[global___TraitState] | None = ...,
            traitOperationLists: collections.abc.Iterable[global___TraitOperationList] | None = ...,
            currentTime: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["currentTime", b"currentTime"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["currentTime", b"currentTime", "initialResourceMetasContinue", b"initialResourceMetasContinue", "resourceMetas", b"resourceMetas", "traitOperationLists", b"traitOperationLists", "traitStates", b"traitStates"]) -> None: ...

    OBSERVERESPONSE_FIELD_NUMBER: builtins.int
    @property
    def observeResponse(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___ObserveResponse.ObserveResponse]: ...
    def __init__(
        self,
        *,
        observeResponse: collections.abc.Iterable[global___ObserveResponse.ObserveResponse] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["observeResponse", b"observeResponse"]) -> None: ...

global___ObserveResponse = ObserveResponse
