"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _EventImportance:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _EventImportanceEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_EventImportance.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    EVENT_IMPORTANCE_UNSPECIFIED: _EventImportance.ValueType  # 0
    EVENT_IMPORTANCE_PRODUCTION_CRITICAL: _EventImportance.ValueType  # 1
    EVENT_IMPORTANCE_PRODUCTION_STANDARD: _EventImportance.ValueType  # 2
    EVENT_IMPORTANCE_INFO: _EventImportance.ValueType  # 3
    EVENT_IMPORTANCE_DEBUG: _EventImportance.ValueType  # 4

class EventImportance(_EventImportance, metaclass=_EventImportanceEnumTypeWrapper): ...

EVENT_IMPORTANCE_UNSPECIFIED: EventImportance.ValueType  # 0
EVENT_IMPORTANCE_PRODUCTION_CRITICAL: EventImportance.ValueType  # 1
EVENT_IMPORTANCE_PRODUCTION_STANDARD: EventImportance.ValueType  # 2
EVENT_IMPORTANCE_INFO: EventImportance.ValueType  # 3
EVENT_IMPORTANCE_DEBUG: EventImportance.ValueType  # 4
global___EventImportance = EventImportance
