"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class SchemaVersion(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CURRENTVERSION_FIELD_NUMBER: builtins.int
    MINCOMPATVERSION_FIELD_NUMBER: builtins.int
    currentVersion: builtins.int
    minCompatVersion: builtins.int
    def __init__(
        self,
        *,
        currentVersion: builtins.int = ...,
        minCompatVersion: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["currentVersion", b"currentVersion", "minCompatVersion", b"minCompatVersion"]) -> None: ...

global___SchemaVersion = SchemaVersion
