"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.duration_pb2
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.timestamp_pb2
import sys
import typing
from .. import wdl_event_importance_pb2

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _DayOfWeek:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _DayOfWeekEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_DayOfWeek.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    DAY_OF_WEEK_UNSPECIFIED: _DayOfWeek.ValueType  # 0
    DAY_OF_WEEK_SUNDAY: _DayOfWeek.ValueType  # 1
    DAY_OF_WEEK_MONDAY: _DayOfWeek.ValueType  # 2
    DAY_OF_WEEK_TUESDAY: _DayOfWeek.ValueType  # 4
    DAY_OF_WEEK_WEDNESDAY: _DayOfWeek.ValueType  # 8
    DAY_OF_WEEK_THURSDAY: _DayOfWeek.ValueType  # 16
    DAY_OF_WEEK_FRIDAY: _DayOfWeek.ValueType  # 32
    DAY_OF_WEEK_SATURDAY: _DayOfWeek.ValueType  # 64

class DayOfWeek(_DayOfWeek, metaclass=_DayOfWeekEnumTypeWrapper): ...

DAY_OF_WEEK_UNSPECIFIED: DayOfWeek.ValueType  # 0
DAY_OF_WEEK_SUNDAY: DayOfWeek.ValueType  # 1
DAY_OF_WEEK_MONDAY: DayOfWeek.ValueType  # 2
DAY_OF_WEEK_TUESDAY: DayOfWeek.ValueType  # 4
DAY_OF_WEEK_WEDNESDAY: DayOfWeek.ValueType  # 8
DAY_OF_WEEK_THURSDAY: DayOfWeek.ValueType  # 16
DAY_OF_WEEK_FRIDAY: DayOfWeek.ValueType  # 32
DAY_OF_WEEK_SATURDAY: DayOfWeek.ValueType  # 64
global___DayOfWeek = DayOfWeek

class _MonthOfYear:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _MonthOfYearEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_MonthOfYear.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    MONTH_OF_YEAR_UNSPECIFIED: _MonthOfYear.ValueType  # 0
    MONTH_OF_YEAR_JANUARY: _MonthOfYear.ValueType  # 1
    MONTH_OF_YEAR_FEBRUARY: _MonthOfYear.ValueType  # 2
    MONTH_OF_YEAR_MARCH: _MonthOfYear.ValueType  # 4
    MONTH_OF_YEAR_APRIL: _MonthOfYear.ValueType  # 8
    MONTH_OF_YEAR_MAY: _MonthOfYear.ValueType  # 16
    MONTH_OF_YEAR_JUNE: _MonthOfYear.ValueType  # 32
    MONTH_OF_YEAR_JULY: _MonthOfYear.ValueType  # 64
    MONTH_OF_YEAR_AUGUST: _MonthOfYear.ValueType  # 128
    MONTH_OF_YEAR_SEPTEMBER: _MonthOfYear.ValueType  # 256
    MONTH_OF_YEAR_OCTOBER: _MonthOfYear.ValueType  # 512
    MONTH_OF_YEAR_NOVEMBER: _MonthOfYear.ValueType  # 1024
    MONTH_OF_YEAR_DECEMBER: _MonthOfYear.ValueType  # 2048

class MonthOfYear(_MonthOfYear, metaclass=_MonthOfYearEnumTypeWrapper): ...

MONTH_OF_YEAR_UNSPECIFIED: MonthOfYear.ValueType  # 0
MONTH_OF_YEAR_JANUARY: MonthOfYear.ValueType  # 1
MONTH_OF_YEAR_FEBRUARY: MonthOfYear.ValueType  # 2
MONTH_OF_YEAR_MARCH: MonthOfYear.ValueType  # 4
MONTH_OF_YEAR_APRIL: MonthOfYear.ValueType  # 8
MONTH_OF_YEAR_MAY: MonthOfYear.ValueType  # 16
MONTH_OF_YEAR_JUNE: MonthOfYear.ValueType  # 32
MONTH_OF_YEAR_JULY: MonthOfYear.ValueType  # 64
MONTH_OF_YEAR_AUGUST: MonthOfYear.ValueType  # 128
MONTH_OF_YEAR_SEPTEMBER: MonthOfYear.ValueType  # 256
MONTH_OF_YEAR_OCTOBER: MonthOfYear.ValueType  # 512
MONTH_OF_YEAR_NOVEMBER: MonthOfYear.ValueType  # 1024
MONTH_OF_YEAR_DECEMBER: MonthOfYear.ValueType  # 2048
global___MonthOfYear = MonthOfYear

class _ResourceType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _ResourceTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_ResourceType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    RESOURCE_TYPE_UNSPECIFIED: _ResourceType.ValueType  # 0
    RESOURCE_TYPE_DEVICE: _ResourceType.ValueType  # 1
    RESOURCE_TYPE_USER: _ResourceType.ValueType  # 2
    RESOURCE_TYPE_ACCOUNT: _ResourceType.ValueType  # 3
    RESOURCE_TYPE_AREA: _ResourceType.ValueType  # 4
    RESOURCE_TYPE_FIXTURE: _ResourceType.ValueType  # 5
    RESOURCE_TYPE_GROUP: _ResourceType.ValueType  # 6
    RESOURCE_TYPE_ANNOTATION: _ResourceType.ValueType  # 7
    RESOURCE_TYPE_STRUCTURE: _ResourceType.ValueType  # 8
    RESOURCE_TYPE_GUEST: _ResourceType.ValueType  # 9
    RESOURCE_TYPE_SERVICE: _ResourceType.ValueType  # 10

class ResourceType(_ResourceType, metaclass=_ResourceTypeEnumTypeWrapper): ...

RESOURCE_TYPE_UNSPECIFIED: ResourceType.ValueType  # 0
RESOURCE_TYPE_DEVICE: ResourceType.ValueType  # 1
RESOURCE_TYPE_USER: ResourceType.ValueType  # 2
RESOURCE_TYPE_ACCOUNT: ResourceType.ValueType  # 3
RESOURCE_TYPE_AREA: ResourceType.ValueType  # 4
RESOURCE_TYPE_FIXTURE: ResourceType.ValueType  # 5
RESOURCE_TYPE_GROUP: ResourceType.ValueType  # 6
RESOURCE_TYPE_ANNOTATION: ResourceType.ValueType  # 7
RESOURCE_TYPE_STRUCTURE: ResourceType.ValueType  # 8
RESOURCE_TYPE_GUEST: ResourceType.ValueType  # 9
RESOURCE_TYPE_SERVICE: ResourceType.ValueType  # 10
global___ResourceType = ResourceType

class _QuantityType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _QuantityTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_QuantityType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    QUANTITY_TYPE_UNSPECIFIED: _QuantityType.ValueType  # 0
    LENGTH: _QuantityType.ValueType  # 1
    MASS: _QuantityType.ValueType  # 2
    DURATION: _QuantityType.ValueType  # 3
    CURRENT: _QuantityType.ValueType  # 4
    TEMPERATURE: _QuantityType.ValueType  # 5
    LUMINOUS_INTENSITY: _QuantityType.ValueType  # 6
    AREA: _QuantityType.ValueType  # 7
    VOLUME: _QuantityType.ValueType  # 8
    VELOCITY: _QuantityType.ValueType  # 9
    ACCELERATION: _QuantityType.ValueType  # 10
    FREQUENCY: _QuantityType.ValueType  # 27
    ENERGY: _QuantityType.ValueType  # 30
    ELECTRIC_CHARGE: _QuantityType.ValueType  # 32
    VOLTAGE: _QuantityType.ValueType  # 33
    RESISTANCE: _QuantityType.ValueType  # 34
    MAGNETIC_FLUX_DENSITY: _QuantityType.ValueType  # 38
    ILLUMINANCE: _QuantityType.ValueType  # 42
    HUMIDITY: _QuantityType.ValueType  # 46
    DBM: _QuantityType.ValueType  # 47
    PPM: _QuantityType.ValueType  # 48
    PIRMEASUREMENT: _QuantityType.ValueType  # 256
    NORMALIZED: _QuantityType.ValueType  # 257
    ANGLE: _QuantityType.ValueType  # 259

class QuantityType(_QuantityType, metaclass=_QuantityTypeEnumTypeWrapper): ...

QUANTITY_TYPE_UNSPECIFIED: QuantityType.ValueType  # 0
LENGTH: QuantityType.ValueType  # 1
MASS: QuantityType.ValueType  # 2
DURATION: QuantityType.ValueType  # 3
CURRENT: QuantityType.ValueType  # 4
TEMPERATURE: QuantityType.ValueType  # 5
LUMINOUS_INTENSITY: QuantityType.ValueType  # 6
AREA: QuantityType.ValueType  # 7
VOLUME: QuantityType.ValueType  # 8
VELOCITY: QuantityType.ValueType  # 9
ACCELERATION: QuantityType.ValueType  # 10
FREQUENCY: QuantityType.ValueType  # 27
ENERGY: QuantityType.ValueType  # 30
ELECTRIC_CHARGE: QuantityType.ValueType  # 32
VOLTAGE: QuantityType.ValueType  # 33
RESISTANCE: QuantityType.ValueType  # 34
MAGNETIC_FLUX_DENSITY: QuantityType.ValueType  # 38
ILLUMINANCE: QuantityType.ValueType  # 42
HUMIDITY: QuantityType.ValueType  # 46
DBM: QuantityType.ValueType  # 47
PPM: QuantityType.ValueType  # 48
PIRMEASUREMENT: QuantityType.ValueType  # 256
NORMALIZED: QuantityType.ValueType  # 257
ANGLE: QuantityType.ValueType  # 259
global___QuantityType = QuantityType

@typing.final
class ResourceId(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RESOURCEID_FIELD_NUMBER: builtins.int
    resourceId: builtins.str
    def __init__(
        self,
        *,
        resourceId: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["resourceId", b"resourceId"]) -> None: ...

global___ResourceId = ResourceId

@typing.final
class ResourceName(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RESOURCENAME_FIELD_NUMBER: builtins.int
    resourceName: builtins.str
    def __init__(
        self,
        *,
        resourceName: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["resourceName", b"resourceName"]) -> None: ...

global___ResourceName = ResourceName

@typing.final
class TraitTypeId(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TRAITTYPEID_FIELD_NUMBER: builtins.int
    traitTypeId: builtins.int
    def __init__(
        self,
        *,
        traitTypeId: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["traitTypeId", b"traitTypeId"]) -> None: ...

global___TraitTypeId = TraitTypeId

@typing.final
class TraitTypeInstance(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TRAITTYPEID_FIELD_NUMBER: builtins.int
    INSTANCEID_FIELD_NUMBER: builtins.int
    instanceId: builtins.int
    @property
    def traitTypeId(self) -> global___TraitTypeId: ...
    def __init__(
        self,
        *,
        traitTypeId: global___TraitTypeId | None = ...,
        instanceId: builtins.int = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["traitTypeId", b"traitTypeId"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["instanceId", b"instanceId", "traitTypeId", b"traitTypeId"]) -> None: ...

global___TraitTypeInstance = TraitTypeInstance

@typing.final
class TraitInstanceId(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _TraitInstanceCase:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _TraitInstanceCaseEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[TraitInstanceId._TraitInstanceCase.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        TRAIT_INSTANCE_NOT_SET: TraitInstanceId._TraitInstanceCase.ValueType  # 0
        TRAIT_INSTANCE_LABEL: TraitInstanceId._TraitInstanceCase.ValueType  # 1
        TRAIT_INSTANCE_ID: TraitInstanceId._TraitInstanceCase.ValueType  # 2

    class TraitInstanceCase(_TraitInstanceCase, metaclass=_TraitInstanceCaseEnumTypeWrapper): ...
    TRAIT_INSTANCE_NOT_SET: TraitInstanceId.TraitInstanceCase.ValueType  # 0
    TRAIT_INSTANCE_LABEL: TraitInstanceId.TraitInstanceCase.ValueType  # 1
    TRAIT_INSTANCE_ID: TraitInstanceId.TraitInstanceCase.ValueType  # 2

    TRAITINSTANCELABEL_FIELD_NUMBER: builtins.int
    TRAITINSTANCEID_FIELD_NUMBER: builtins.int
    traitInstanceLabel: builtins.str
    @property
    def traitInstanceId(self) -> global___TraitTypeInstance: ...
    def __init__(
        self,
        *,
        traitInstanceLabel: builtins.str = ...,
        traitInstanceId: global___TraitTypeInstance | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["traitInstanceId", b"traitInstanceId"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["traitInstanceId", b"traitInstanceId", "traitInstanceLabel", b"traitInstanceLabel"]) -> None: ...

global___TraitInstanceId = TraitInstanceId

@typing.final
class FullTraitInstanceId(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RESOURCEID_FIELD_NUMBER: builtins.int
    TRAITINSTANCEID_FIELD_NUMBER: builtins.int
    @property
    def resourceId(self) -> global___ResourceId: ...
    @property
    def traitInstanceId(self) -> global___TraitInstanceId: ...
    def __init__(
        self,
        *,
        resourceId: global___ResourceId | None = ...,
        traitInstanceId: global___TraitInstanceId | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["resourceId", b"resourceId", "traitInstanceId", b"traitInstanceId"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["resourceId", b"resourceId", "traitInstanceId", b"traitInstanceId"]) -> None: ...

global___FullTraitInstanceId = FullTraitInstanceId

@typing.final
class InterfaceName(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    INTERFACENAME_FIELD_NUMBER: builtins.int
    interfaceName: builtins.str
    def __init__(
        self,
        *,
        interfaceName: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["interfaceName", b"interfaceName"]) -> None: ...

global___InterfaceName = InterfaceName

@typing.final
class EventId(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RESOURCEID_FIELD_NUMBER: builtins.int
    IMPORTANCE_FIELD_NUMBER: builtins.int
    ID_FIELD_NUMBER: builtins.int
    importance: wdl_event_importance_pb2.EventImportance.ValueType
    id: builtins.int
    @property
    def resourceId(self) -> global___ResourceId: ...
    def __init__(
        self,
        *,
        resourceId: global___ResourceId | None = ...,
        importance: wdl_event_importance_pb2.EventImportance.ValueType = ...,
        id: builtins.int = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["resourceId", b"resourceId"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["id", b"id", "importance", b"importance", "resourceId", b"resourceId"]) -> None: ...

global___EventId = EventId

@typing.final
class ProfileSpecificStatusCode(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PROFILEID_FIELD_NUMBER: builtins.int
    STATUSCODE_FIELD_NUMBER: builtins.int
    profileId: builtins.int
    statusCode: builtins.int
    def __init__(
        self,
        *,
        profileId: builtins.int = ...,
        statusCode: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["profileId", b"profileId", "statusCode", b"statusCode"]) -> None: ...

global___ProfileSpecificStatusCode = ProfileSpecificStatusCode

@typing.final
class StringRef(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _StringRefCase:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _StringRefCaseEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[StringRef._StringRefCase.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        STRING_REF_NOT_SET: StringRef._StringRefCase.ValueType  # 0
        LITERAL: StringRef._StringRefCase.ValueType  # 1
        REFERENCE: StringRef._StringRefCase.ValueType  # 2

    class StringRefCase(_StringRefCase, metaclass=_StringRefCaseEnumTypeWrapper): ...
    STRING_REF_NOT_SET: StringRef.StringRefCase.ValueType  # 0
    LITERAL: StringRef.StringRefCase.ValueType  # 1
    REFERENCE: StringRef.StringRefCase.ValueType  # 2

    LITERAL_FIELD_NUMBER: builtins.int
    REFERENCE_FIELD_NUMBER: builtins.int
    literal: builtins.str
    reference: builtins.int
    def __init__(
        self,
        *,
        literal: builtins.str = ...,
        reference: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["literal", b"literal", "reference", b"reference"]) -> None: ...

global___StringRef = StringRef

@typing.final
class Timer(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TIME_FIELD_NUMBER: builtins.int
    TIMEBASIS_FIELD_NUMBER: builtins.int
    @property
    def time(self) -> google.protobuf.duration_pb2.Duration: ...
    @property
    def timeBasis(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        time: google.protobuf.duration_pb2.Duration | None = ...,
        timeBasis: google.protobuf.timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["time", b"time", "timeBasis", b"timeBasis"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["time", b"time", "timeBasis", b"timeBasis"]) -> None: ...

global___Timer = Timer

@typing.final
class TimeOfDay(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HOUR_FIELD_NUMBER: builtins.int
    MINUTE_FIELD_NUMBER: builtins.int
    SECOND_FIELD_NUMBER: builtins.int
    hour: builtins.int
    minute: builtins.int
    second: builtins.int
    def __init__(
        self,
        *,
        hour: builtins.int = ...,
        minute: builtins.int = ...,
        second: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["hour", b"hour", "minute", b"minute", "second", b"second"]) -> None: ...

global___TimeOfDay = TimeOfDay
