"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import google.protobuf.wrappers_pb2
import typing
from ...weave import common_pb2

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class SoftwareComponentTrait(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class SoftwareComponentTypeStruct(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        COMPONENTNAME_FIELD_NUMBER: builtins.int
        COMPONENTVERSION_FIELD_NUMBER: builtins.int
        componentName: builtins.str
        componentVersion: builtins.str
        def __init__(
            self,
            *,
            componentName: builtins.str = ...,
            componentVersion: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["componentName", b"componentName", "componentVersion", b"componentVersion"]) -> None: ...

    SOFTWARECOMPONENTS_FIELD_NUMBER: builtins.int
    @property
    def softwareComponents(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___SoftwareComponentTrait.SoftwareComponentTypeStruct]: ...
    def __init__(
        self,
        *,
        softwareComponents: collections.abc.Iterable[global___SoftwareComponentTrait.SoftwareComponentTypeStruct] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["softwareComponents", b"softwareComponents"]) -> None: ...

global___SoftwareComponentTrait = SoftwareComponentTrait

@typing.final
class DeviceIdentityTrait(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VENDORID_FIELD_NUMBER: builtins.int
    VENDORIDDESCRIPTION_FIELD_NUMBER: builtins.int
    VENDORPRODUCTID_FIELD_NUMBER: builtins.int
    PRODUCTIDDESCRIPTION_FIELD_NUMBER: builtins.int
    PRODUCTREVISION_FIELD_NUMBER: builtins.int
    SERIALNUMBER_FIELD_NUMBER: builtins.int
    SOFTWAREVERSION_FIELD_NUMBER: builtins.int
    MANUFACTURINGDATE_FIELD_NUMBER: builtins.int
    DEVICEID_FIELD_NUMBER: builtins.int
    FABRICID_FIELD_NUMBER: builtins.int
    vendorId: builtins.int
    vendorProductId: builtins.int
    productRevision: builtins.int
    serialNumber: builtins.str
    softwareVersion: builtins.str
    fabricId: builtins.int
    @property
    def vendorIdDescription(self) -> weave.common_pb2.StringRef: ...
    @property
    def productIdDescription(self) -> weave.common_pb2.StringRef: ...
    @property
    def manufacturingDate(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def deviceId(self) -> weave.common_pb2.ResourceId: ...
    def __init__(
        self,
        *,
        vendorId: builtins.int = ...,
        vendorIdDescription: weave.common_pb2.StringRef | None = ...,
        vendorProductId: builtins.int = ...,
        productIdDescription: weave.common_pb2.StringRef | None = ...,
        productRevision: builtins.int = ...,
        serialNumber: builtins.str = ...,
        softwareVersion: builtins.str = ...,
        manufacturingDate: google.protobuf.wrappers_pb2.StringValue | None = ...,
        deviceId: weave.common_pb2.ResourceId | None = ...,
        fabricId: builtins.int = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["deviceId", b"deviceId", "manufacturingDate", b"manufacturingDate", "productIdDescription", b"productIdDescription", "vendorIdDescription", b"vendorIdDescription"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["deviceId", b"deviceId", "fabricId", b"fabricId", "manufacturingDate", b"manufacturingDate", "productIdDescription", b"productIdDescription", "productRevision", b"productRevision", "serialNumber", b"serialNumber", "softwareVersion", b"softwareVersion", "vendorId", b"vendorId", "vendorIdDescription", b"vendorIdDescription", "vendorProductId", b"vendorProductId"]) -> None: ...

global___DeviceIdentityTrait = DeviceIdentityTrait

@typing.final
class LabelSettingsTrait(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LABEL_FIELD_NUMBER: builtins.int
    label: builtins.str
    def __init__(
        self,
        *,
        label: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["label", b"label"]) -> None: ...

global___LabelSettingsTrait = LabelSettingsTrait
