"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.duration_pb2
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.timestamp_pb2
import google.protobuf.wrappers_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class LivenessTrait(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _LivenessDeviceStatus:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _LivenessDeviceStatusEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[LivenessTrait._LivenessDeviceStatus.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        LIVENESS_DEVICE_STATUS_UNSPECIFIED: LivenessTrait._LivenessDeviceStatus.ValueType  # 0
        LIVENESS_DEVICE_STATUS_ONLINE: LivenessTrait._LivenessDeviceStatus.ValueType  # 1
        LIVENESS_DEVICE_STATUS_UNREACHABLE: LivenessTrait._LivenessDeviceStatus.ValueType  # 2
        LIVENESS_DEVICE_STATUS_UNINITIALIZED: LivenessTrait._LivenessDeviceStatus.ValueType  # 3
        LIVENESS_DEVICE_STATUS_REBOOTING: LivenessTrait._LivenessDeviceStatus.ValueType  # 4
        LIVENESS_DEVICE_STATUS_UPGRADING: LivenessTrait._LivenessDeviceStatus.ValueType  # 5
        LIVENESS_DEVICE_STATUS_SCHEDULED_DOWN: LivenessTrait._LivenessDeviceStatus.ValueType  # 6

    class LivenessDeviceStatus(_LivenessDeviceStatus, metaclass=_LivenessDeviceStatusEnumTypeWrapper): ...
    LIVENESS_DEVICE_STATUS_UNSPECIFIED: LivenessTrait.LivenessDeviceStatus.ValueType  # 0
    LIVENESS_DEVICE_STATUS_ONLINE: LivenessTrait.LivenessDeviceStatus.ValueType  # 1
    LIVENESS_DEVICE_STATUS_UNREACHABLE: LivenessTrait.LivenessDeviceStatus.ValueType  # 2
    LIVENESS_DEVICE_STATUS_UNINITIALIZED: LivenessTrait.LivenessDeviceStatus.ValueType  # 3
    LIVENESS_DEVICE_STATUS_REBOOTING: LivenessTrait.LivenessDeviceStatus.ValueType  # 4
    LIVENESS_DEVICE_STATUS_UPGRADING: LivenessTrait.LivenessDeviceStatus.ValueType  # 5
    LIVENESS_DEVICE_STATUS_SCHEDULED_DOWN: LivenessTrait.LivenessDeviceStatus.ValueType  # 6

    class _DeviceFrontendType:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _DeviceFrontendTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[LivenessTrait._DeviceFrontendType.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        DEVICE_FRONTEND_TYPE_UNSPECIFIED: LivenessTrait._DeviceFrontendType.ValueType  # 0
        DEVICE_FRONTEND_TYPE_LYCRA: LivenessTrait._DeviceFrontendType.ValueType  # 1
        DEVICE_FRONTEND_TYPE_WEAVE_FE_1: LivenessTrait._DeviceFrontendType.ValueType  # 2

    class DeviceFrontendType(_DeviceFrontendType, metaclass=_DeviceFrontendTypeEnumTypeWrapper): ...
    DEVICE_FRONTEND_TYPE_UNSPECIFIED: LivenessTrait.DeviceFrontendType.ValueType  # 0
    DEVICE_FRONTEND_TYPE_LYCRA: LivenessTrait.DeviceFrontendType.ValueType  # 1
    DEVICE_FRONTEND_TYPE_WEAVE_FE_1: LivenessTrait.DeviceFrontendType.ValueType  # 2

    @typing.final
    class LivenessChangeEvent(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        STATUS_FIELD_NUMBER: builtins.int
        HEARTBEATSTATUS_FIELD_NUMBER: builtins.int
        NOTIFYREQUESTUNRESPONSIVENESS_FIELD_NUMBER: builtins.int
        COMMANDREQUESTUNRESPONSIVENESS_FIELD_NUMBER: builtins.int
        PREVSTATUS_FIELD_NUMBER: builtins.int
        TUNNELDISCONNECTED_FIELD_NUMBER: builtins.int
        LASTCONTACTEDTIME_FIELD_NUMBER: builtins.int
        LASTWDMHEARTBEATTIME_FIELD_NUMBER: builtins.int
        TUNNELCLOSEDTIME_FIELD_NUMBER: builtins.int
        TIMESTATUSCHANGED_FIELD_NUMBER: builtins.int
        TIMEPREVSTATUSCHANGED_FIELD_NUMBER: builtins.int
        FRONTEND_FIELD_NUMBER: builtins.int
        DISCONNECTED_FIELD_NUMBER: builtins.int
        DISCONNECTEDTIMESTATUSCHANGED_FIELD_NUMBER: builtins.int
        CONNECTIONCLOSEDTIME_FIELD_NUMBER: builtins.int
        TRAITLABEL_FIELD_NUMBER: builtins.int
        status: global___LivenessTrait.LivenessDeviceStatus.ValueType
        heartbeatStatus: global___LivenessTrait.LivenessDeviceStatus.ValueType
        prevStatus: global___LivenessTrait.LivenessDeviceStatus.ValueType
        @property
        def notifyRequestUnresponsiveness(self) -> google.protobuf.wrappers_pb2.BoolValue: ...
        @property
        def commandRequestUnresponsiveness(self) -> google.protobuf.wrappers_pb2.BoolValue: ...
        @property
        def tunnelDisconnected(self) -> google.protobuf.wrappers_pb2.BoolValue: ...
        @property
        def lastContactedTime(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
        @property
        def lastWdmHeartbeatTime(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
        @property
        def tunnelClosedTime(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
        @property
        def timeStatusChanged(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
        @property
        def timePrevStatusChanged(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
        @property
        def frontend(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[global___LivenessTrait.DeviceFrontendType.ValueType]: ...
        @property
        def disconnected(self) -> google.protobuf.wrappers_pb2.BoolValue: ...
        @property
        def disconnectedTimeStatusChanged(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
        @property
        def connectionClosedTime(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
        @property
        def traitLabel(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        def __init__(
            self,
            *,
            status: global___LivenessTrait.LivenessDeviceStatus.ValueType = ...,
            heartbeatStatus: global___LivenessTrait.LivenessDeviceStatus.ValueType = ...,
            notifyRequestUnresponsiveness: google.protobuf.wrappers_pb2.BoolValue | None = ...,
            commandRequestUnresponsiveness: google.protobuf.wrappers_pb2.BoolValue | None = ...,
            prevStatus: global___LivenessTrait.LivenessDeviceStatus.ValueType = ...,
            tunnelDisconnected: google.protobuf.wrappers_pb2.BoolValue | None = ...,
            lastContactedTime: google.protobuf.timestamp_pb2.Timestamp | None = ...,
            lastWdmHeartbeatTime: google.protobuf.timestamp_pb2.Timestamp | None = ...,
            tunnelClosedTime: google.protobuf.timestamp_pb2.Timestamp | None = ...,
            timeStatusChanged: google.protobuf.timestamp_pb2.Timestamp | None = ...,
            timePrevStatusChanged: google.protobuf.timestamp_pb2.Timestamp | None = ...,
            frontend: collections.abc.Iterable[global___LivenessTrait.DeviceFrontendType.ValueType] | None = ...,
            disconnected: google.protobuf.wrappers_pb2.BoolValue | None = ...,
            disconnectedTimeStatusChanged: google.protobuf.timestamp_pb2.Timestamp | None = ...,
            connectionClosedTime: google.protobuf.timestamp_pb2.Timestamp | None = ...,
            traitLabel: google.protobuf.wrappers_pb2.StringValue | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["commandRequestUnresponsiveness", b"commandRequestUnresponsiveness", "connectionClosedTime", b"connectionClosedTime", "disconnected", b"disconnected", "disconnectedTimeStatusChanged", b"disconnectedTimeStatusChanged", "lastContactedTime", b"lastContactedTime", "lastWdmHeartbeatTime", b"lastWdmHeartbeatTime", "notifyRequestUnresponsiveness", b"notifyRequestUnresponsiveness", "timePrevStatusChanged", b"timePrevStatusChanged", "timeStatusChanged", b"timeStatusChanged", "traitLabel", b"traitLabel", "tunnelClosedTime", b"tunnelClosedTime", "tunnelDisconnected", b"tunnelDisconnected"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["commandRequestUnresponsiveness", b"commandRequestUnresponsiveness", "connectionClosedTime", b"connectionClosedTime", "disconnected", b"disconnected", "disconnectedTimeStatusChanged", b"disconnectedTimeStatusChanged", "frontend", b"frontend", "heartbeatStatus", b"heartbeatStatus", "lastContactedTime", b"lastContactedTime", "lastWdmHeartbeatTime", b"lastWdmHeartbeatTime", "notifyRequestUnresponsiveness", b"notifyRequestUnresponsiveness", "prevStatus", b"prevStatus", "status", b"status", "timePrevStatusChanged", b"timePrevStatusChanged", "timeStatusChanged", b"timeStatusChanged", "traitLabel", b"traitLabel", "tunnelClosedTime", b"tunnelClosedTime", "tunnelDisconnected", b"tunnelDisconnected"]) -> None: ...

    @typing.final
    class LivenessConnectedSignalEvent(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        CONNECTIONID_FIELD_NUMBER: builtins.int
        FRONTEND_FIELD_NUMBER: builtins.int
        OCCURRENCETIME_FIELD_NUMBER: builtins.int
        CONNECTIONTAG_FIELD_NUMBER: builtins.int
        connectionId: builtins.str
        frontend: global___LivenessTrait.DeviceFrontendType.ValueType
        @property
        def occurrenceTime(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
        @property
        def connectionTag(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        def __init__(
            self,
            *,
            connectionId: builtins.str = ...,
            frontend: global___LivenessTrait.DeviceFrontendType.ValueType = ...,
            occurrenceTime: google.protobuf.timestamp_pb2.Timestamp | None = ...,
            connectionTag: google.protobuf.wrappers_pb2.StringValue | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["connectionTag", b"connectionTag", "occurrenceTime", b"occurrenceTime"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["connectionId", b"connectionId", "connectionTag", b"connectionTag", "frontend", b"frontend", "occurrenceTime", b"occurrenceTime"]) -> None: ...

    @typing.final
    class LivenessDisconnectedSignalEvent(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        CONNECTIONID_FIELD_NUMBER: builtins.int
        FRONTEND_FIELD_NUMBER: builtins.int
        OCCURRENCETIME_FIELD_NUMBER: builtins.int
        CONNECTIONTAG_FIELD_NUMBER: builtins.int
        connectionId: builtins.str
        frontend: global___LivenessTrait.DeviceFrontendType.ValueType
        @property
        def occurrenceTime(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
        @property
        def connectionTag(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        def __init__(
            self,
            *,
            connectionId: builtins.str = ...,
            frontend: global___LivenessTrait.DeviceFrontendType.ValueType = ...,
            occurrenceTime: google.protobuf.timestamp_pb2.Timestamp | None = ...,
            connectionTag: google.protobuf.wrappers_pb2.StringValue | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["connectionTag", b"connectionTag", "occurrenceTime", b"occurrenceTime"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["connectionId", b"connectionId", "connectionTag", b"connectionTag", "frontend", b"frontend", "occurrenceTime", b"occurrenceTime"]) -> None: ...

    STATUS_FIELD_NUMBER: builtins.int
    TIMESTATUSCHANGED_FIELD_NUMBER: builtins.int
    MAXINACTIVITYDURATION_FIELD_NUMBER: builtins.int
    HEARTBEATSTATUS_FIELD_NUMBER: builtins.int
    TIMEHEARTBEATSTATUSCHANGED_FIELD_NUMBER: builtins.int
    NOTIFYREQUESTUNRESPONSIVENESS_FIELD_NUMBER: builtins.int
    NOTIFYREQUESTUNRESPONSIVENESSTIMESTATUSCHANGED_FIELD_NUMBER: builtins.int
    COMMANDREQUESTUNRESPONSIVENESS_FIELD_NUMBER: builtins.int
    COMMANDREQUESTUNRESPONSIVENESSTIMESTATUSCHANGED_FIELD_NUMBER: builtins.int
    PUBLISHERNAME_FIELD_NUMBER: builtins.int
    TUNNELDISCONNECTED_FIELD_NUMBER: builtins.int
    TUNNELDISCONNECTEDTIMESTATUSCHANGED_FIELD_NUMBER: builtins.int
    LASTCONTACTEDTIME_FIELD_NUMBER: builtins.int
    LASTWDMHEARTBEATTIME_FIELD_NUMBER: builtins.int
    TUNNELCLOSEDTIME_FIELD_NUMBER: builtins.int
    FRONTEND_FIELD_NUMBER: builtins.int
    DISCONNECTED_FIELD_NUMBER: builtins.int
    DISCONNECTEDTIMESTATUSCHANGED_FIELD_NUMBER: builtins.int
    CONNECTIONCLOSEDTIME_FIELD_NUMBER: builtins.int
    status: global___LivenessTrait.LivenessDeviceStatus.ValueType
    heartbeatStatus: global___LivenessTrait.LivenessDeviceStatus.ValueType
    @property
    def timeStatusChanged(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def maxInactivityDuration(self) -> google.protobuf.duration_pb2.Duration: ...
    @property
    def timeHeartbeatStatusChanged(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def notifyRequestUnresponsiveness(self) -> google.protobuf.wrappers_pb2.BoolValue: ...
    @property
    def notifyRequestUnresponsivenessTimeStatusChanged(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def commandRequestUnresponsiveness(self) -> google.protobuf.wrappers_pb2.BoolValue: ...
    @property
    def commandRequestUnresponsivenessTimeStatusChanged(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def publisherName(self) -> google.protobuf.wrappers_pb2.StringValue: ...
    @property
    def tunnelDisconnected(self) -> google.protobuf.wrappers_pb2.BoolValue: ...
    @property
    def tunnelDisconnectedTimeStatusChanged(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def lastContactedTime(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def lastWdmHeartbeatTime(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def tunnelClosedTime(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def frontend(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[global___LivenessTrait.DeviceFrontendType.ValueType]: ...
    @property
    def disconnected(self) -> google.protobuf.wrappers_pb2.BoolValue: ...
    @property
    def disconnectedTimeStatusChanged(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def connectionClosedTime(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        status: global___LivenessTrait.LivenessDeviceStatus.ValueType = ...,
        timeStatusChanged: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        maxInactivityDuration: google.protobuf.duration_pb2.Duration | None = ...,
        heartbeatStatus: global___LivenessTrait.LivenessDeviceStatus.ValueType = ...,
        timeHeartbeatStatusChanged: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        notifyRequestUnresponsiveness: google.protobuf.wrappers_pb2.BoolValue | None = ...,
        notifyRequestUnresponsivenessTimeStatusChanged: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        commandRequestUnresponsiveness: google.protobuf.wrappers_pb2.BoolValue | None = ...,
        commandRequestUnresponsivenessTimeStatusChanged: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        publisherName: google.protobuf.wrappers_pb2.StringValue | None = ...,
        tunnelDisconnected: google.protobuf.wrappers_pb2.BoolValue | None = ...,
        tunnelDisconnectedTimeStatusChanged: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        lastContactedTime: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        lastWdmHeartbeatTime: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        tunnelClosedTime: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        frontend: collections.abc.Iterable[global___LivenessTrait.DeviceFrontendType.ValueType] | None = ...,
        disconnected: google.protobuf.wrappers_pb2.BoolValue | None = ...,
        disconnectedTimeStatusChanged: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        connectionClosedTime: google.protobuf.timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["commandRequestUnresponsiveness", b"commandRequestUnresponsiveness", "commandRequestUnresponsivenessTimeStatusChanged", b"commandRequestUnresponsivenessTimeStatusChanged", "connectionClosedTime", b"connectionClosedTime", "disconnected", b"disconnected", "disconnectedTimeStatusChanged", b"disconnectedTimeStatusChanged", "lastContactedTime", b"lastContactedTime", "lastWdmHeartbeatTime", b"lastWdmHeartbeatTime", "maxInactivityDuration", b"maxInactivityDuration", "notifyRequestUnresponsiveness", b"notifyRequestUnresponsiveness", "notifyRequestUnresponsivenessTimeStatusChanged", b"notifyRequestUnresponsivenessTimeStatusChanged", "publisherName", b"publisherName", "timeHeartbeatStatusChanged", b"timeHeartbeatStatusChanged", "timeStatusChanged", b"timeStatusChanged", "tunnelClosedTime", b"tunnelClosedTime", "tunnelDisconnected", b"tunnelDisconnected", "tunnelDisconnectedTimeStatusChanged", b"tunnelDisconnectedTimeStatusChanged"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["commandRequestUnresponsiveness", b"commandRequestUnresponsiveness", "commandRequestUnresponsivenessTimeStatusChanged", b"commandRequestUnresponsivenessTimeStatusChanged", "connectionClosedTime", b"connectionClosedTime", "disconnected", b"disconnected", "disconnectedTimeStatusChanged", b"disconnectedTimeStatusChanged", "frontend", b"frontend", "heartbeatStatus", b"heartbeatStatus", "lastContactedTime", b"lastContactedTime", "lastWdmHeartbeatTime", b"lastWdmHeartbeatTime", "maxInactivityDuration", b"maxInactivityDuration", "notifyRequestUnresponsiveness", b"notifyRequestUnresponsiveness", "notifyRequestUnresponsivenessTimeStatusChanged", b"notifyRequestUnresponsivenessTimeStatusChanged", "publisherName", b"publisherName", "status", b"status", "timeHeartbeatStatusChanged", b"timeHeartbeatStatusChanged", "timeStatusChanged", b"timeStatusChanged", "tunnelClosedTime", b"tunnelClosedTime", "tunnelDisconnected", b"tunnelDisconnected", "tunnelDisconnectedTimeStatusChanged", b"tunnelDisconnectedTimeStatusChanged"]) -> None: ...

global___LivenessTrait = LivenessTrait
