"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.wrappers_pb2
import sys
import typing
from ...weave import common_pb2

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class PowerSourceTrait(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _PowerSourceCondition:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _PowerSourceConditionEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[PowerSourceTrait._PowerSourceCondition.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        POWER_SOURCE_CONDITION_UNSPECIFIED: PowerSourceTrait._PowerSourceCondition.ValueType  # 0
        POWER_SOURCE_CONDITION_NOMINAL: PowerSourceTrait._PowerSourceCondition.ValueType  # 1
        POWER_SOURCE_CONDITION_CRITICAL: PowerSourceTrait._PowerSourceCondition.ValueType  # 2

    class PowerSourceCondition(_PowerSourceCondition, metaclass=_PowerSourceConditionEnumTypeWrapper): ...
    POWER_SOURCE_CONDITION_UNSPECIFIED: PowerSourceTrait.PowerSourceCondition.ValueType  # 0
    POWER_SOURCE_CONDITION_NOMINAL: PowerSourceTrait.PowerSourceCondition.ValueType  # 1
    POWER_SOURCE_CONDITION_CRITICAL: PowerSourceTrait.PowerSourceCondition.ValueType  # 2

    class _PowerSourceStatus:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _PowerSourceStatusEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[PowerSourceTrait._PowerSourceStatus.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        POWER_SOURCE_STATUS_UNSPECIFIED: PowerSourceTrait._PowerSourceStatus.ValueType  # 0
        POWER_SOURCE_STATUS_ACTIVE: PowerSourceTrait._PowerSourceStatus.ValueType  # 1
        POWER_SOURCE_STATUS_STANDBY: PowerSourceTrait._PowerSourceStatus.ValueType  # 2
        POWER_SOURCE_STATUS_INACTIVE: PowerSourceTrait._PowerSourceStatus.ValueType  # 3

    class PowerSourceStatus(_PowerSourceStatus, metaclass=_PowerSourceStatusEnumTypeWrapper): ...
    POWER_SOURCE_STATUS_UNSPECIFIED: PowerSourceTrait.PowerSourceStatus.ValueType  # 0
    POWER_SOURCE_STATUS_ACTIVE: PowerSourceTrait.PowerSourceStatus.ValueType  # 1
    POWER_SOURCE_STATUS_STANDBY: PowerSourceTrait.PowerSourceStatus.ValueType  # 2
    POWER_SOURCE_STATUS_INACTIVE: PowerSourceTrait.PowerSourceStatus.ValueType  # 3

    @typing.final
    class PowerSourceChangedEvent(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        CONDITION_FIELD_NUMBER: builtins.int
        STATUS_FIELD_NUMBER: builtins.int
        condition: global___PowerSourceTrait.PowerSourceCondition.ValueType
        status: global___PowerSourceTrait.PowerSourceStatus.ValueType
        def __init__(
            self,
            *,
            condition: global___PowerSourceTrait.PowerSourceCondition.ValueType = ...,
            status: global___PowerSourceTrait.PowerSourceStatus.ValueType = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["condition", b"condition", "status", b"status"]) -> None: ...

    TYPE_FIELD_NUMBER: builtins.int
    ASSESSEDVOLTAGE_FIELD_NUMBER: builtins.int
    ASSESSEDCURRENT_FIELD_NUMBER: builtins.int
    ASSESSEDFREQUENCY_FIELD_NUMBER: builtins.int
    CONDITION_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    PRESENT_FIELD_NUMBER: builtins.int
    type: global___PowerSourceCapabilitiesTrait.PowerSourceType.ValueType
    condition: global___PowerSourceTrait.PowerSourceCondition.ValueType
    status: global___PowerSourceTrait.PowerSourceStatus.ValueType
    present: builtins.bool
    @property
    def assessedVoltage(self) -> google.protobuf.wrappers_pb2.FloatValue: ...
    @property
    def assessedCurrent(self) -> google.protobuf.wrappers_pb2.FloatValue: ...
    @property
    def assessedFrequency(self) -> google.protobuf.wrappers_pb2.FloatValue: ...
    def __init__(
        self,
        *,
        type: global___PowerSourceCapabilitiesTrait.PowerSourceType.ValueType = ...,
        assessedVoltage: google.protobuf.wrappers_pb2.FloatValue | None = ...,
        assessedCurrent: google.protobuf.wrappers_pb2.FloatValue | None = ...,
        assessedFrequency: google.protobuf.wrappers_pb2.FloatValue | None = ...,
        condition: global___PowerSourceTrait.PowerSourceCondition.ValueType = ...,
        status: global___PowerSourceTrait.PowerSourceStatus.ValueType = ...,
        present: builtins.bool = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["assessedCurrent", b"assessedCurrent", "assessedFrequency", b"assessedFrequency", "assessedVoltage", b"assessedVoltage"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["assessedCurrent", b"assessedCurrent", "assessedFrequency", b"assessedFrequency", "assessedVoltage", b"assessedVoltage", "condition", b"condition", "present", b"present", "status", b"status", "type", b"type"]) -> None: ...

global___PowerSourceTrait = PowerSourceTrait

@typing.final
class PowerSourceCapabilitiesTrait(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _PowerSourceType:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _PowerSourceTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[PowerSourceCapabilitiesTrait._PowerSourceType.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        POWER_SOURCE_TYPE_UNSPECIFIED: PowerSourceCapabilitiesTrait._PowerSourceType.ValueType  # 0
        POWER_SOURCE_TYPE_BATTERY: PowerSourceCapabilitiesTrait._PowerSourceType.ValueType  # 1
        POWER_SOURCE_TYPE_RECHARGEABLE_BATTERY: PowerSourceCapabilitiesTrait._PowerSourceType.ValueType  # 2

    class PowerSourceType(_PowerSourceType, metaclass=_PowerSourceTypeEnumTypeWrapper): ...
    POWER_SOURCE_TYPE_UNSPECIFIED: PowerSourceCapabilitiesTrait.PowerSourceType.ValueType  # 0
    POWER_SOURCE_TYPE_BATTERY: PowerSourceCapabilitiesTrait.PowerSourceType.ValueType  # 1
    POWER_SOURCE_TYPE_RECHARGEABLE_BATTERY: PowerSourceCapabilitiesTrait.PowerSourceType.ValueType  # 2

    class _PowerSourceCurrentType:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _PowerSourceCurrentTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[PowerSourceCapabilitiesTrait._PowerSourceCurrentType.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        POWER_SOURCE_CURRENT_TYPE_UNSPECIFIED: PowerSourceCapabilitiesTrait._PowerSourceCurrentType.ValueType  # 0
        POWER_SOURCE_CURRENT_TYPE_DC: PowerSourceCapabilitiesTrait._PowerSourceCurrentType.ValueType  # 1
        POWER_SOURCE_CURRENT_TYPE_AC: PowerSourceCapabilitiesTrait._PowerSourceCurrentType.ValueType  # 2

    class PowerSourceCurrentType(_PowerSourceCurrentType, metaclass=_PowerSourceCurrentTypeEnumTypeWrapper): ...
    POWER_SOURCE_CURRENT_TYPE_UNSPECIFIED: PowerSourceCapabilitiesTrait.PowerSourceCurrentType.ValueType  # 0
    POWER_SOURCE_CURRENT_TYPE_DC: PowerSourceCapabilitiesTrait.PowerSourceCurrentType.ValueType  # 1
    POWER_SOURCE_CURRENT_TYPE_AC: PowerSourceCapabilitiesTrait.PowerSourceCurrentType.ValueType  # 2

    TYPE_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    NOMINALVOLTAGE_FIELD_NUMBER: builtins.int
    MAXIMUMCURRENT_FIELD_NUMBER: builtins.int
    CURRENTTYPE_FIELD_NUMBER: builtins.int
    ORDER_FIELD_NUMBER: builtins.int
    REMOVABLE_FIELD_NUMBER: builtins.int
    type: global___PowerSourceCapabilitiesTrait.PowerSourceType.ValueType
    nominalVoltage: builtins.float
    currentType: global___PowerSourceCapabilitiesTrait.PowerSourceCurrentType.ValueType
    order: builtins.int
    removable: builtins.bool
    @property
    def description(self) -> weave.common_pb2.StringRef: ...
    @property
    def maximumCurrent(self) -> google.protobuf.wrappers_pb2.FloatValue: ...
    def __init__(
        self,
        *,
        type: global___PowerSourceCapabilitiesTrait.PowerSourceType.ValueType = ...,
        description: weave.common_pb2.StringRef | None = ...,
        nominalVoltage: builtins.float = ...,
        maximumCurrent: google.protobuf.wrappers_pb2.FloatValue | None = ...,
        currentType: global___PowerSourceCapabilitiesTrait.PowerSourceCurrentType.ValueType = ...,
        order: builtins.int = ...,
        removable: builtins.bool = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["description", b"description", "maximumCurrent", b"maximumCurrent"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["currentType", b"currentType", "description", b"description", "maximumCurrent", b"maximumCurrent", "nominalVoltage", b"nominalVoltage", "order", b"order", "removable", b"removable", "type", b"type"]) -> None: ...

global___PowerSourceCapabilitiesTrait = PowerSourceCapabilitiesTrait

@typing.final
class BatteryPowerSourceTrait(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _BatteryReplacementIndicator:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _BatteryReplacementIndicatorEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[BatteryPowerSourceTrait._BatteryReplacementIndicator.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        BATTERY_REPLACEMENT_INDICATOR_UNSPECIFIED: BatteryPowerSourceTrait._BatteryReplacementIndicator.ValueType  # 0
        BATTERY_REPLACEMENT_INDICATOR_NOT_AT_ALL: BatteryPowerSourceTrait._BatteryReplacementIndicator.ValueType  # 1
        BATTERY_REPLACEMENT_INDICATOR_SOON: BatteryPowerSourceTrait._BatteryReplacementIndicator.ValueType  # 2
        BATTERY_REPLACEMENT_INDICATOR_IMMEDIATELY: BatteryPowerSourceTrait._BatteryReplacementIndicator.ValueType  # 3

    class BatteryReplacementIndicator(_BatteryReplacementIndicator, metaclass=_BatteryReplacementIndicatorEnumTypeWrapper): ...
    BATTERY_REPLACEMENT_INDICATOR_UNSPECIFIED: BatteryPowerSourceTrait.BatteryReplacementIndicator.ValueType  # 0
    BATTERY_REPLACEMENT_INDICATOR_NOT_AT_ALL: BatteryPowerSourceTrait.BatteryReplacementIndicator.ValueType  # 1
    BATTERY_REPLACEMENT_INDICATOR_SOON: BatteryPowerSourceTrait.BatteryReplacementIndicator.ValueType  # 2
    BATTERY_REPLACEMENT_INDICATOR_IMMEDIATELY: BatteryPowerSourceTrait.BatteryReplacementIndicator.ValueType  # 3

    @typing.final
    class BatteryRemaining(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        REMAININGPERCENT_FIELD_NUMBER: builtins.int
        REMAININGTIME_FIELD_NUMBER: builtins.int
        @property
        def remainingPercent(self) -> google.protobuf.wrappers_pb2.FloatValue: ...
        @property
        def remainingTime(self) -> weave.common_pb2.Timer: ...
        def __init__(
            self,
            *,
            remainingPercent: google.protobuf.wrappers_pb2.FloatValue | None = ...,
            remainingTime: weave.common_pb2.Timer | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["remainingPercent", b"remainingPercent", "remainingTime", b"remainingTime"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["remainingPercent", b"remainingPercent", "remainingTime", b"remainingTime"]) -> None: ...

    @typing.final
    class BatteryChangedEvent(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        CONDITION_FIELD_NUMBER: builtins.int
        STATUS_FIELD_NUMBER: builtins.int
        REPLACEMENTINDICATOR_FIELD_NUMBER: builtins.int
        REMAINING_FIELD_NUMBER: builtins.int
        condition: global___PowerSourceTrait.PowerSourceCondition.ValueType
        status: global___PowerSourceTrait.PowerSourceStatus.ValueType
        replacementIndicator: global___BatteryPowerSourceTrait.BatteryReplacementIndicator.ValueType
        @property
        def remaining(self) -> global___BatteryPowerSourceTrait.BatteryRemaining: ...
        def __init__(
            self,
            *,
            condition: global___PowerSourceTrait.PowerSourceCondition.ValueType = ...,
            status: global___PowerSourceTrait.PowerSourceStatus.ValueType = ...,
            replacementIndicator: global___BatteryPowerSourceTrait.BatteryReplacementIndicator.ValueType = ...,
            remaining: global___BatteryPowerSourceTrait.BatteryRemaining | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["remaining", b"remaining"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["condition", b"condition", "remaining", b"remaining", "replacementIndicator", b"replacementIndicator", "status", b"status"]) -> None: ...

    TYPE_FIELD_NUMBER: builtins.int
    ASSESSEDVOLTAGE_FIELD_NUMBER: builtins.int
    ASSESSEDCURRENT_FIELD_NUMBER: builtins.int
    ASSESSEDFREQUENCY_FIELD_NUMBER: builtins.int
    CONDITION_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    PRESENT_FIELD_NUMBER: builtins.int
    REPLACEMENTINDICATOR_FIELD_NUMBER: builtins.int
    REMAINING_FIELD_NUMBER: builtins.int
    type: global___PowerSourceCapabilitiesTrait.PowerSourceType.ValueType
    condition: global___PowerSourceTrait.PowerSourceCondition.ValueType
    status: global___PowerSourceTrait.PowerSourceStatus.ValueType
    present: builtins.bool
    replacementIndicator: global___BatteryPowerSourceTrait.BatteryReplacementIndicator.ValueType
    @property
    def assessedVoltage(self) -> google.protobuf.wrappers_pb2.FloatValue: ...
    @property
    def assessedCurrent(self) -> google.protobuf.wrappers_pb2.FloatValue: ...
    @property
    def assessedFrequency(self) -> google.protobuf.wrappers_pb2.FloatValue: ...
    @property
    def remaining(self) -> global___BatteryPowerSourceTrait.BatteryRemaining: ...
    def __init__(
        self,
        *,
        type: global___PowerSourceCapabilitiesTrait.PowerSourceType.ValueType = ...,
        assessedVoltage: google.protobuf.wrappers_pb2.FloatValue | None = ...,
        assessedCurrent: google.protobuf.wrappers_pb2.FloatValue | None = ...,
        assessedFrequency: google.protobuf.wrappers_pb2.FloatValue | None = ...,
        condition: global___PowerSourceTrait.PowerSourceCondition.ValueType = ...,
        status: global___PowerSourceTrait.PowerSourceStatus.ValueType = ...,
        present: builtins.bool = ...,
        replacementIndicator: global___BatteryPowerSourceTrait.BatteryReplacementIndicator.ValueType = ...,
        remaining: global___BatteryPowerSourceTrait.BatteryRemaining | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["assessedCurrent", b"assessedCurrent", "assessedFrequency", b"assessedFrequency", "assessedVoltage", b"assessedVoltage", "remaining", b"remaining"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["assessedCurrent", b"assessedCurrent", "assessedFrequency", b"assessedFrequency", "assessedVoltage", b"assessedVoltage", "condition", b"condition", "present", b"present", "remaining", b"remaining", "replacementIndicator", b"replacementIndicator", "status", b"status", "type", b"type"]) -> None: ...

global___BatteryPowerSourceTrait = BatteryPowerSourceTrait
