"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.duration_pb2
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.timestamp_pb2
import google.protobuf.wrappers_pb2
import sys
import typing
from ...weave import common_pb2

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class UserPincodesSettingsTrait(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _PincodeErrorCodes:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _PincodeErrorCodesEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[UserPincodesSettingsTrait._PincodeErrorCodes.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        PINCODE_ERROR_CODES_UNSPECIFIED: UserPincodesSettingsTrait._PincodeErrorCodes.ValueType  # 0
        PINCODE_ERROR_CODES_DUPLICATE_PINCODE: UserPincodesSettingsTrait._PincodeErrorCodes.ValueType  # 1
        PINCODE_ERROR_CODES_TOO_MANY_PINCODES: UserPincodesSettingsTrait._PincodeErrorCodes.ValueType  # 2
        PINCODE_ERROR_CODES_INVALID_PINCODE: UserPincodesSettingsTrait._PincodeErrorCodes.ValueType  # 3
        PINCODE_ERROR_CODES_SUCCESS_PINCODE_DELETED: UserPincodesSettingsTrait._PincodeErrorCodes.ValueType  # 4
        PINCODE_ERROR_CODES_SUCCESS_PINCODE_STATUS: UserPincodesSettingsTrait._PincodeErrorCodes.ValueType  # 5
        PINCODE_ERROR_CODES_DUPLICATE_NONCE: UserPincodesSettingsTrait._PincodeErrorCodes.ValueType  # 6
        PINCODE_ERROR_CODES_EXCEEDED_RATE_LIMIT: UserPincodesSettingsTrait._PincodeErrorCodes.ValueType  # 7

    class PincodeErrorCodes(_PincodeErrorCodes, metaclass=_PincodeErrorCodesEnumTypeWrapper): ...
    PINCODE_ERROR_CODES_UNSPECIFIED: UserPincodesSettingsTrait.PincodeErrorCodes.ValueType  # 0
    PINCODE_ERROR_CODES_DUPLICATE_PINCODE: UserPincodesSettingsTrait.PincodeErrorCodes.ValueType  # 1
    PINCODE_ERROR_CODES_TOO_MANY_PINCODES: UserPincodesSettingsTrait.PincodeErrorCodes.ValueType  # 2
    PINCODE_ERROR_CODES_INVALID_PINCODE: UserPincodesSettingsTrait.PincodeErrorCodes.ValueType  # 3
    PINCODE_ERROR_CODES_SUCCESS_PINCODE_DELETED: UserPincodesSettingsTrait.PincodeErrorCodes.ValueType  # 4
    PINCODE_ERROR_CODES_SUCCESS_PINCODE_STATUS: UserPincodesSettingsTrait.PincodeErrorCodes.ValueType  # 5
    PINCODE_ERROR_CODES_DUPLICATE_NONCE: UserPincodesSettingsTrait.PincodeErrorCodes.ValueType  # 6
    PINCODE_ERROR_CODES_EXCEEDED_RATE_LIMIT: UserPincodesSettingsTrait.PincodeErrorCodes.ValueType  # 7

    class _PincodeChangeReason:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _PincodeChangeReasonEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[UserPincodesSettingsTrait._PincodeChangeReason.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        PINCODE_CHANGE_REASON_UNSPECIFIED: UserPincodesSettingsTrait._PincodeChangeReason.ValueType  # 0
        PINCODE_CHANGE_REASON_UPDATE: UserPincodesSettingsTrait._PincodeChangeReason.ValueType  # 1
        PINCODE_CHANGE_REASON_DELETION: UserPincodesSettingsTrait._PincodeChangeReason.ValueType  # 2

    class PincodeChangeReason(_PincodeChangeReason, metaclass=_PincodeChangeReasonEnumTypeWrapper): ...
    PINCODE_CHANGE_REASON_UNSPECIFIED: UserPincodesSettingsTrait.PincodeChangeReason.ValueType  # 0
    PINCODE_CHANGE_REASON_UPDATE: UserPincodesSettingsTrait.PincodeChangeReason.ValueType  # 1
    PINCODE_CHANGE_REASON_DELETION: UserPincodesSettingsTrait.PincodeChangeReason.ValueType  # 2

    @typing.final
    class UserPincodesEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.int
        @property
        def value(self) -> global___UserPincodesSettingsTrait.UserPincode: ...
        def __init__(
            self,
            *,
            key: builtins.int = ...,
            value: global___UserPincodesSettingsTrait.UserPincode | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["value", b"value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    @typing.final
    class UserPincode(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        USERID_FIELD_NUMBER: builtins.int
        PINCODE_FIELD_NUMBER: builtins.int
        PINCODECREDENTIALENABLED_FIELD_NUMBER: builtins.int
        pincode: builtins.bytes
        @property
        def userId(self) -> weave.common_pb2.ResourceId: ...
        @property
        def pincodeCredentialEnabled(self) -> google.protobuf.wrappers_pb2.BoolValue: ...
        def __init__(
            self,
            *,
            userId: weave.common_pb2.ResourceId | None = ...,
            pincode: builtins.bytes = ...,
            pincodeCredentialEnabled: google.protobuf.wrappers_pb2.BoolValue | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["pincodeCredentialEnabled", b"pincodeCredentialEnabled", "userId", b"userId"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["pincode", b"pincode", "pincodeCredentialEnabled", b"pincodeCredentialEnabled", "userId", b"userId"]) -> None: ...

    @typing.final
    class SetUserPincodeRequest(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        USERPINCODE_FIELD_NUMBER: builtins.int
        @property
        def userPincode(self) -> global___UserPincodesSettingsTrait.UserPincode: ...
        def __init__(
            self,
            *,
            userPincode: global___UserPincodesSettingsTrait.UserPincode | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["userPincode", b"userPincode"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["userPincode", b"userPincode"]) -> None: ...

    @typing.final
    class SetUserPincodeResponse(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        STATUS_FIELD_NUMBER: builtins.int
        status: global___UserPincodesSettingsTrait.PincodeErrorCodes.ValueType
        def __init__(
            self,
            *,
            status: global___UserPincodesSettingsTrait.PincodeErrorCodes.ValueType = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["status", b"status"]) -> None: ...

    @typing.final
    class GetUserPincodeRequest(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        USERID_FIELD_NUMBER: builtins.int
        @property
        def userId(self) -> weave.common_pb2.ResourceId: ...
        def __init__(
            self,
            *,
            userId: weave.common_pb2.ResourceId | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["userId", b"userId"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["userId", b"userId"]) -> None: ...

    @typing.final
    class GetUserPincodeResponse(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        USERPINCODE_FIELD_NUMBER: builtins.int
        @property
        def userPincode(self) -> global___UserPincodesSettingsTrait.UserPincode: ...
        def __init__(
            self,
            *,
            userPincode: global___UserPincodesSettingsTrait.UserPincode | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["userPincode", b"userPincode"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["userPincode", b"userPincode"]) -> None: ...

    @typing.final
    class DeleteUserPincodeRequest(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        USERID_FIELD_NUMBER: builtins.int
        @property
        def userId(self) -> weave.common_pb2.ResourceId: ...
        def __init__(
            self,
            *,
            userId: weave.common_pb2.ResourceId | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["userId", b"userId"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["userId", b"userId"]) -> None: ...

    @typing.final
    class DeleteUserPincodeResponse(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        STATUS_FIELD_NUMBER: builtins.int
        status: global___UserPincodesSettingsTrait.PincodeErrorCodes.ValueType
        def __init__(
            self,
            *,
            status: global___UserPincodesSettingsTrait.PincodeErrorCodes.ValueType = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["status", b"status"]) -> None: ...

    @typing.final
    class UserPincodeChangeEvent(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        USERID_FIELD_NUMBER: builtins.int
        REASON_FIELD_NUMBER: builtins.int
        reason: global___UserPincodesSettingsTrait.PincodeChangeReason.ValueType
        @property
        def userId(self) -> weave.common_pb2.ResourceId: ...
        def __init__(
            self,
            *,
            userId: weave.common_pb2.ResourceId | None = ...,
            reason: global___UserPincodesSettingsTrait.PincodeChangeReason.ValueType = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["userId", b"userId"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["reason", b"reason", "userId", b"userId"]) -> None: ...

    USERPINCODES_FIELD_NUMBER: builtins.int
    @property
    def userPincodes(self) -> google.protobuf.internal.containers.MessageMap[builtins.int, global___UserPincodesSettingsTrait.UserPincode]: ...
    def __init__(
        self,
        *,
        userPincodes: collections.abc.Mapping[builtins.int, global___UserPincodesSettingsTrait.UserPincode] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["userPincodes", b"userPincodes"]) -> None: ...

global___UserPincodesSettingsTrait = UserPincodesSettingsTrait

@typing.final
class BoltLockTrait(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _BoltState:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _BoltStateEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[BoltLockTrait._BoltState.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        BOLT_STATE_UNSPECIFIED: BoltLockTrait._BoltState.ValueType  # 0
        BOLT_STATE_RETRACTED: BoltLockTrait._BoltState.ValueType  # 1
        BOLT_STATE_EXTENDED: BoltLockTrait._BoltState.ValueType  # 2

    class BoltState(_BoltState, metaclass=_BoltStateEnumTypeWrapper): ...
    BOLT_STATE_UNSPECIFIED: BoltLockTrait.BoltState.ValueType  # 0
    BOLT_STATE_RETRACTED: BoltLockTrait.BoltState.ValueType  # 1
    BOLT_STATE_EXTENDED: BoltLockTrait.BoltState.ValueType  # 2

    class _BoltLockActorMethod:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _BoltLockActorMethodEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[BoltLockTrait._BoltLockActorMethod.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        BOLT_LOCK_ACTOR_METHOD_UNSPECIFIED: BoltLockTrait._BoltLockActorMethod.ValueType  # 0
        BOLT_LOCK_ACTOR_METHOD_OTHER: BoltLockTrait._BoltLockActorMethod.ValueType  # 1
        BOLT_LOCK_ACTOR_METHOD_PHYSICAL: BoltLockTrait._BoltLockActorMethod.ValueType  # 2
        BOLT_LOCK_ACTOR_METHOD_KEYPAD_PIN: BoltLockTrait._BoltLockActorMethod.ValueType  # 3
        BOLT_LOCK_ACTOR_METHOD_LOCAL_IMPLICIT: BoltLockTrait._BoltLockActorMethod.ValueType  # 4
        BOLT_LOCK_ACTOR_METHOD_REMOTE_USER_EXPLICIT: BoltLockTrait._BoltLockActorMethod.ValueType  # 5
        BOLT_LOCK_ACTOR_METHOD_REMOTE_USER_IMPLICIT: BoltLockTrait._BoltLockActorMethod.ValueType  # 6
        BOLT_LOCK_ACTOR_METHOD_REMOTE_USER_OTHER: BoltLockTrait._BoltLockActorMethod.ValueType  # 7
        BOLT_LOCK_ACTOR_METHOD_REMOTE_DELEGATE: BoltLockTrait._BoltLockActorMethod.ValueType  # 8
        BOLT_LOCK_ACTOR_METHOD_LOW_POWER_SHUTDOWN: BoltLockTrait._BoltLockActorMethod.ValueType  # 9
        BOLT_LOCK_ACTOR_METHOD_VOICE_ASSISTANT: BoltLockTrait._BoltLockActorMethod.ValueType  # 10

    class BoltLockActorMethod(_BoltLockActorMethod, metaclass=_BoltLockActorMethodEnumTypeWrapper): ...
    BOLT_LOCK_ACTOR_METHOD_UNSPECIFIED: BoltLockTrait.BoltLockActorMethod.ValueType  # 0
    BOLT_LOCK_ACTOR_METHOD_OTHER: BoltLockTrait.BoltLockActorMethod.ValueType  # 1
    BOLT_LOCK_ACTOR_METHOD_PHYSICAL: BoltLockTrait.BoltLockActorMethod.ValueType  # 2
    BOLT_LOCK_ACTOR_METHOD_KEYPAD_PIN: BoltLockTrait.BoltLockActorMethod.ValueType  # 3
    BOLT_LOCK_ACTOR_METHOD_LOCAL_IMPLICIT: BoltLockTrait.BoltLockActorMethod.ValueType  # 4
    BOLT_LOCK_ACTOR_METHOD_REMOTE_USER_EXPLICIT: BoltLockTrait.BoltLockActorMethod.ValueType  # 5
    BOLT_LOCK_ACTOR_METHOD_REMOTE_USER_IMPLICIT: BoltLockTrait.BoltLockActorMethod.ValueType  # 6
    BOLT_LOCK_ACTOR_METHOD_REMOTE_USER_OTHER: BoltLockTrait.BoltLockActorMethod.ValueType  # 7
    BOLT_LOCK_ACTOR_METHOD_REMOTE_DELEGATE: BoltLockTrait.BoltLockActorMethod.ValueType  # 8
    BOLT_LOCK_ACTOR_METHOD_LOW_POWER_SHUTDOWN: BoltLockTrait.BoltLockActorMethod.ValueType  # 9
    BOLT_LOCK_ACTOR_METHOD_VOICE_ASSISTANT: BoltLockTrait.BoltLockActorMethod.ValueType  # 10

    class _BoltActuatorState:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _BoltActuatorStateEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[BoltLockTrait._BoltActuatorState.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        BOLT_ACTUATOR_STATE_UNSPECIFIED: BoltLockTrait._BoltActuatorState.ValueType  # 0
        BOLT_ACTUATOR_STATE_OK: BoltLockTrait._BoltActuatorState.ValueType  # 1
        BOLT_ACTUATOR_STATE_LOCKING: BoltLockTrait._BoltActuatorState.ValueType  # 2
        BOLT_ACTUATOR_STATE_UNLOCKING: BoltLockTrait._BoltActuatorState.ValueType  # 3
        BOLT_ACTUATOR_STATE_MOVING: BoltLockTrait._BoltActuatorState.ValueType  # 4
        BOLT_ACTUATOR_STATE_JAMMED_LOCKING: BoltLockTrait._BoltActuatorState.ValueType  # 5
        BOLT_ACTUATOR_STATE_JAMMED_UNLOCKING: BoltLockTrait._BoltActuatorState.ValueType  # 6
        BOLT_ACTUATOR_STATE_JAMMED_OTHER: BoltLockTrait._BoltActuatorState.ValueType  # 7

    class BoltActuatorState(_BoltActuatorState, metaclass=_BoltActuatorStateEnumTypeWrapper): ...
    BOLT_ACTUATOR_STATE_UNSPECIFIED: BoltLockTrait.BoltActuatorState.ValueType  # 0
    BOLT_ACTUATOR_STATE_OK: BoltLockTrait.BoltActuatorState.ValueType  # 1
    BOLT_ACTUATOR_STATE_LOCKING: BoltLockTrait.BoltActuatorState.ValueType  # 2
    BOLT_ACTUATOR_STATE_UNLOCKING: BoltLockTrait.BoltActuatorState.ValueType  # 3
    BOLT_ACTUATOR_STATE_MOVING: BoltLockTrait.BoltActuatorState.ValueType  # 4
    BOLT_ACTUATOR_STATE_JAMMED_LOCKING: BoltLockTrait.BoltActuatorState.ValueType  # 5
    BOLT_ACTUATOR_STATE_JAMMED_UNLOCKING: BoltLockTrait.BoltActuatorState.ValueType  # 6
    BOLT_ACTUATOR_STATE_JAMMED_OTHER: BoltLockTrait.BoltActuatorState.ValueType  # 7

    class _BoltLockedState:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _BoltLockedStateEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[BoltLockTrait._BoltLockedState.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        BOLT_LOCKED_STATE_UNSPECIFIED: BoltLockTrait._BoltLockedState.ValueType  # 0
        BOLT_LOCKED_STATE_UNLOCKED: BoltLockTrait._BoltLockedState.ValueType  # 1
        BOLT_LOCKED_STATE_LOCKED: BoltLockTrait._BoltLockedState.ValueType  # 2
        BOLT_LOCKED_STATE_UNKNOWN: BoltLockTrait._BoltLockedState.ValueType  # 3

    class BoltLockedState(_BoltLockedState, metaclass=_BoltLockedStateEnumTypeWrapper): ...
    BOLT_LOCKED_STATE_UNSPECIFIED: BoltLockTrait.BoltLockedState.ValueType  # 0
    BOLT_LOCKED_STATE_UNLOCKED: BoltLockTrait.BoltLockedState.ValueType  # 1
    BOLT_LOCKED_STATE_LOCKED: BoltLockTrait.BoltLockedState.ValueType  # 2
    BOLT_LOCKED_STATE_UNKNOWN: BoltLockTrait.BoltLockedState.ValueType  # 3

    @typing.final
    class BoltLockActorStruct(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        METHOD_FIELD_NUMBER: builtins.int
        ORIGINATOR_FIELD_NUMBER: builtins.int
        AGENT_FIELD_NUMBER: builtins.int
        method: global___BoltLockTrait.BoltLockActorMethod.ValueType
        @property
        def originator(self) -> weave.common_pb2.ResourceId: ...
        @property
        def agent(self) -> weave.common_pb2.ResourceId: ...
        def __init__(
            self,
            *,
            method: global___BoltLockTrait.BoltLockActorMethod.ValueType = ...,
            originator: weave.common_pb2.ResourceId | None = ...,
            agent: weave.common_pb2.ResourceId | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["agent", b"agent", "originator", b"originator"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["agent", b"agent", "method", b"method", "originator", b"originator"]) -> None: ...

    @typing.final
    class BoltLockChangeRequest(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        STATE_FIELD_NUMBER: builtins.int
        BOLTLOCKACTOR_FIELD_NUMBER: builtins.int
        state: global___BoltLockTrait.BoltState.ValueType
        @property
        def boltLockActor(self) -> global___BoltLockTrait.BoltLockActorStruct: ...
        def __init__(
            self,
            *,
            state: global___BoltLockTrait.BoltState.ValueType = ...,
            boltLockActor: global___BoltLockTrait.BoltLockActorStruct | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["boltLockActor", b"boltLockActor"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["boltLockActor", b"boltLockActor", "state", b"state"]) -> None: ...

    @typing.final
    class BoltLockProximityChangeRequest(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        STATE_FIELD_NUMBER: builtins.int
        BOLTLOCKACTOR_FIELD_NUMBER: builtins.int
        TOKEN_FIELD_NUMBER: builtins.int
        state: global___BoltLockTrait.BoltState.ValueType
        token: builtins.bytes
        @property
        def boltLockActor(self) -> global___BoltLockTrait.BoltLockActorStruct: ...
        def __init__(
            self,
            *,
            state: global___BoltLockTrait.BoltState.ValueType = ...,
            boltLockActor: global___BoltLockTrait.BoltLockActorStruct | None = ...,
            token: builtins.bytes = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["boltLockActor", b"boltLockActor"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["boltLockActor", b"boltLockActor", "state", b"state", "token", b"token"]) -> None: ...

    @typing.final
    class BoltActuatorStateChangeEvent(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        STATE_FIELD_NUMBER: builtins.int
        ACTUATORSTATE_FIELD_NUMBER: builtins.int
        LOCKEDSTATE_FIELD_NUMBER: builtins.int
        BOLTLOCKACTOR_FIELD_NUMBER: builtins.int
        state: global___BoltLockTrait.BoltState.ValueType
        actuatorState: global___BoltLockTrait.BoltActuatorState.ValueType
        lockedState: global___BoltLockTrait.BoltLockedState.ValueType
        @property
        def boltLockActor(self) -> global___BoltLockTrait.BoltLockActorStruct: ...
        def __init__(
            self,
            *,
            state: global___BoltLockTrait.BoltState.ValueType = ...,
            actuatorState: global___BoltLockTrait.BoltActuatorState.ValueType = ...,
            lockedState: global___BoltLockTrait.BoltLockedState.ValueType = ...,
            boltLockActor: global___BoltLockTrait.BoltLockActorStruct | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["boltLockActor", b"boltLockActor"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["actuatorState", b"actuatorState", "boltLockActor", b"boltLockActor", "lockedState", b"lockedState", "state", b"state"]) -> None: ...

    STATE_FIELD_NUMBER: builtins.int
    ACTUATORSTATE_FIELD_NUMBER: builtins.int
    LOCKEDSTATE_FIELD_NUMBER: builtins.int
    BOLTLOCKACTOR_FIELD_NUMBER: builtins.int
    LOCKEDSTATELASTCHANGEDAT_FIELD_NUMBER: builtins.int
    state: global___BoltLockTrait.BoltState.ValueType
    actuatorState: global___BoltLockTrait.BoltActuatorState.ValueType
    lockedState: global___BoltLockTrait.BoltLockedState.ValueType
    @property
    def boltLockActor(self) -> global___BoltLockTrait.BoltLockActorStruct: ...
    @property
    def lockedStateLastChangedAt(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        state: global___BoltLockTrait.BoltState.ValueType = ...,
        actuatorState: global___BoltLockTrait.BoltActuatorState.ValueType = ...,
        lockedState: global___BoltLockTrait.BoltLockedState.ValueType = ...,
        boltLockActor: global___BoltLockTrait.BoltLockActorStruct | None = ...,
        lockedStateLastChangedAt: google.protobuf.timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["boltLockActor", b"boltLockActor", "lockedStateLastChangedAt", b"lockedStateLastChangedAt"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["actuatorState", b"actuatorState", "boltLockActor", b"boltLockActor", "lockedState", b"lockedState", "lockedStateLastChangedAt", b"lockedStateLastChangedAt", "state", b"state"]) -> None: ...

global___BoltLockTrait = BoltLockTrait

@typing.final
class SensorAssociationTrait(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _StatusCode:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _StatusCodeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[SensorAssociationTrait._StatusCode.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        STATUS_CODE_UNSPECIFIED: SensorAssociationTrait._StatusCode.ValueType  # 0
        STATUS_CODE_SUCCESS: SensorAssociationTrait._StatusCode.ValueType  # 1
        STATUS_CODE_FAILURE: SensorAssociationTrait._StatusCode.ValueType  # 2
        STATUS_CODE_SENSOR_ALREADY_ASSOCIATED_OTHER: SensorAssociationTrait._StatusCode.ValueType  # 3
        STATUS_CODE_SENSOR_ALREADY_ASSOCIATED_SELF: SensorAssociationTrait._StatusCode.ValueType  # 4
        STATUS_CODE_SENSOR_INVALID: SensorAssociationTrait._StatusCode.ValueType  # 5
        STATUS_CODE_USER_SETTING_INVALID: SensorAssociationTrait._StatusCode.ValueType  # 6

    class StatusCode(_StatusCode, metaclass=_StatusCodeEnumTypeWrapper): ...
    STATUS_CODE_UNSPECIFIED: SensorAssociationTrait.StatusCode.ValueType  # 0
    STATUS_CODE_SUCCESS: SensorAssociationTrait.StatusCode.ValueType  # 1
    STATUS_CODE_FAILURE: SensorAssociationTrait.StatusCode.ValueType  # 2
    STATUS_CODE_SENSOR_ALREADY_ASSOCIATED_OTHER: SensorAssociationTrait.StatusCode.ValueType  # 3
    STATUS_CODE_SENSOR_ALREADY_ASSOCIATED_SELF: SensorAssociationTrait.StatusCode.ValueType  # 4
    STATUS_CODE_SENSOR_INVALID: SensorAssociationTrait.StatusCode.ValueType  # 5
    STATUS_CODE_USER_SETTING_INVALID: SensorAssociationTrait.StatusCode.ValueType  # 6

    class _SensorAssociationStatus:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _SensorAssociationStatusEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[SensorAssociationTrait._SensorAssociationStatus.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        SENSOR_ASSOCIATION_STATUS_UNSPECIFIED: SensorAssociationTrait._SensorAssociationStatus.ValueType  # 0
        SENSOR_ASSOCIATION_STATUS_ASSOCIATED_SELF: SensorAssociationTrait._SensorAssociationStatus.ValueType  # 1
        SENSOR_ASSOCIATION_STATUS_ASSOCIATED_OTHER: SensorAssociationTrait._SensorAssociationStatus.ValueType  # 2
        SENSOR_ASSOCIATION_STATUS_DEFAULT: SensorAssociationTrait._SensorAssociationStatus.ValueType  # 3
        SENSOR_ASSOCIATION_STATUS_ELIGIBLE: SensorAssociationTrait._SensorAssociationStatus.ValueType  # 4
        SENSOR_ASSOCIATION_STATUS_INELIGIBLE: SensorAssociationTrait._SensorAssociationStatus.ValueType  # 5

    class SensorAssociationStatus(_SensorAssociationStatus, metaclass=_SensorAssociationStatusEnumTypeWrapper): ...
    SENSOR_ASSOCIATION_STATUS_UNSPECIFIED: SensorAssociationTrait.SensorAssociationStatus.ValueType  # 0
    SENSOR_ASSOCIATION_STATUS_ASSOCIATED_SELF: SensorAssociationTrait.SensorAssociationStatus.ValueType  # 1
    SENSOR_ASSOCIATION_STATUS_ASSOCIATED_OTHER: SensorAssociationTrait.SensorAssociationStatus.ValueType  # 2
    SENSOR_ASSOCIATION_STATUS_DEFAULT: SensorAssociationTrait.SensorAssociationStatus.ValueType  # 3
    SENSOR_ASSOCIATION_STATUS_ELIGIBLE: SensorAssociationTrait.SensorAssociationStatus.ValueType  # 4
    SENSOR_ASSOCIATION_STATUS_INELIGIBLE: SensorAssociationTrait.SensorAssociationStatus.ValueType  # 5

    @typing.final
    class SetUserSensorAssociationRequest(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        SENSORDEVICEID_FIELD_NUMBER: builtins.int
        @property
        def sensorDeviceId(self) -> weave.common_pb2.ResourceId: ...
        def __init__(
            self,
            *,
            sensorDeviceId: weave.common_pb2.ResourceId | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["sensorDeviceId", b"sensorDeviceId"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["sensorDeviceId", b"sensorDeviceId"]) -> None: ...

    @typing.final
    class SetUserSensorAssociationResponse(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        STATUS_FIELD_NUMBER: builtins.int
        status: global___SensorAssociationTrait.StatusCode.ValueType
        def __init__(
            self,
            *,
            status: global___SensorAssociationTrait.StatusCode.ValueType = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["status", b"status"]) -> None: ...

    @typing.final
    class SensorDeviceStatus(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        DEVICEID_FIELD_NUMBER: builtins.int
        SENSORASSOCIATIONSTATUS_FIELD_NUMBER: builtins.int
        SENSORASSOCIATIONSTATUSLIST_FIELD_NUMBER: builtins.int
        sensorAssociationStatus: global___SensorAssociationTrait.SensorAssociationStatus.ValueType
        @property
        def deviceId(self) -> weave.common_pb2.ResourceId: ...
        @property
        def sensorAssociationStatusList(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[global___SensorAssociationTrait.SensorAssociationStatus.ValueType]: ...
        def __init__(
            self,
            *,
            deviceId: weave.common_pb2.ResourceId | None = ...,
            sensorAssociationStatus: global___SensorAssociationTrait.SensorAssociationStatus.ValueType = ...,
            sensorAssociationStatusList: collections.abc.Iterable[global___SensorAssociationTrait.SensorAssociationStatus.ValueType] | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["deviceId", b"deviceId"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["deviceId", b"deviceId", "sensorAssociationStatus", b"sensorAssociationStatus", "sensorAssociationStatusList", b"sensorAssociationStatusList"]) -> None: ...

    SENSORS_FIELD_NUMBER: builtins.int
    ASSOCIATEDSENSORDEVICEID_FIELD_NUMBER: builtins.int
    @property
    def sensors(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___SensorAssociationTrait.SensorDeviceStatus]: ...
    @property
    def associatedSensorDeviceId(self) -> weave.common_pb2.ResourceId: ...
    def __init__(
        self,
        *,
        sensors: collections.abc.Iterable[global___SensorAssociationTrait.SensorDeviceStatus] | None = ...,
        associatedSensorDeviceId: weave.common_pb2.ResourceId | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["associatedSensorDeviceId", b"associatedSensorDeviceId"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["associatedSensorDeviceId", b"associatedSensorDeviceId", "sensors", b"sensors"]) -> None: ...

global___SensorAssociationTrait = SensorAssociationTrait

@typing.final
class UserNFCTokenManagementTrait(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _NFCTokenEvent:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _NFCTokenEventEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[UserNFCTokenManagementTrait._NFCTokenEvent.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        NFC_TOKEN_EVENT_UNSPECIFIED: UserNFCTokenManagementTrait._NFCTokenEvent.ValueType  # 0
        NFC_TOKEN_EVENT_PAIRED: UserNFCTokenManagementTrait._NFCTokenEvent.ValueType  # 1
        NFC_TOKEN_EVENT_UNPAIRED: UserNFCTokenManagementTrait._NFCTokenEvent.ValueType  # 2
        NFC_TOKEN_EVENT_STRUCTURE_AUTH: UserNFCTokenManagementTrait._NFCTokenEvent.ValueType  # 3
        NFC_TOKEN_EVENT_STRUCTURE_UNAUTH: UserNFCTokenManagementTrait._NFCTokenEvent.ValueType  # 4
        NFC_TOKEN_EVENT_TRANSFERRED: UserNFCTokenManagementTrait._NFCTokenEvent.ValueType  # 5
        NFC_TOKEN_EVENT_DISABLED: UserNFCTokenManagementTrait._NFCTokenEvent.ValueType  # 6
        NFC_TOKEN_EVENT_ENABLED: UserNFCTokenManagementTrait._NFCTokenEvent.ValueType  # 7

    class NFCTokenEvent(_NFCTokenEvent, metaclass=_NFCTokenEventEnumTypeWrapper): ...
    NFC_TOKEN_EVENT_UNSPECIFIED: UserNFCTokenManagementTrait.NFCTokenEvent.ValueType  # 0
    NFC_TOKEN_EVENT_PAIRED: UserNFCTokenManagementTrait.NFCTokenEvent.ValueType  # 1
    NFC_TOKEN_EVENT_UNPAIRED: UserNFCTokenManagementTrait.NFCTokenEvent.ValueType  # 2
    NFC_TOKEN_EVENT_STRUCTURE_AUTH: UserNFCTokenManagementTrait.NFCTokenEvent.ValueType  # 3
    NFC_TOKEN_EVENT_STRUCTURE_UNAUTH: UserNFCTokenManagementTrait.NFCTokenEvent.ValueType  # 4
    NFC_TOKEN_EVENT_TRANSFERRED: UserNFCTokenManagementTrait.NFCTokenEvent.ValueType  # 5
    NFC_TOKEN_EVENT_DISABLED: UserNFCTokenManagementTrait.NFCTokenEvent.ValueType  # 6
    NFC_TOKEN_EVENT_ENABLED: UserNFCTokenManagementTrait.NFCTokenEvent.ValueType  # 7

    @typing.final
    class TransferUserNFCTokenRequest(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        TARGETUSERID_FIELD_NUMBER: builtins.int
        TOKENDEVICEID_FIELD_NUMBER: builtins.int
        @property
        def targetUserId(self) -> weave.common_pb2.ResourceId: ...
        @property
        def tokenDeviceId(self) -> weave.common_pb2.ResourceId: ...
        def __init__(
            self,
            *,
            targetUserId: weave.common_pb2.ResourceId | None = ...,
            tokenDeviceId: weave.common_pb2.ResourceId | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["targetUserId", b"targetUserId", "tokenDeviceId", b"tokenDeviceId"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["targetUserId", b"targetUserId", "tokenDeviceId", b"tokenDeviceId"]) -> None: ...

    @typing.final
    class SetUserNFCTokenEnableStateRequest(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        TOKENDEVICEID_FIELD_NUMBER: builtins.int
        ENABLED_FIELD_NUMBER: builtins.int
        enabled: builtins.bool
        @property
        def tokenDeviceId(self) -> weave.common_pb2.ResourceId: ...
        def __init__(
            self,
            *,
            tokenDeviceId: weave.common_pb2.ResourceId | None = ...,
            enabled: builtins.bool = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["tokenDeviceId", b"tokenDeviceId"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["enabled", b"enabled", "tokenDeviceId", b"tokenDeviceId"]) -> None: ...

    @typing.final
    class AuthUserNFCTokenToStructureRequest(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        TOKENDEVICEID_FIELD_NUMBER: builtins.int
        AUTHORIZED_FIELD_NUMBER: builtins.int
        STRUCTUREID_FIELD_NUMBER: builtins.int
        authorized: builtins.bool
        @property
        def tokenDeviceId(self) -> weave.common_pb2.ResourceId: ...
        @property
        def structureId(self) -> weave.common_pb2.ResourceId: ...
        def __init__(
            self,
            *,
            tokenDeviceId: weave.common_pb2.ResourceId | None = ...,
            authorized: builtins.bool = ...,
            structureId: weave.common_pb2.ResourceId | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["structureId", b"structureId", "tokenDeviceId", b"tokenDeviceId"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["authorized", b"authorized", "structureId", b"structureId", "tokenDeviceId", b"tokenDeviceId"]) -> None: ...

    @typing.final
    class UserNFCTokenManagementEvent(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        NFCTOKENMANAGEMENTEVENT_FIELD_NUMBER: builtins.int
        USERNFCTOKEN_FIELD_NUMBER: builtins.int
        INITIATINGUSERID_FIELD_NUMBER: builtins.int
        PREVIOUSUSERID_FIELD_NUMBER: builtins.int
        nfcTokenManagementEvent: global___UserNFCTokenManagementTrait.NFCTokenEvent.ValueType
        @property
        def userNfcToken(self) -> global___UserNFCTokensTrait.UserNFCTokenData: ...
        @property
        def initiatingUserId(self) -> weave.common_pb2.ResourceId: ...
        @property
        def previousUserId(self) -> weave.common_pb2.ResourceId: ...
        def __init__(
            self,
            *,
            nfcTokenManagementEvent: global___UserNFCTokenManagementTrait.NFCTokenEvent.ValueType = ...,
            userNfcToken: global___UserNFCTokensTrait.UserNFCTokenData | None = ...,
            initiatingUserId: weave.common_pb2.ResourceId | None = ...,
            previousUserId: weave.common_pb2.ResourceId | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["initiatingUserId", b"initiatingUserId", "previousUserId", b"previousUserId", "userNfcToken", b"userNfcToken"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["initiatingUserId", b"initiatingUserId", "nfcTokenManagementEvent", b"nfcTokenManagementEvent", "previousUserId", b"previousUserId", "userNfcToken", b"userNfcToken"]) -> None: ...

    def __init__(
        self,
    ) -> None: ...

global___UserNFCTokenManagementTrait = UserNFCTokenManagementTrait

@typing.final
class PincodeInputTrait(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _PincodeEntryResult:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _PincodeEntryResultEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[PincodeInputTrait._PincodeEntryResult.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        PINCODE_ENTRY_RESULT_UNSPECIFIED: PincodeInputTrait._PincodeEntryResult.ValueType  # 0
        PINCODE_ENTRY_RESULT_FAILURE_INVALID_PINCODE: PincodeInputTrait._PincodeEntryResult.ValueType  # 1
        PINCODE_ENTRY_RESULT_FAILURE_OUT_OF_SCHEDULE: PincodeInputTrait._PincodeEntryResult.ValueType  # 2
        PINCODE_ENTRY_RESULT_FAILURE_PINCODE_DISABLED: PincodeInputTrait._PincodeEntryResult.ValueType  # 3
        PINCODE_ENTRY_RESULT_SUCCESS: PincodeInputTrait._PincodeEntryResult.ValueType  # 4

    class PincodeEntryResult(_PincodeEntryResult, metaclass=_PincodeEntryResultEnumTypeWrapper): ...
    PINCODE_ENTRY_RESULT_UNSPECIFIED: PincodeInputTrait.PincodeEntryResult.ValueType  # 0
    PINCODE_ENTRY_RESULT_FAILURE_INVALID_PINCODE: PincodeInputTrait.PincodeEntryResult.ValueType  # 1
    PINCODE_ENTRY_RESULT_FAILURE_OUT_OF_SCHEDULE: PincodeInputTrait.PincodeEntryResult.ValueType  # 2
    PINCODE_ENTRY_RESULT_FAILURE_PINCODE_DISABLED: PincodeInputTrait.PincodeEntryResult.ValueType  # 3
    PINCODE_ENTRY_RESULT_SUCCESS: PincodeInputTrait.PincodeEntryResult.ValueType  # 4

    class _PincodeInputState:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _PincodeInputStateEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[PincodeInputTrait._PincodeInputState.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        PINCODE_INPUT_STATE_UNSPECIFIED: PincodeInputTrait._PincodeInputState.ValueType  # 0
        PINCODE_INPUT_STATE_ENABLED: PincodeInputTrait._PincodeInputState.ValueType  # 1
        PINCODE_INPUT_STATE_DISABLED: PincodeInputTrait._PincodeInputState.ValueType  # 2

    class PincodeInputState(_PincodeInputState, metaclass=_PincodeInputStateEnumTypeWrapper): ...
    PINCODE_INPUT_STATE_UNSPECIFIED: PincodeInputTrait.PincodeInputState.ValueType  # 0
    PINCODE_INPUT_STATE_ENABLED: PincodeInputTrait.PincodeInputState.ValueType  # 1
    PINCODE_INPUT_STATE_DISABLED: PincodeInputTrait.PincodeInputState.ValueType  # 2

    @typing.final
    class KeypadEntryEvent(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        PINCODECREDENTIALENABLED_FIELD_NUMBER: builtins.int
        USERID_FIELD_NUMBER: builtins.int
        INVALIDENTRYCOUNT_FIELD_NUMBER: builtins.int
        PINCODEENTRYRESULT_FIELD_NUMBER: builtins.int
        invalidEntryCount: builtins.int
        pincodeEntryResult: global___PincodeInputTrait.PincodeEntryResult.ValueType
        @property
        def pincodeCredentialEnabled(self) -> google.protobuf.wrappers_pb2.BoolValue: ...
        @property
        def userId(self) -> weave.common_pb2.ResourceId: ...
        def __init__(
            self,
            *,
            pincodeCredentialEnabled: google.protobuf.wrappers_pb2.BoolValue | None = ...,
            userId: weave.common_pb2.ResourceId | None = ...,
            invalidEntryCount: builtins.int = ...,
            pincodeEntryResult: global___PincodeInputTrait.PincodeEntryResult.ValueType = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["pincodeCredentialEnabled", b"pincodeCredentialEnabled", "userId", b"userId"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["invalidEntryCount", b"invalidEntryCount", "pincodeCredentialEnabled", b"pincodeCredentialEnabled", "pincodeEntryResult", b"pincodeEntryResult", "userId", b"userId"]) -> None: ...

    @typing.final
    class PincodeInputStateChangeEvent(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        PINCODEINPUTSTATE_FIELD_NUMBER: builtins.int
        USERID_FIELD_NUMBER: builtins.int
        pincodeInputState: global___PincodeInputTrait.PincodeInputState.ValueType
        @property
        def userId(self) -> weave.common_pb2.ResourceId: ...
        def __init__(
            self,
            *,
            pincodeInputState: global___PincodeInputTrait.PincodeInputState.ValueType = ...,
            userId: weave.common_pb2.ResourceId | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["userId", b"userId"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["pincodeInputState", b"pincodeInputState", "userId", b"userId"]) -> None: ...

    PINCODEINPUTSTATE_FIELD_NUMBER: builtins.int
    pincodeInputState: global___PincodeInputTrait.PincodeInputState.ValueType
    def __init__(
        self,
        *,
        pincodeInputState: global___PincodeInputTrait.PincodeInputState.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["pincodeInputState", b"pincodeInputState"]) -> None: ...

global___PincodeInputTrait = PincodeInputTrait

@typing.final
class TamperTrait(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _TamperState:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _TamperStateEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[TamperTrait._TamperState.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        TAMPER_STATE_UNSPECIFIED: TamperTrait._TamperState.ValueType  # 0
        TAMPER_STATE_CLEAR: TamperTrait._TamperState.ValueType  # 1
        TAMPER_STATE_TAMPERED: TamperTrait._TamperState.ValueType  # 2
        TAMPER_STATE_UNKNOWN: TamperTrait._TamperState.ValueType  # 3

    class TamperState(_TamperState, metaclass=_TamperStateEnumTypeWrapper): ...
    TAMPER_STATE_UNSPECIFIED: TamperTrait.TamperState.ValueType  # 0
    TAMPER_STATE_CLEAR: TamperTrait.TamperState.ValueType  # 1
    TAMPER_STATE_TAMPERED: TamperTrait.TamperState.ValueType  # 2
    TAMPER_STATE_UNKNOWN: TamperTrait.TamperState.ValueType  # 3

    class _TamperStateChangeReason:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _TamperStateChangeReasonEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[TamperTrait._TamperStateChangeReason.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        TAMPER_STATE_CHANGE_REASON_UNSPECIFIED: TamperTrait._TamperStateChangeReason.ValueType  # 0
        TAMPER_STATE_CHANGE_REASON_CLEAR_SECURE: TamperTrait._TamperStateChangeReason.ValueType  # 1
        TAMPER_STATE_CHANGE_REASON_CLEAR_DISARM: TamperTrait._TamperStateChangeReason.ValueType  # 2
        TAMPER_STATE_CHANGE_REASON_CLEAR_SNOOZE: TamperTrait._TamperStateChangeReason.ValueType  # 3

    class TamperStateChangeReason(_TamperStateChangeReason, metaclass=_TamperStateChangeReasonEnumTypeWrapper): ...
    TAMPER_STATE_CHANGE_REASON_UNSPECIFIED: TamperTrait.TamperStateChangeReason.ValueType  # 0
    TAMPER_STATE_CHANGE_REASON_CLEAR_SECURE: TamperTrait.TamperStateChangeReason.ValueType  # 1
    TAMPER_STATE_CHANGE_REASON_CLEAR_DISARM: TamperTrait.TamperStateChangeReason.ValueType  # 2
    TAMPER_STATE_CHANGE_REASON_CLEAR_SNOOZE: TamperTrait.TamperStateChangeReason.ValueType  # 3

    @typing.final
    class ResetTamperRequest(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        def __init__(
            self,
        ) -> None: ...

    @typing.final
    class TamperStateChangeEvent(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        TAMPERSTATE_FIELD_NUMBER: builtins.int
        PRIORTAMPERSTATE_FIELD_NUMBER: builtins.int
        REASON_FIELD_NUMBER: builtins.int
        TAMPERSTATECHANGETIME_FIELD_NUMBER: builtins.int
        tamperState: global___TamperTrait.TamperState.ValueType
        priorTamperState: global___TamperTrait.TamperState.ValueType
        reason: global___TamperTrait.TamperStateChangeReason.ValueType
        @property
        def tamperStateChangeTime(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
        def __init__(
            self,
            *,
            tamperState: global___TamperTrait.TamperState.ValueType = ...,
            priorTamperState: global___TamperTrait.TamperState.ValueType = ...,
            reason: global___TamperTrait.TamperStateChangeReason.ValueType = ...,
            tamperStateChangeTime: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["tamperStateChangeTime", b"tamperStateChangeTime"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["priorTamperState", b"priorTamperState", "reason", b"reason", "tamperState", b"tamperState", "tamperStateChangeTime", b"tamperStateChangeTime"]) -> None: ...

    TAMPERSTATE_FIELD_NUMBER: builtins.int
    FIRSTOBSERVEDAT_FIELD_NUMBER: builtins.int
    FIRSTOBSERVEDATMS_FIELD_NUMBER: builtins.int
    tamperState: global___TamperTrait.TamperState.ValueType
    @property
    def firstObservedAt(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def firstObservedAtMs(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        tamperState: global___TamperTrait.TamperState.ValueType = ...,
        firstObservedAt: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        firstObservedAtMs: google.protobuf.timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["firstObservedAt", b"firstObservedAt", "firstObservedAtMs", b"firstObservedAtMs"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["firstObservedAt", b"firstObservedAt", "firstObservedAtMs", b"firstObservedAtMs", "tamperState", b"tamperState"]) -> None: ...

global___TamperTrait = TamperTrait

@typing.final
class UserNFCTokenAccessTrait(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _UserNFCTokenAccessResult:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _UserNFCTokenAccessResultEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[UserNFCTokenAccessTrait._UserNFCTokenAccessResult.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        USER_NFC_TOKEN_ACCESS_RESULT_UNSPECIFIED: UserNFCTokenAccessTrait._UserNFCTokenAccessResult.ValueType  # 0
        USER_NFC_TOKEN_ACCESS_RESULT_SUCCESS: UserNFCTokenAccessTrait._UserNFCTokenAccessResult.ValueType  # 1
        USER_NFC_TOKEN_ACCESS_RESULT_FAILURE_UNKNOWN_TOKEN: UserNFCTokenAccessTrait._UserNFCTokenAccessResult.ValueType  # 2
        USER_NFC_TOKEN_ACCESS_RESULT_FAILURE_INVALID_TOKEN: UserNFCTokenAccessTrait._UserNFCTokenAccessResult.ValueType  # 3
        USER_NFC_TOKEN_ACCESS_RESULT_FAILURE_OUT_OF_SCHEDULE: UserNFCTokenAccessTrait._UserNFCTokenAccessResult.ValueType  # 4
        USER_NFC_TOKEN_ACCESS_RESULT_FAILURE_TOKEN_DISABLED: UserNFCTokenAccessTrait._UserNFCTokenAccessResult.ValueType  # 5
        USER_NFC_TOKEN_ACCESS_RESULT_FAILURE_INVALID_VERSION: UserNFCTokenAccessTrait._UserNFCTokenAccessResult.ValueType  # 6
        USER_NFC_TOKEN_ACCESS_RESULT_FAILURE_OTHER_REASON: UserNFCTokenAccessTrait._UserNFCTokenAccessResult.ValueType  # 7

    class UserNFCTokenAccessResult(_UserNFCTokenAccessResult, metaclass=_UserNFCTokenAccessResultEnumTypeWrapper): ...
    USER_NFC_TOKEN_ACCESS_RESULT_UNSPECIFIED: UserNFCTokenAccessTrait.UserNFCTokenAccessResult.ValueType  # 0
    USER_NFC_TOKEN_ACCESS_RESULT_SUCCESS: UserNFCTokenAccessTrait.UserNFCTokenAccessResult.ValueType  # 1
    USER_NFC_TOKEN_ACCESS_RESULT_FAILURE_UNKNOWN_TOKEN: UserNFCTokenAccessTrait.UserNFCTokenAccessResult.ValueType  # 2
    USER_NFC_TOKEN_ACCESS_RESULT_FAILURE_INVALID_TOKEN: UserNFCTokenAccessTrait.UserNFCTokenAccessResult.ValueType  # 3
    USER_NFC_TOKEN_ACCESS_RESULT_FAILURE_OUT_OF_SCHEDULE: UserNFCTokenAccessTrait.UserNFCTokenAccessResult.ValueType  # 4
    USER_NFC_TOKEN_ACCESS_RESULT_FAILURE_TOKEN_DISABLED: UserNFCTokenAccessTrait.UserNFCTokenAccessResult.ValueType  # 5
    USER_NFC_TOKEN_ACCESS_RESULT_FAILURE_INVALID_VERSION: UserNFCTokenAccessTrait.UserNFCTokenAccessResult.ValueType  # 6
    USER_NFC_TOKEN_ACCESS_RESULT_FAILURE_OTHER_REASON: UserNFCTokenAccessTrait.UserNFCTokenAccessResult.ValueType  # 7

    @typing.final
    class UserNFCTokenAccessEvent(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        RESULT_FIELD_NUMBER: builtins.int
        TOKENID_FIELD_NUMBER: builtins.int
        USERID_FIELD_NUMBER: builtins.int
        result: global___UserNFCTokenAccessTrait.UserNFCTokenAccessResult.ValueType
        @property
        def tokenId(self) -> weave.common_pb2.ResourceId: ...
        @property
        def userId(self) -> weave.common_pb2.ResourceId: ...
        def __init__(
            self,
            *,
            result: global___UserNFCTokenAccessTrait.UserNFCTokenAccessResult.ValueType = ...,
            tokenId: weave.common_pb2.ResourceId | None = ...,
            userId: weave.common_pb2.ResourceId | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["tokenId", b"tokenId", "userId", b"userId"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["result", b"result", "tokenId", b"tokenId", "userId", b"userId"]) -> None: ...

    def __init__(
        self,
    ) -> None: ...

global___UserNFCTokenAccessTrait = UserNFCTokenAccessTrait

@typing.final
class UserNFCTokensTrait(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class UserNFCTokenData(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        USERID_FIELD_NUMBER: builtins.int
        TOKENDEVICEID_FIELD_NUMBER: builtins.int
        ENABLED_FIELD_NUMBER: builtins.int
        STRUCTUREIDS_FIELD_NUMBER: builtins.int
        LABEL_FIELD_NUMBER: builtins.int
        METADATA_FIELD_NUMBER: builtins.int
        enabled: builtins.bool
        label: builtins.str
        @property
        def userId(self) -> weave.common_pb2.ResourceId: ...
        @property
        def tokenDeviceId(self) -> weave.common_pb2.ResourceId: ...
        @property
        def structureIds(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[weave.common_pb2.ResourceId]: ...
        @property
        def metadata(self) -> global___UserNFCTokenMetadataTrait.Metadata: ...
        def __init__(
            self,
            *,
            userId: weave.common_pb2.ResourceId | None = ...,
            tokenDeviceId: weave.common_pb2.ResourceId | None = ...,
            enabled: builtins.bool = ...,
            structureIds: collections.abc.Iterable[weave.common_pb2.ResourceId] | None = ...,
            label: builtins.str = ...,
            metadata: global___UserNFCTokenMetadataTrait.Metadata | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["metadata", b"metadata", "tokenDeviceId", b"tokenDeviceId", "userId", b"userId"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["enabled", b"enabled", "label", b"label", "metadata", b"metadata", "structureIds", b"structureIds", "tokenDeviceId", b"tokenDeviceId", "userId", b"userId"]) -> None: ...

    USERNFCTOKENS_FIELD_NUMBER: builtins.int
    @property
    def userNfcTokens(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___UserNFCTokensTrait.UserNFCTokenData]: ...
    def __init__(
        self,
        *,
        userNfcTokens: collections.abc.Iterable[global___UserNFCTokensTrait.UserNFCTokenData] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["userNfcTokens", b"userNfcTokens"]) -> None: ...

global___UserNFCTokensTrait = UserNFCTokensTrait

@typing.final
class UserNFCTokenMetadataTrait(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class Metadata(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        SERIALNUMBER_FIELD_NUMBER: builtins.int
        TAGNUMBER_FIELD_NUMBER: builtins.int
        serialNumber: builtins.str
        tagNumber: builtins.str
        def __init__(
            self,
            *,
            serialNumber: builtins.str = ...,
            tagNumber: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["serialNumber", b"serialNumber", "tagNumber", b"tagNumber"]) -> None: ...

    METADATA_FIELD_NUMBER: builtins.int
    @property
    def metadata(self) -> global___UserNFCTokenMetadataTrait.Metadata: ...
    def __init__(
        self,
        *,
        metadata: global___UserNFCTokenMetadataTrait.Metadata | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["metadata", b"metadata"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["metadata", b"metadata"]) -> None: ...

global___UserNFCTokenMetadataTrait = UserNFCTokenMetadataTrait

@typing.final
class BoltLockSettingsTrait(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    AUTORELOCKON_FIELD_NUMBER: builtins.int
    AUTORELOCKDURATION_FIELD_NUMBER: builtins.int
    autoRelockOn: builtins.bool
    @property
    def autoRelockDuration(self) -> google.protobuf.duration_pb2.Duration: ...
    def __init__(
        self,
        *,
        autoRelockOn: builtins.bool = ...,
        autoRelockDuration: google.protobuf.duration_pb2.Duration | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["autoRelockDuration", b"autoRelockDuration"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["autoRelockDuration", b"autoRelockDuration", "autoRelockOn", b"autoRelockOn"]) -> None: ...

global___BoltLockSettingsTrait = BoltLockSettingsTrait

@typing.final
class BoltLockCapabilitiesTrait(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _BoltLockCapabilitiesHandedness:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _BoltLockCapabilitiesHandednessEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[BoltLockCapabilitiesTrait._BoltLockCapabilitiesHandedness.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        BOLT_LOCK_CAPABILITIES_HANDEDNESS_UNSPECIFIED: BoltLockCapabilitiesTrait._BoltLockCapabilitiesHandedness.ValueType  # 0
        BOLT_LOCK_CAPABILITIES_HANDEDNESS_RIGHT: BoltLockCapabilitiesTrait._BoltLockCapabilitiesHandedness.ValueType  # 1
        BOLT_LOCK_CAPABILITIES_HANDEDNESS_LEFT: BoltLockCapabilitiesTrait._BoltLockCapabilitiesHandedness.ValueType  # 2
        BOLT_LOCK_CAPABILITIES_HANDEDNESS_FIXED_UNKNOWN: BoltLockCapabilitiesTrait._BoltLockCapabilitiesHandedness.ValueType  # 3

    class BoltLockCapabilitiesHandedness(_BoltLockCapabilitiesHandedness, metaclass=_BoltLockCapabilitiesHandednessEnumTypeWrapper): ...
    BOLT_LOCK_CAPABILITIES_HANDEDNESS_UNSPECIFIED: BoltLockCapabilitiesTrait.BoltLockCapabilitiesHandedness.ValueType  # 0
    BOLT_LOCK_CAPABILITIES_HANDEDNESS_RIGHT: BoltLockCapabilitiesTrait.BoltLockCapabilitiesHandedness.ValueType  # 1
    BOLT_LOCK_CAPABILITIES_HANDEDNESS_LEFT: BoltLockCapabilitiesTrait.BoltLockCapabilitiesHandedness.ValueType  # 2
    BOLT_LOCK_CAPABILITIES_HANDEDNESS_FIXED_UNKNOWN: BoltLockCapabilitiesTrait.BoltLockCapabilitiesHandedness.ValueType  # 3

    HANDEDNESS_FIELD_NUMBER: builtins.int
    MAXAUTORELOCKDURATION_FIELD_NUMBER: builtins.int
    handedness: global___BoltLockCapabilitiesTrait.BoltLockCapabilitiesHandedness.ValueType
    @property
    def maxAutoRelockDuration(self) -> google.protobuf.duration_pb2.Duration: ...
    def __init__(
        self,
        *,
        handedness: global___BoltLockCapabilitiesTrait.BoltLockCapabilitiesHandedness.ValueType = ...,
        maxAutoRelockDuration: google.protobuf.duration_pb2.Duration | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["maxAutoRelockDuration", b"maxAutoRelockDuration"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["handedness", b"handedness", "maxAutoRelockDuration", b"maxAutoRelockDuration"]) -> None: ...

global___BoltLockCapabilitiesTrait = BoltLockCapabilitiesTrait

@typing.final
class UserNFCTokenSettingsTrait(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class UserNfcTokensEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.int
        @property
        def value(self) -> global___UserNFCTokenSettingsTrait.UserNFCToken: ...
        def __init__(
            self,
            *,
            key: builtins.int = ...,
            value: global___UserNFCTokenSettingsTrait.UserNFCToken | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["value", b"value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    @typing.final
    class UserNFCToken(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        USERID_FIELD_NUMBER: builtins.int
        TOKENDEVICEID_FIELD_NUMBER: builtins.int
        PUBLICKEY_FIELD_NUMBER: builtins.int
        publicKey: builtins.bytes
        @property
        def userId(self) -> weave.common_pb2.ResourceId: ...
        @property
        def tokenDeviceId(self) -> weave.common_pb2.ResourceId: ...
        def __init__(
            self,
            *,
            userId: weave.common_pb2.ResourceId | None = ...,
            tokenDeviceId: weave.common_pb2.ResourceId | None = ...,
            publicKey: builtins.bytes = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["tokenDeviceId", b"tokenDeviceId", "userId", b"userId"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["publicKey", b"publicKey", "tokenDeviceId", b"tokenDeviceId", "userId", b"userId"]) -> None: ...

    USERNFCTOKENS_FIELD_NUMBER: builtins.int
    @property
    def userNfcTokens(self) -> google.protobuf.internal.containers.MessageMap[builtins.int, global___UserNFCTokenSettingsTrait.UserNFCToken]: ...
    def __init__(
        self,
        *,
        userNfcTokens: collections.abc.Mapping[builtins.int, global___UserNFCTokenSettingsTrait.UserNFCToken] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["userNfcTokens", b"userNfcTokens"]) -> None: ...

global___UserNFCTokenSettingsTrait = UserNFCTokenSettingsTrait

@typing.final
class DoorCheckSettingsTrait(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DOORCHECKENABLED_FIELD_NUMBER: builtins.int
    SENSORDEVICEID_FIELD_NUMBER: builtins.int
    @property
    def doorCheckEnabled(self) -> google.protobuf.wrappers_pb2.BoolValue: ...
    @property
    def sensorDeviceId(self) -> weave.common_pb2.ResourceId: ...
    def __init__(
        self,
        *,
        doorCheckEnabled: google.protobuf.wrappers_pb2.BoolValue | None = ...,
        sensorDeviceId: weave.common_pb2.ResourceId | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["doorCheckEnabled", b"doorCheckEnabled", "sensorDeviceId", b"sensorDeviceId"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["doorCheckEnabled", b"doorCheckEnabled", "sensorDeviceId", b"sensorDeviceId"]) -> None: ...

global___DoorCheckSettingsTrait = DoorCheckSettingsTrait

@typing.final
class PincodeInputSettingsTrait(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    WRONGENTRYCODELIMIT_FIELD_NUMBER: builtins.int
    WRONGENTRYDISABLETIME_FIELD_NUMBER: builtins.int
    wrongEntryCodeLimit: builtins.int
    @property
    def wrongEntryDisableTime(self) -> google.protobuf.duration_pb2.Duration: ...
    def __init__(
        self,
        *,
        wrongEntryCodeLimit: builtins.int = ...,
        wrongEntryDisableTime: google.protobuf.duration_pb2.Duration | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["wrongEntryDisableTime", b"wrongEntryDisableTime"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["wrongEntryCodeLimit", b"wrongEntryCodeLimit", "wrongEntryDisableTime", b"wrongEntryDisableTime"]) -> None: ...

global___PincodeInputSettingsTrait = PincodeInputSettingsTrait

@typing.final
class UserPincodesCapabilitiesTrait(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MINPINCODELENGTH_FIELD_NUMBER: builtins.int
    MAXPINCODELENGTH_FIELD_NUMBER: builtins.int
    MAXPINCODESSUPPORTED_FIELD_NUMBER: builtins.int
    minPincodeLength: builtins.int
    maxPincodeLength: builtins.int
    maxPincodesSupported: builtins.int
    def __init__(
        self,
        *,
        minPincodeLength: builtins.int = ...,
        maxPincodeLength: builtins.int = ...,
        maxPincodesSupported: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["maxPincodeLength", b"maxPincodeLength", "maxPincodesSupported", b"maxPincodesSupported", "minPincodeLength", b"minPincodeLength"]) -> None: ...

global___UserPincodesCapabilitiesTrait = UserPincodesCapabilitiesTrait
