"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.timestamp_pb2
import google.protobuf.wrappers_pb2
import sys
import typing
from ...weave import common_pb2 as weave_common_pb2

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class StructureModeTrait(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _StructureMode:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _StructureModeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[StructureModeTrait._StructureMode.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        STRUCTURE_MODE_UNSPECIFIED: StructureModeTrait._StructureMode.ValueType  # 0
        STRUCTURE_MODE_HOME: StructureModeTrait._StructureMode.ValueType  # 1
        STRUCTURE_MODE_AWAY: StructureModeTrait._StructureMode.ValueType  # 2
        STRUCTURE_MODE_SLEEP: StructureModeTrait._StructureMode.ValueType  # 3
        STRUCTURE_MODE_VACATION: StructureModeTrait._StructureMode.ValueType  # 4

    class StructureMode(_StructureMode, metaclass=_StructureModeEnumTypeWrapper): ...
    STRUCTURE_MODE_UNSPECIFIED: StructureModeTrait.StructureMode.ValueType  # 0
    STRUCTURE_MODE_HOME: StructureModeTrait.StructureMode.ValueType  # 1
    STRUCTURE_MODE_AWAY: StructureModeTrait.StructureMode.ValueType  # 2
    STRUCTURE_MODE_SLEEP: StructureModeTrait.StructureMode.ValueType  # 3
    STRUCTURE_MODE_VACATION: StructureModeTrait.StructureMode.ValueType  # 4

    class _Activity:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _ActivityEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[StructureModeTrait._Activity.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        ACTIVITY_UNSPECIFIED: StructureModeTrait._Activity.ValueType  # 0
        ACTIVITY_ACTIVE: StructureModeTrait._Activity.ValueType  # 1
        ACTIVITY_INACTIVE: StructureModeTrait._Activity.ValueType  # 2

    class Activity(_Activity, metaclass=_ActivityEnumTypeWrapper): ...
    ACTIVITY_UNSPECIFIED: StructureModeTrait.Activity.ValueType  # 0
    ACTIVITY_ACTIVE: StructureModeTrait.Activity.ValueType  # 1
    ACTIVITY_INACTIVE: StructureModeTrait.Activity.ValueType  # 2

    class _Presence:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _PresenceEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[StructureModeTrait._Presence.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        PRESENCE_UNSPECIFIED: StructureModeTrait._Presence.ValueType  # 0
        PRESENCE_UNAVAILABLE: StructureModeTrait._Presence.ValueType  # 1
        PRESENCE_PRESENT: StructureModeTrait._Presence.ValueType  # 2
        PRESENCE_ABSENT: StructureModeTrait._Presence.ValueType  # 3

    class Presence(_Presence, metaclass=_PresenceEnumTypeWrapper): ...
    PRESENCE_UNSPECIFIED: StructureModeTrait.Presence.ValueType  # 0
    PRESENCE_UNAVAILABLE: StructureModeTrait.Presence.ValueType  # 1
    PRESENCE_PRESENT: StructureModeTrait.Presence.ValueType  # 2
    PRESENCE_ABSENT: StructureModeTrait.Presence.ValueType  # 3

    class _ModeStickiness:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _ModeStickinessEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[StructureModeTrait._ModeStickiness.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        MODE_STICKINESS_UNSPECIFIED: StructureModeTrait._ModeStickiness.ValueType  # 0
        MODE_STICKINESS_NONE: StructureModeTrait._ModeStickiness.ValueType  # 1
        MODE_STICKINESS_TIMED: StructureModeTrait._ModeStickiness.ValueType  # 2
        MODE_STICKINESS_CONDITIONAL_TIMED: StructureModeTrait._ModeStickiness.ValueType  # 3

    class ModeStickiness(_ModeStickiness, metaclass=_ModeStickinessEnumTypeWrapper): ...
    MODE_STICKINESS_UNSPECIFIED: StructureModeTrait.ModeStickiness.ValueType  # 0
    MODE_STICKINESS_NONE: StructureModeTrait.ModeStickiness.ValueType  # 1
    MODE_STICKINESS_TIMED: StructureModeTrait.ModeStickiness.ValueType  # 2
    MODE_STICKINESS_CONDITIONAL_TIMED: StructureModeTrait.ModeStickiness.ValueType  # 3

    class _StructureModeReason:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _StructureModeReasonEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[StructureModeTrait._StructureModeReason.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        STRUCTURE_MODE_REASON_UNSPECIFIED: StructureModeTrait._StructureModeReason.ValueType  # 0
        STRUCTURE_MODE_REASON_EXPLICIT_INTENT: StructureModeTrait._StructureModeReason.ValueType  # 1
        STRUCTURE_MODE_REASON_IMPLICIT_INTENT: StructureModeTrait._StructureModeReason.ValueType  # 2
        STRUCTURE_MODE_REASON_ACTIVITY: StructureModeTrait._StructureModeReason.ValueType  # 3
        STRUCTURE_MODE_REASON_EXTENDED_INACTIVITY: StructureModeTrait._StructureModeReason.ValueType  # 4
        STRUCTURE_MODE_REASON_IDENTIFIED_PRESENCE: StructureModeTrait._StructureModeReason.ValueType  # 5
        STRUCTURE_MODE_REASON_IDENTIFIED_ABSENCE: StructureModeTrait._StructureModeReason.ValueType  # 6
        STRUCTURE_MODE_REASON_SCHEDULE: StructureModeTrait._StructureModeReason.ValueType  # 7

    class StructureModeReason(_StructureModeReason, metaclass=_StructureModeReasonEnumTypeWrapper): ...
    STRUCTURE_MODE_REASON_UNSPECIFIED: StructureModeTrait.StructureModeReason.ValueType  # 0
    STRUCTURE_MODE_REASON_EXPLICIT_INTENT: StructureModeTrait.StructureModeReason.ValueType  # 1
    STRUCTURE_MODE_REASON_IMPLICIT_INTENT: StructureModeTrait.StructureModeReason.ValueType  # 2
    STRUCTURE_MODE_REASON_ACTIVITY: StructureModeTrait.StructureModeReason.ValueType  # 3
    STRUCTURE_MODE_REASON_EXTENDED_INACTIVITY: StructureModeTrait.StructureModeReason.ValueType  # 4
    STRUCTURE_MODE_REASON_IDENTIFIED_PRESENCE: StructureModeTrait.StructureModeReason.ValueType  # 5
    STRUCTURE_MODE_REASON_IDENTIFIED_ABSENCE: StructureModeTrait.StructureModeReason.ValueType  # 6
    STRUCTURE_MODE_REASON_SCHEDULE: StructureModeTrait.StructureModeReason.ValueType  # 7

    class _StructureModeActorMethod:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _StructureModeActorMethodEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[StructureModeTrait._StructureModeActorMethod.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        STRUCTURE_MODE_ACTOR_METHOD_UNSPECIFIED: StructureModeTrait._StructureModeActorMethod.ValueType  # 0
        STRUCTURE_MODE_ACTOR_METHOD_LEGACY_NEST_APP: StructureModeTrait._StructureModeActorMethod.ValueType  # 1
        STRUCTURE_MODE_ACTOR_METHOD_GOOGLE_HOME_APP: StructureModeTrait._StructureModeActorMethod.ValueType  # 2
        STRUCTURE_MODE_ACTOR_METHOD_GOOGLE_ASSISTANT: StructureModeTrait._StructureModeActorMethod.ValueType  # 3

    class StructureModeActorMethod(_StructureModeActorMethod, metaclass=_StructureModeActorMethodEnumTypeWrapper): ...
    STRUCTURE_MODE_ACTOR_METHOD_UNSPECIFIED: StructureModeTrait.StructureModeActorMethod.ValueType  # 0
    STRUCTURE_MODE_ACTOR_METHOD_LEGACY_NEST_APP: StructureModeTrait.StructureModeActorMethod.ValueType  # 1
    STRUCTURE_MODE_ACTOR_METHOD_GOOGLE_HOME_APP: StructureModeTrait.StructureModeActorMethod.ValueType  # 2
    STRUCTURE_MODE_ACTOR_METHOD_GOOGLE_ASSISTANT: StructureModeTrait.StructureModeActorMethod.ValueType  # 3

    class _UserBlameType:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _UserBlameTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[StructureModeTrait._UserBlameType.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        USER_BLAME_TYPE_UNSPECIFIED: StructureModeTrait._UserBlameType.ValueType  # 0
        USER_BLAME_TYPE_PHONE_LOCATION: StructureModeTrait._UserBlameType.ValueType  # 1
        USER_BLAME_TYPE_MANUAL_CHANGE: StructureModeTrait._UserBlameType.ValueType  # 2

    class UserBlameType(_UserBlameType, metaclass=_UserBlameTypeEnumTypeWrapper): ...
    USER_BLAME_TYPE_UNSPECIFIED: StructureModeTrait.UserBlameType.ValueType  # 0
    USER_BLAME_TYPE_PHONE_LOCATION: StructureModeTrait.UserBlameType.ValueType  # 1
    USER_BLAME_TYPE_MANUAL_CHANGE: StructureModeTrait.UserBlameType.ValueType  # 2

    class _DeviceBlameType:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _DeviceBlameTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[StructureModeTrait._DeviceBlameType.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        DEVICE_BLAME_TYPE_UNSPECIFIED: StructureModeTrait._DeviceBlameType.ValueType  # 0
        DEVICE_BLAME_TYPE_LOCK: StructureModeTrait._DeviceBlameType.ValueType  # 1
        DEVICE_BLAME_TYPE_UNLOCK: StructureModeTrait._DeviceBlameType.ValueType  # 2
        DEVICE_BLAME_TYPE_MOTION_DETECTION: StructureModeTrait._DeviceBlameType.ValueType  # 3
        DEVICE_BLAME_TYPE_TOUCH_INTERACTION: StructureModeTrait._DeviceBlameType.ValueType  # 4
        DEVICE_BLAME_TYPE_VOICE_INTERACTION: StructureModeTrait._DeviceBlameType.ValueType  # 5

    class DeviceBlameType(_DeviceBlameType, metaclass=_DeviceBlameTypeEnumTypeWrapper): ...
    DEVICE_BLAME_TYPE_UNSPECIFIED: StructureModeTrait.DeviceBlameType.ValueType  # 0
    DEVICE_BLAME_TYPE_LOCK: StructureModeTrait.DeviceBlameType.ValueType  # 1
    DEVICE_BLAME_TYPE_UNLOCK: StructureModeTrait.DeviceBlameType.ValueType  # 2
    DEVICE_BLAME_TYPE_MOTION_DETECTION: StructureModeTrait.DeviceBlameType.ValueType  # 3
    DEVICE_BLAME_TYPE_TOUCH_INTERACTION: StructureModeTrait.DeviceBlameType.ValueType  # 4
    DEVICE_BLAME_TYPE_VOICE_INTERACTION: StructureModeTrait.DeviceBlameType.ValueType  # 5

    class _NonPropagatingChangeSourceType:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _NonPropagatingChangeSourceTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[StructureModeTrait._NonPropagatingChangeSourceType.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        NON_PROPAGATING_CHANGE_SOURCE_TYPE_UNSPECIFIED: StructureModeTrait._NonPropagatingChangeSourceType.ValueType  # 0
        NON_PROPAGATING_CHANGE_SOURCE_TYPE_CZ: StructureModeTrait._NonPropagatingChangeSourceType.ValueType  # 1

    class NonPropagatingChangeSourceType(_NonPropagatingChangeSourceType, metaclass=_NonPropagatingChangeSourceTypeEnumTypeWrapper): ...
    NON_PROPAGATING_CHANGE_SOURCE_TYPE_UNSPECIFIED: StructureModeTrait.NonPropagatingChangeSourceType.ValueType  # 0
    NON_PROPAGATING_CHANGE_SOURCE_TYPE_CZ: StructureModeTrait.NonPropagatingChangeSourceType.ValueType  # 1

    class _StructureModeChangeResponseType:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _StructureModeChangeResponseTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[StructureModeTrait._StructureModeChangeResponseType.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        STRUCTURE_MODE_CHANGE_RESPONSE_TYPE_UNSPECIFIED: StructureModeTrait._StructureModeChangeResponseType.ValueType  # 0
        STRUCTURE_MODE_CHANGE_RESPONSE_TYPE_SUCCESS: StructureModeTrait._StructureModeChangeResponseType.ValueType  # 1
        STRUCTURE_MODE_CHANGE_RESPONSE_TYPE_FAIL_ALREADY: StructureModeTrait._StructureModeChangeResponseType.ValueType  # 2

    class StructureModeChangeResponseType(_StructureModeChangeResponseType, metaclass=_StructureModeChangeResponseTypeEnumTypeWrapper): ...
    STRUCTURE_MODE_CHANGE_RESPONSE_TYPE_UNSPECIFIED: StructureModeTrait.StructureModeChangeResponseType.ValueType  # 0
    STRUCTURE_MODE_CHANGE_RESPONSE_TYPE_SUCCESS: StructureModeTrait.StructureModeChangeResponseType.ValueType  # 1
    STRUCTURE_MODE_CHANGE_RESPONSE_TYPE_FAIL_ALREADY: StructureModeTrait.StructureModeChangeResponseType.ValueType  # 2

    class _StructureModeCompleteUpdateResponseType:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _StructureModeCompleteUpdateResponseTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[StructureModeTrait._StructureModeCompleteUpdateResponseType.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        STRUCTURE_MODE_COMPLETE_UPDATE_RESPONSE_TYPE_UNSPECIFIED: StructureModeTrait._StructureModeCompleteUpdateResponseType.ValueType  # 0
        STRUCTURE_MODE_COMPLETE_UPDATE_RESPONSE_TYPE_SUCCESS: StructureModeTrait._StructureModeCompleteUpdateResponseType.ValueType  # 1
        STRUCTURE_MODE_COMPLETE_UPDATE_RESPONSE_TYPE_FAIL_ALREADY: StructureModeTrait._StructureModeCompleteUpdateResponseType.ValueType  # 2
        STRUCTURE_MODE_COMPLETE_UPDATE_RESPONSE_TYPE_FAIL_VERSION: StructureModeTrait._StructureModeCompleteUpdateResponseType.ValueType  # 3
        STRUCTURE_MODE_COMPLETE_UPDATE_RESPONSE_TYPE_FAIL_OTHER: StructureModeTrait._StructureModeCompleteUpdateResponseType.ValueType  # 4

    class StructureModeCompleteUpdateResponseType(_StructureModeCompleteUpdateResponseType, metaclass=_StructureModeCompleteUpdateResponseTypeEnumTypeWrapper): ...
    STRUCTURE_MODE_COMPLETE_UPDATE_RESPONSE_TYPE_UNSPECIFIED: StructureModeTrait.StructureModeCompleteUpdateResponseType.ValueType  # 0
    STRUCTURE_MODE_COMPLETE_UPDATE_RESPONSE_TYPE_SUCCESS: StructureModeTrait.StructureModeCompleteUpdateResponseType.ValueType  # 1
    STRUCTURE_MODE_COMPLETE_UPDATE_RESPONSE_TYPE_FAIL_ALREADY: StructureModeTrait.StructureModeCompleteUpdateResponseType.ValueType  # 2
    STRUCTURE_MODE_COMPLETE_UPDATE_RESPONSE_TYPE_FAIL_VERSION: StructureModeTrait.StructureModeCompleteUpdateResponseType.ValueType  # 3
    STRUCTURE_MODE_COMPLETE_UPDATE_RESPONSE_TYPE_FAIL_OTHER: StructureModeTrait.StructureModeCompleteUpdateResponseType.ValueType  # 4

    class _LegacyAwayState:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _LegacyAwayStateEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[StructureModeTrait._LegacyAwayState.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        LEGACY_AWAY_STATE_UNSPECIFIED: StructureModeTrait._LegacyAwayState.ValueType  # 0
        LEGACY_AWAY_STATE_TRUE: StructureModeTrait._LegacyAwayState.ValueType  # 1
        LEGACY_AWAY_STATE_FALSE: StructureModeTrait._LegacyAwayState.ValueType  # 2

    class LegacyAwayState(_LegacyAwayState, metaclass=_LegacyAwayStateEnumTypeWrapper): ...
    LEGACY_AWAY_STATE_UNSPECIFIED: StructureModeTrait.LegacyAwayState.ValueType  # 0
    LEGACY_AWAY_STATE_TRUE: StructureModeTrait.LegacyAwayState.ValueType  # 1
    LEGACY_AWAY_STATE_FALSE: StructureModeTrait.LegacyAwayState.ValueType  # 2

    class _LegacyAwaySetter:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _LegacyAwaySetterEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[StructureModeTrait._LegacyAwaySetter.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        LEGACY_AWAY_SETTER_UNSPECIFIED: StructureModeTrait._LegacyAwaySetter.ValueType  # 0
        LEGACY_AWAY_SETTER_CLIENT: StructureModeTrait._LegacyAwaySetter.ValueType  # 1
        LEGACY_AWAY_SETTER_CONTROL: StructureModeTrait._LegacyAwaySetter.ValueType  # 2
        LEGACY_AWAY_SETTER_CLOUD: StructureModeTrait._LegacyAwaySetter.ValueType  # 3

    class LegacyAwaySetter(_LegacyAwaySetter, metaclass=_LegacyAwaySetterEnumTypeWrapper): ...
    LEGACY_AWAY_SETTER_UNSPECIFIED: StructureModeTrait.LegacyAwaySetter.ValueType  # 0
    LEGACY_AWAY_SETTER_CLIENT: StructureModeTrait.LegacyAwaySetter.ValueType  # 1
    LEGACY_AWAY_SETTER_CONTROL: StructureModeTrait.LegacyAwaySetter.ValueType  # 2
    LEGACY_AWAY_SETTER_CLOUD: StructureModeTrait.LegacyAwaySetter.ValueType  # 3

    class _LegacyTouchedBy:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _LegacyTouchedByEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[StructureModeTrait._LegacyTouchedBy.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        LEGACY_TOUCHED_BY_UNSPECIFIED: StructureModeTrait._LegacyTouchedBy.ValueType  # 0
        LEGACY_TOUCHED_BY_NOBODY: StructureModeTrait._LegacyTouchedBy.ValueType  # 1
        LEGACY_TOUCHED_BY_LEARNING: StructureModeTrait._LegacyTouchedBy.ValueType  # 2
        LEGACY_TOUCHED_BY_LOCAL: StructureModeTrait._LegacyTouchedBy.ValueType  # 3
        LEGACY_TOUCHED_BY_REMOTE: StructureModeTrait._LegacyTouchedBy.ValueType  # 4
        LEGACY_TOUCHED_BY_WEB: StructureModeTrait._LegacyTouchedBy.ValueType  # 5
        LEGACY_TOUCHED_BY_ANDROID: StructureModeTrait._LegacyTouchedBy.ValueType  # 6
        LEGACY_TOUCHED_BY_IOS: StructureModeTrait._LegacyTouchedBy.ValueType  # 7
        LEGACY_TOUCHED_BY_WIN_MOBILE: StructureModeTrait._LegacyTouchedBy.ValueType  # 8
        LEGACY_TOUCHED_BY_TUNE_UP: StructureModeTrait._LegacyTouchedBy.ValueType  # 9
        LEGACY_TOUCHED_BY_DR: StructureModeTrait._LegacyTouchedBy.ValueType  # 10
        LEGACY_TOUCHED_BY_TOU: StructureModeTrait._LegacyTouchedBy.ValueType  # 11
        LEGACY_TOUCHED_BY_TOPAZ_CO: StructureModeTrait._LegacyTouchedBy.ValueType  # 12
        LEGACY_TOUCHED_BY_PROGRAMMER: StructureModeTrait._LegacyTouchedBy.ValueType  # 13
        LEGACY_TOUCHED_BY_TOPAZ_SMOKE: StructureModeTrait._LegacyTouchedBy.ValueType  # 14
        LEGACY_TOUCHED_BY_DEMAND_CHARGE: StructureModeTrait._LegacyTouchedBy.ValueType  # 15

    class LegacyTouchedBy(_LegacyTouchedBy, metaclass=_LegacyTouchedByEnumTypeWrapper): ...
    LEGACY_TOUCHED_BY_UNSPECIFIED: StructureModeTrait.LegacyTouchedBy.ValueType  # 0
    LEGACY_TOUCHED_BY_NOBODY: StructureModeTrait.LegacyTouchedBy.ValueType  # 1
    LEGACY_TOUCHED_BY_LEARNING: StructureModeTrait.LegacyTouchedBy.ValueType  # 2
    LEGACY_TOUCHED_BY_LOCAL: StructureModeTrait.LegacyTouchedBy.ValueType  # 3
    LEGACY_TOUCHED_BY_REMOTE: StructureModeTrait.LegacyTouchedBy.ValueType  # 4
    LEGACY_TOUCHED_BY_WEB: StructureModeTrait.LegacyTouchedBy.ValueType  # 5
    LEGACY_TOUCHED_BY_ANDROID: StructureModeTrait.LegacyTouchedBy.ValueType  # 6
    LEGACY_TOUCHED_BY_IOS: StructureModeTrait.LegacyTouchedBy.ValueType  # 7
    LEGACY_TOUCHED_BY_WIN_MOBILE: StructureModeTrait.LegacyTouchedBy.ValueType  # 8
    LEGACY_TOUCHED_BY_TUNE_UP: StructureModeTrait.LegacyTouchedBy.ValueType  # 9
    LEGACY_TOUCHED_BY_DR: StructureModeTrait.LegacyTouchedBy.ValueType  # 10
    LEGACY_TOUCHED_BY_TOU: StructureModeTrait.LegacyTouchedBy.ValueType  # 11
    LEGACY_TOUCHED_BY_TOPAZ_CO: StructureModeTrait.LegacyTouchedBy.ValueType  # 12
    LEGACY_TOUCHED_BY_PROGRAMMER: StructureModeTrait.LegacyTouchedBy.ValueType  # 13
    LEGACY_TOUCHED_BY_TOPAZ_SMOKE: StructureModeTrait.LegacyTouchedBy.ValueType  # 14
    LEGACY_TOUCHED_BY_DEMAND_CHARGE: StructureModeTrait.LegacyTouchedBy.ValueType  # 15

    class _AutoAskType:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _AutoAskTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[StructureModeTrait._AutoAskType.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        AUTO_ASK_TYPE_UNSPECIFIED: StructureModeTrait._AutoAskType.ValueType  # 0
        AUTO_ASK_TYPE_AWAY_AND_ARM: StructureModeTrait._AutoAskType.ValueType  # 1
        AUTO_ASK_TYPE_HOME_AND_DISARM: StructureModeTrait._AutoAskType.ValueType  # 2
        AUTO_ASK_TYPE_ARM: StructureModeTrait._AutoAskType.ValueType  # 3
        AUTO_ASK_TYPE_DISARM: StructureModeTrait._AutoAskType.ValueType  # 4

    class AutoAskType(_AutoAskType, metaclass=_AutoAskTypeEnumTypeWrapper): ...
    AUTO_ASK_TYPE_UNSPECIFIED: StructureModeTrait.AutoAskType.ValueType  # 0
    AUTO_ASK_TYPE_AWAY_AND_ARM: StructureModeTrait.AutoAskType.ValueType  # 1
    AUTO_ASK_TYPE_HOME_AND_DISARM: StructureModeTrait.AutoAskType.ValueType  # 2
    AUTO_ASK_TYPE_ARM: StructureModeTrait.AutoAskType.ValueType  # 3
    AUTO_ASK_TYPE_DISARM: StructureModeTrait.AutoAskType.ValueType  # 4

    class _AutoAskArm:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _AutoAskArmEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[StructureModeTrait._AutoAskArm.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        AUTO_ASK_ARM_UNSPECIFIED: StructureModeTrait._AutoAskArm.ValueType  # 0
        AUTO_ASK_ARM_TYPE_ARM: StructureModeTrait._AutoAskArm.ValueType  # 1
        AUTO_ASK_ARM_TYPE_DISARM: StructureModeTrait._AutoAskArm.ValueType  # 2

    class AutoAskArm(_AutoAskArm, metaclass=_AutoAskArmEnumTypeWrapper): ...
    AUTO_ASK_ARM_UNSPECIFIED: StructureModeTrait.AutoAskArm.ValueType  # 0
    AUTO_ASK_ARM_TYPE_ARM: StructureModeTrait.AutoAskArm.ValueType  # 1
    AUTO_ASK_ARM_TYPE_DISARM: StructureModeTrait.AutoAskArm.ValueType  # 2

    class _AutoAskLock:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _AutoAskLockEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[StructureModeTrait._AutoAskLock.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        AUTO_ASK_LOCK_UNSPECIFIED: StructureModeTrait._AutoAskLock.ValueType  # 0
        AUTO_ASK_LOCK_TYPE_LOCK: StructureModeTrait._AutoAskLock.ValueType  # 1
        AUTO_ASK_LOCK_TYPE_UNLOCK: StructureModeTrait._AutoAskLock.ValueType  # 2

    class AutoAskLock(_AutoAskLock, metaclass=_AutoAskLockEnumTypeWrapper): ...
    AUTO_ASK_LOCK_UNSPECIFIED: StructureModeTrait.AutoAskLock.ValueType  # 0
    AUTO_ASK_LOCK_TYPE_LOCK: StructureModeTrait.AutoAskLock.ValueType  # 1
    AUTO_ASK_LOCK_TYPE_UNLOCK: StructureModeTrait.AutoAskLock.ValueType  # 2

    class _AutoAskStructureMode:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _AutoAskStructureModeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[StructureModeTrait._AutoAskStructureMode.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        AUTO_ASK_STRUCTURE_MODE_UNSPECIFIED: StructureModeTrait._AutoAskStructureMode.ValueType  # 0
        AUTO_ASK_STRUCTURE_MODE_TYPE_HOME: StructureModeTrait._AutoAskStructureMode.ValueType  # 1
        AUTO_ASK_STRUCTURE_MODE_TYPE_AWAY: StructureModeTrait._AutoAskStructureMode.ValueType  # 2

    class AutoAskStructureMode(_AutoAskStructureMode, metaclass=_AutoAskStructureModeEnumTypeWrapper): ...
    AUTO_ASK_STRUCTURE_MODE_UNSPECIFIED: StructureModeTrait.AutoAskStructureMode.ValueType  # 0
    AUTO_ASK_STRUCTURE_MODE_TYPE_HOME: StructureModeTrait.AutoAskStructureMode.ValueType  # 1
    AUTO_ASK_STRUCTURE_MODE_TYPE_AWAY: StructureModeTrait.AutoAskStructureMode.ValueType  # 2

    @typing.final
    class BlamesEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.int
        @property
        def value(self) -> global___StructureModeTrait.StructureModeBlame: ...
        def __init__(
            self,
            *,
            key: builtins.int = ...,
            value: global___StructureModeTrait.StructureModeBlame | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["value", b"value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    @typing.final
    class Occupancy(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        ACTIVITY_FIELD_NUMBER: builtins.int
        PRESENCE_FIELD_NUMBER: builtins.int
        LASTACTIVITYTIME_FIELD_NUMBER: builtins.int
        ACTIVITYHOLDOFF_FIELD_NUMBER: builtins.int
        activity: global___StructureModeTrait.Activity.ValueType
        presence: global___StructureModeTrait.Presence.ValueType
        @property
        def lastActivityTime(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
        @property
        def activityHoldOff(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
        def __init__(
            self,
            *,
            activity: global___StructureModeTrait.Activity.ValueType = ...,
            presence: global___StructureModeTrait.Presence.ValueType = ...,
            lastActivityTime: google.protobuf.timestamp_pb2.Timestamp | None = ...,
            activityHoldOff: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["activityHoldOff", b"activityHoldOff", "lastActivityTime", b"lastActivityTime"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["activity", b"activity", "activityHoldOff", b"activityHoldOff", "lastActivityTime", b"lastActivityTime", "presence", b"presence"]) -> None: ...

    @typing.final
    class Allowance(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        MODESTICKINESS_FIELD_NUMBER: builtins.int
        MODESTICKINESSEXPIRATION_FIELD_NUMBER: builtins.int
        modeStickiness: global___StructureModeTrait.ModeStickiness.ValueType
        @property
        def modeStickinessExpiration(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
        def __init__(
            self,
            *,
            modeStickiness: global___StructureModeTrait.ModeStickiness.ValueType = ...,
            modeStickinessExpiration: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["modeStickinessExpiration", b"modeStickinessExpiration"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["modeStickiness", b"modeStickiness", "modeStickinessExpiration", b"modeStickinessExpiration"]) -> None: ...

    @typing.final
    class UserBlame(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        GAIAID_FIELD_NUMBER: builtins.int
        BLAMETYPE_FIELD_NUMBER: builtins.int
        gaiaId: builtins.int
        blameType: global___StructureModeTrait.UserBlameType.ValueType
        def __init__(
            self,
            *,
            gaiaId: builtins.int = ...,
            blameType: global___StructureModeTrait.UserBlameType.ValueType = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["blameType", b"blameType", "gaiaId", b"gaiaId"]) -> None: ...

    @typing.final
    class DeviceBlame(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        HGSDEVICEID_FIELD_NUMBER: builtins.int
        BLAMETYPE_FIELD_NUMBER: builtins.int
        hgsDeviceId: builtins.str
        blameType: global___StructureModeTrait.DeviceBlameType.ValueType
        def __init__(
            self,
            *,
            hgsDeviceId: builtins.str = ...,
            blameType: global___StructureModeTrait.DeviceBlameType.ValueType = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["blameType", b"blameType", "hgsDeviceId", b"hgsDeviceId"]) -> None: ...

    @typing.final
    class StructureModeBlame(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        OBSERVEDTIMESTAMP_FIELD_NUMBER: builtins.int
        PAYLOADTYPEURL_FIELD_NUMBER: builtins.int
        LEAFEVENTURL_FIELD_NUMBER: builtins.int
        PAYLOAD_FIELD_NUMBER: builtins.int
        USERBLAME_FIELD_NUMBER: builtins.int
        DEVICEBLAME_FIELD_NUMBER: builtins.int
        payloadTypeUrl: builtins.str
        leafEventUrl: builtins.str
        payload: builtins.bytes
        @property
        def observedTimestamp(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
        @property
        def userBlame(self) -> global___StructureModeTrait.UserBlame: ...
        @property
        def deviceBlame(self) -> global___StructureModeTrait.DeviceBlame: ...
        def __init__(
            self,
            *,
            observedTimestamp: google.protobuf.timestamp_pb2.Timestamp | None = ...,
            payloadTypeUrl: builtins.str = ...,
            leafEventUrl: builtins.str = ...,
            payload: builtins.bytes = ...,
            userBlame: global___StructureModeTrait.UserBlame | None = ...,
            deviceBlame: global___StructureModeTrait.DeviceBlame | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["deviceBlame", b"deviceBlame", "observedTimestamp", b"observedTimestamp", "userBlame", b"userBlame"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["deviceBlame", b"deviceBlame", "leafEventUrl", b"leafEventUrl", "observedTimestamp", b"observedTimestamp", "payload", b"payload", "payloadTypeUrl", b"payloadTypeUrl", "userBlame", b"userBlame"]) -> None: ...

    @typing.final
    class PrivateTraitHandlerState(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        ISCZUPDATESTATEOK_FIELD_NUMBER: builtins.int
        isCzUpdateStateOk: builtins.bool
        def __init__(
            self,
            *,
            isCzUpdateStateOk: builtins.bool = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["isCzUpdateStateOk", b"isCzUpdateStateOk"]) -> None: ...

    @typing.final
    class UserInfo(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        RTSUSERID_FIELD_NUMBER: builtins.int
        PHOENIXUSERID_FIELD_NUMBER: builtins.int
        @property
        def rtsUserId(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        @property
        def phoenixUserId(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        def __init__(
            self,
            *,
            rtsUserId: google.protobuf.wrappers_pb2.StringValue | None = ...,
            phoenixUserId: google.protobuf.wrappers_pb2.StringValue | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["phoenixUserId", b"phoenixUserId", "rtsUserId", b"rtsUserId"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["phoenixUserId", b"phoenixUserId", "rtsUserId", b"rtsUserId"]) -> None: ...

    @typing.final
    class StructureModeChangeRequest(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        STRUCTUREMODE_FIELD_NUMBER: builtins.int
        REASON_FIELD_NUMBER: builtins.int
        USERID_FIELD_NUMBER: builtins.int
        NONPROPAGATINGCHANGEDETAILS_FIELD_NUMBER: builtins.int
        ACTORMETHOD_FIELD_NUMBER: builtins.int
        structureMode: global___StructureModeTrait.StructureMode.ValueType
        reason: global___StructureModeTrait.StructureModeReason.ValueType
        actorMethod: global___StructureModeTrait.StructureModeActorMethod.ValueType
        @property
        def userId(self) -> weave_common_pb2.ResourceId: ...
        @property
        def nonPropagatingChangeDetails(self) -> global___StructureModeTrait.NonPropagatingChangeDetails: ...
        def __init__(
            self,
            *,
            structureMode: global___StructureModeTrait.StructureMode.ValueType = ...,
            reason: global___StructureModeTrait.StructureModeReason.ValueType = ...,
            userId: weave_common_pb2.ResourceId | None = ...,
            nonPropagatingChangeDetails: global___StructureModeTrait.NonPropagatingChangeDetails | None = ...,
            actorMethod: global___StructureModeTrait.StructureModeActorMethod.ValueType = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["nonPropagatingChangeDetails", b"nonPropagatingChangeDetails", "userId", b"userId"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["actorMethod", b"actorMethod", "nonPropagatingChangeDetails", b"nonPropagatingChangeDetails", "reason", b"reason", "structureMode", b"structureMode", "userId", b"userId"]) -> None: ...

    @typing.final
    class NonPropagatingChangeDetails(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        SOURCETYPE_FIELD_NUMBER: builtins.int
        CHANGETIME_FIELD_NUMBER: builtins.int
        sourceType: global___StructureModeTrait.NonPropagatingChangeSourceType.ValueType
        @property
        def changeTime(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
        def __init__(
            self,
            *,
            sourceType: global___StructureModeTrait.NonPropagatingChangeSourceType.ValueType = ...,
            changeTime: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["changeTime", b"changeTime"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["changeTime", b"changeTime", "sourceType", b"sourceType"]) -> None: ...

    @typing.final
    class StructureModeChangeResponse(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        RESPONSETYPE_FIELD_NUMBER: builtins.int
        responseType: global___StructureModeTrait.StructureModeChangeResponseType.ValueType
        def __init__(
            self,
            *,
            responseType: global___StructureModeTrait.StructureModeChangeResponseType.ValueType = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["responseType", b"responseType"]) -> None: ...

    @typing.final
    class StructureModeCompleteUpdateRequest(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        @typing.final
        class BlamesEntry(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            KEY_FIELD_NUMBER: builtins.int
            VALUE_FIELD_NUMBER: builtins.int
            key: builtins.int
            @property
            def value(self) -> global___StructureModeTrait.StructureModeBlame: ...
            def __init__(
                self,
                *,
                key: builtins.int = ...,
                value: global___StructureModeTrait.StructureModeBlame | None = ...,
            ) -> None: ...
            def HasField(self, field_name: typing.Literal["value", b"value"]) -> builtins.bool: ...
            def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

        STRUCTUREMODE_FIELD_NUMBER: builtins.int
        OCCUPANCY_FIELD_NUMBER: builtins.int
        ALLOWANCE_FIELD_NUMBER: builtins.int
        STRUCTUREMODEREASON_FIELD_NUMBER: builtins.int
        STRUCTUREMODESETTER_FIELD_NUMBER: builtins.int
        STRUCTUREMODEEFFECTIVETIME_FIELD_NUMBER: builtins.int
        ACTIVITYAGNOSTICSTRUCTUREMODE_FIELD_NUMBER: builtins.int
        ACTIVITYAGNOSTICSTRUCTUREMODEEFFECTIVETIME_FIELD_NUMBER: builtins.int
        REVISIONID_FIELD_NUMBER: builtins.int
        IDENTIFIEDPRESENCECHANGERTSUSERID_FIELD_NUMBER: builtins.int
        IDENTIFIEDPRESENCECHANGETIME_FIELD_NUMBER: builtins.int
        RECENTUSERARRIVALS_FIELD_NUMBER: builtins.int
        RECENTUSERDEPARTURES_FIELD_NUMBER: builtins.int
        MLPSESSIONID_FIELD_NUMBER: builtins.int
        BLAMES_FIELD_NUMBER: builtins.int
        PRIMARYBLAME_FIELD_NUMBER: builtins.int
        structureMode: global___StructureModeTrait.StructureMode.ValueType
        structureModeReason: global___StructureModeTrait.StructureModeReason.ValueType
        activityAgnosticStructureMode: global___StructureModeTrait.StructureMode.ValueType
        mlpSessionId: builtins.str
        @property
        def occupancy(self) -> global___StructureModeTrait.Occupancy: ...
        @property
        def allowance(self) -> global___StructureModeTrait.Allowance: ...
        @property
        def structureModeSetter(self) -> weave_common_pb2.ResourceId: ...
        @property
        def structureModeEffectiveTime(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
        @property
        def activityAgnosticStructureModeEffectiveTime(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
        @property
        def revisionId(self) -> google.protobuf.wrappers_pb2.UInt64Value: ...
        @property
        def identifiedPresenceChangeRtsUserId(self) -> global___StructureModeTrait.UserInfo: ...
        @property
        def identifiedPresenceChangeTime(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
        @property
        def recentUserArrivals(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___StructureModeTrait.UserInfo]: ...
        @property
        def recentUserDepartures(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___StructureModeTrait.UserInfo]: ...
        @property
        def blames(self) -> google.protobuf.internal.containers.MessageMap[builtins.int, global___StructureModeTrait.StructureModeBlame]: ...
        @property
        def primaryBlame(self) -> global___StructureModeTrait.StructureModeBlame: ...
        def __init__(
            self,
            *,
            structureMode: global___StructureModeTrait.StructureMode.ValueType = ...,
            occupancy: global___StructureModeTrait.Occupancy | None = ...,
            allowance: global___StructureModeTrait.Allowance | None = ...,
            structureModeReason: global___StructureModeTrait.StructureModeReason.ValueType = ...,
            structureModeSetter: weave_common_pb2.ResourceId | None = ...,
            structureModeEffectiveTime: google.protobuf.timestamp_pb2.Timestamp | None = ...,
            activityAgnosticStructureMode: global___StructureModeTrait.StructureMode.ValueType = ...,
            activityAgnosticStructureModeEffectiveTime: google.protobuf.timestamp_pb2.Timestamp | None = ...,
            revisionId: google.protobuf.wrappers_pb2.UInt64Value | None = ...,
            identifiedPresenceChangeRtsUserId: global___StructureModeTrait.UserInfo | None = ...,
            identifiedPresenceChangeTime: google.protobuf.timestamp_pb2.Timestamp | None = ...,
            recentUserArrivals: collections.abc.Iterable[global___StructureModeTrait.UserInfo] | None = ...,
            recentUserDepartures: collections.abc.Iterable[global___StructureModeTrait.UserInfo] | None = ...,
            mlpSessionId: builtins.str = ...,
            blames: collections.abc.Mapping[builtins.int, global___StructureModeTrait.StructureModeBlame] | None = ...,
            primaryBlame: global___StructureModeTrait.StructureModeBlame | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["activityAgnosticStructureModeEffectiveTime", b"activityAgnosticStructureModeEffectiveTime", "allowance", b"allowance", "identifiedPresenceChangeRtsUserId", b"identifiedPresenceChangeRtsUserId", "identifiedPresenceChangeTime", b"identifiedPresenceChangeTime", "occupancy", b"occupancy", "primaryBlame", b"primaryBlame", "revisionId", b"revisionId", "structureModeEffectiveTime", b"structureModeEffectiveTime", "structureModeSetter", b"structureModeSetter"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["activityAgnosticStructureMode", b"activityAgnosticStructureMode", "activityAgnosticStructureModeEffectiveTime", b"activityAgnosticStructureModeEffectiveTime", "allowance", b"allowance", "blames", b"blames", "identifiedPresenceChangeRtsUserId", b"identifiedPresenceChangeRtsUserId", "identifiedPresenceChangeTime", b"identifiedPresenceChangeTime", "mlpSessionId", b"mlpSessionId", "occupancy", b"occupancy", "primaryBlame", b"primaryBlame", "recentUserArrivals", b"recentUserArrivals", "recentUserDepartures", b"recentUserDepartures", "revisionId", b"revisionId", "structureMode", b"structureMode", "structureModeEffectiveTime", b"structureModeEffectiveTime", "structureModeReason", b"structureModeReason", "structureModeSetter", b"structureModeSetter"]) -> None: ...

    @typing.final
    class StructureModeCompleteUpdateResponse(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        RESPONSETYPE_FIELD_NUMBER: builtins.int
        COMPLETERESPONSETYPE_FIELD_NUMBER: builtins.int
        responseType: global___StructureModeTrait.StructureModeChangeResponseType.ValueType
        completeResponseType: global___StructureModeTrait.StructureModeCompleteUpdateResponseType.ValueType
        def __init__(
            self,
            *,
            responseType: global___StructureModeTrait.StructureModeChangeResponseType.ValueType = ...,
            completeResponseType: global___StructureModeTrait.StructureModeCompleteUpdateResponseType.ValueType = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["completeResponseType", b"completeResponseType", "responseType", b"responseType"]) -> None: ...

    @typing.final
    class LegacyStructureModeChangeRequest(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        STRUCTUREMODE_FIELD_NUMBER: builtins.int
        REASON_FIELD_NUMBER: builtins.int
        USERID_FIELD_NUMBER: builtins.int
        WWNID_FIELD_NUMBER: builtins.int
        structureMode: global___StructureModeTrait.StructureMode.ValueType
        reason: global___StructureModeTrait.StructureModeReason.ValueType
        @property
        def userId(self) -> weave_common_pb2.ResourceId: ...
        @property
        def wwnId(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        def __init__(
            self,
            *,
            structureMode: global___StructureModeTrait.StructureMode.ValueType = ...,
            reason: global___StructureModeTrait.StructureModeReason.ValueType = ...,
            userId: weave_common_pb2.ResourceId | None = ...,
            wwnId: google.protobuf.wrappers_pb2.StringValue | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["userId", b"userId", "wwnId", b"wwnId"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["reason", b"reason", "structureMode", b"structureMode", "userId", b"userId", "wwnId", b"wwnId"]) -> None: ...

    @typing.final
    class ConsumeOccupancyStateBeliefRequest(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        ACTIVEPROBABILITY_FIELD_NUMBER: builtins.int
        SLEEPPROBABILITY_FIELD_NUMBER: builtins.int
        VACANTPROBABILITY_FIELD_NUMBER: builtins.int
        IDENTIFIEDPRESENCEPROBABILITY_FIELD_NUMBER: builtins.int
        LASTMOTIONEVENTTIMESTAMP_FIELD_NUMBER: builtins.int
        UNKNOWNPROBABILITY_FIELD_NUMBER: builtins.int
        EVALUATIONTIMESTAMP_FIELD_NUMBER: builtins.int
        TRANSITIONEVALUATIONTIMESTAMP_FIELD_NUMBER: builtins.int
        IDENTIFIEDPRESENCECHANGEUSERID_FIELD_NUMBER: builtins.int
        IDENTIFIEDPRESENCECHANGETIME_FIELD_NUMBER: builtins.int
        RECENTUSERARRIVALS_FIELD_NUMBER: builtins.int
        RECENTUSERDEPARTURES_FIELD_NUMBER: builtins.int
        activeProbability: builtins.float
        sleepProbability: builtins.float
        vacantProbability: builtins.float
        identifiedPresenceProbability: builtins.float
        unknownProbability: builtins.float
        @property
        def lastMotionEventTimestamp(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
        @property
        def evaluationTimestamp(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
        @property
        def transitionEvaluationTimestamp(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
        @property
        def identifiedPresenceChangeUserId(self) -> global___StructureModeTrait.UserInfo: ...
        @property
        def identifiedPresenceChangeTime(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
        @property
        def recentUserArrivals(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___StructureModeTrait.UserInfo]: ...
        @property
        def recentUserDepartures(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___StructureModeTrait.UserInfo]: ...
        def __init__(
            self,
            *,
            activeProbability: builtins.float = ...,
            sleepProbability: builtins.float = ...,
            vacantProbability: builtins.float = ...,
            identifiedPresenceProbability: builtins.float = ...,
            lastMotionEventTimestamp: google.protobuf.timestamp_pb2.Timestamp | None = ...,
            unknownProbability: builtins.float = ...,
            evaluationTimestamp: google.protobuf.timestamp_pb2.Timestamp | None = ...,
            transitionEvaluationTimestamp: google.protobuf.timestamp_pb2.Timestamp | None = ...,
            identifiedPresenceChangeUserId: global___StructureModeTrait.UserInfo | None = ...,
            identifiedPresenceChangeTime: google.protobuf.timestamp_pb2.Timestamp | None = ...,
            recentUserArrivals: collections.abc.Iterable[global___StructureModeTrait.UserInfo] | None = ...,
            recentUserDepartures: collections.abc.Iterable[global___StructureModeTrait.UserInfo] | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["evaluationTimestamp", b"evaluationTimestamp", "identifiedPresenceChangeTime", b"identifiedPresenceChangeTime", "identifiedPresenceChangeUserId", b"identifiedPresenceChangeUserId", "lastMotionEventTimestamp", b"lastMotionEventTimestamp", "transitionEvaluationTimestamp", b"transitionEvaluationTimestamp"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["activeProbability", b"activeProbability", "evaluationTimestamp", b"evaluationTimestamp", "identifiedPresenceChangeTime", b"identifiedPresenceChangeTime", "identifiedPresenceChangeUserId", b"identifiedPresenceChangeUserId", "identifiedPresenceProbability", b"identifiedPresenceProbability", "lastMotionEventTimestamp", b"lastMotionEventTimestamp", "recentUserArrivals", b"recentUserArrivals", "recentUserDepartures", b"recentUserDepartures", "sleepProbability", b"sleepProbability", "transitionEvaluationTimestamp", b"transitionEvaluationTimestamp", "unknownProbability", b"unknownProbability", "vacantProbability", b"vacantProbability"]) -> None: ...

    @typing.final
    class ConsumeOccupancyStateBeliefResponse(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        RESPONSETYPE_FIELD_NUMBER: builtins.int
        responseType: global___StructureModeTrait.StructureModeChangeResponseType.ValueType
        def __init__(
            self,
            *,
            responseType: global___StructureModeTrait.StructureModeChangeResponseType.ValueType = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["responseType", b"responseType"]) -> None: ...

    @typing.final
    class ConsumeSecurityArmStateChangeRequest(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        def __init__(
            self,
        ) -> None: ...

    @typing.final
    class ConsumeBoltActuatorStateChangeRequest(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        def __init__(
            self,
        ) -> None: ...

    @typing.final
    class ConsumeLegacyStructureModeChangeRequest(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        AWAY_FIELD_NUMBER: builtins.int
        AWAYSETTER_FIELD_NUMBER: builtins.int
        MANUALAWAYTIMESTAMP_FIELD_NUMBER: builtins.int
        TOUCHEDBY_FIELD_NUMBER: builtins.int
        TOUCHEDID_FIELD_NUMBER: builtins.int
        away: global___StructureModeTrait.LegacyAwayState.ValueType
        awaySetter: global___StructureModeTrait.LegacyAwaySetter.ValueType
        touchedBy: global___StructureModeTrait.LegacyTouchedBy.ValueType
        @property
        def manualAwayTimestamp(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
        @property
        def touchedId(self) -> weave_common_pb2.ResourceId: ...
        def __init__(
            self,
            *,
            away: global___StructureModeTrait.LegacyAwayState.ValueType = ...,
            awaySetter: global___StructureModeTrait.LegacyAwaySetter.ValueType = ...,
            manualAwayTimestamp: google.protobuf.timestamp_pb2.Timestamp | None = ...,
            touchedBy: global___StructureModeTrait.LegacyTouchedBy.ValueType = ...,
            touchedId: weave_common_pb2.ResourceId | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["manualAwayTimestamp", b"manualAwayTimestamp", "touchedId", b"touchedId"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["away", b"away", "awaySetter", b"awaySetter", "manualAwayTimestamp", b"manualAwayTimestamp", "touchedBy", b"touchedBy", "touchedId", b"touchedId"]) -> None: ...

    @typing.final
    class StructureModeChangeEvent(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        @typing.final
        class BlamesEntry(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            KEY_FIELD_NUMBER: builtins.int
            VALUE_FIELD_NUMBER: builtins.int
            key: builtins.int
            @property
            def value(self) -> global___StructureModeTrait.StructureModeBlame: ...
            def __init__(
                self,
                *,
                key: builtins.int = ...,
                value: global___StructureModeTrait.StructureModeBlame | None = ...,
            ) -> None: ...
            def HasField(self, field_name: typing.Literal["value", b"value"]) -> builtins.bool: ...
            def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

        STRUCTUREMODE_FIELD_NUMBER: builtins.int
        PRIORSTRUCTUREMODE_FIELD_NUMBER: builtins.int
        REASON_FIELD_NUMBER: builtins.int
        USERID_FIELD_NUMBER: builtins.int
        DEVICEID_FIELD_NUMBER: builtins.int
        RTSDEVICEID_FIELD_NUMBER: builtins.int
        CONTROLEVENTTYPEURL_FIELD_NUMBER: builtins.int
        WWNID_FIELD_NUMBER: builtins.int
        BLAMES_FIELD_NUMBER: builtins.int
        ACTORMETHOD_FIELD_NUMBER: builtins.int
        PRIMARYBLAME_FIELD_NUMBER: builtins.int
        structureMode: global___StructureModeTrait.StructureMode.ValueType
        priorStructureMode: global___StructureModeTrait.StructureMode.ValueType
        reason: global___StructureModeTrait.StructureModeReason.ValueType
        actorMethod: global___StructureModeTrait.StructureModeActorMethod.ValueType
        @property
        def userId(self) -> weave_common_pb2.ResourceId: ...
        @property
        def deviceId(self) -> weave_common_pb2.ResourceId: ...
        @property
        def rtsDeviceId(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        @property
        def controlEventTypeUrl(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        @property
        def wwnId(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        @property
        def blames(self) -> google.protobuf.internal.containers.MessageMap[builtins.int, global___StructureModeTrait.StructureModeBlame]: ...
        @property
        def primaryBlame(self) -> global___StructureModeTrait.StructureModeBlame: ...
        def __init__(
            self,
            *,
            structureMode: global___StructureModeTrait.StructureMode.ValueType = ...,
            priorStructureMode: global___StructureModeTrait.StructureMode.ValueType = ...,
            reason: global___StructureModeTrait.StructureModeReason.ValueType = ...,
            userId: weave_common_pb2.ResourceId | None = ...,
            deviceId: weave_common_pb2.ResourceId | None = ...,
            rtsDeviceId: google.protobuf.wrappers_pb2.StringValue | None = ...,
            controlEventTypeUrl: google.protobuf.wrappers_pb2.StringValue | None = ...,
            wwnId: google.protobuf.wrappers_pb2.StringValue | None = ...,
            blames: collections.abc.Mapping[builtins.int, global___StructureModeTrait.StructureModeBlame] | None = ...,
            actorMethod: global___StructureModeTrait.StructureModeActorMethod.ValueType = ...,
            primaryBlame: global___StructureModeTrait.StructureModeBlame | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["controlEventTypeUrl", b"controlEventTypeUrl", "deviceId", b"deviceId", "primaryBlame", b"primaryBlame", "rtsDeviceId", b"rtsDeviceId", "userId", b"userId", "wwnId", b"wwnId"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["actorMethod", b"actorMethod", "blames", b"blames", "controlEventTypeUrl", b"controlEventTypeUrl", "deviceId", b"deviceId", "primaryBlame", b"primaryBlame", "priorStructureMode", b"priorStructureMode", "reason", b"reason", "rtsDeviceId", b"rtsDeviceId", "structureMode", b"structureMode", "userId", b"userId", "wwnId", b"wwnId"]) -> None: ...

    @typing.final
    class OccupancyChangeEvent(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        OCCUPANCY_FIELD_NUMBER: builtins.int
        PRIOROCCUPANCY_FIELD_NUMBER: builtins.int
        @property
        def occupancy(self) -> global___StructureModeTrait.Occupancy: ...
        @property
        def priorOccupancy(self) -> global___StructureModeTrait.Occupancy: ...
        def __init__(
            self,
            *,
            occupancy: global___StructureModeTrait.Occupancy | None = ...,
            priorOccupancy: global___StructureModeTrait.Occupancy | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["occupancy", b"occupancy", "priorOccupancy", b"priorOccupancy"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["occupancy", b"occupancy", "priorOccupancy", b"priorOccupancy"]) -> None: ...

    @typing.final
    class AllowanceChangeEvent(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        ALLOWANCE_FIELD_NUMBER: builtins.int
        PRIORALLOWANCE_FIELD_NUMBER: builtins.int
        @property
        def allowance(self) -> global___StructureModeTrait.Allowance: ...
        @property
        def priorAllowance(self) -> global___StructureModeTrait.Allowance: ...
        def __init__(
            self,
            *,
            allowance: global___StructureModeTrait.Allowance | None = ...,
            priorAllowance: global___StructureModeTrait.Allowance | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["allowance", b"allowance", "priorAllowance", b"priorAllowance"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["allowance", b"allowance", "priorAllowance", b"priorAllowance"]) -> None: ...

    @typing.final
    class AutoAsk(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        AUTOASKARM_FIELD_NUMBER: builtins.int
        AUTOASKLOCK_FIELD_NUMBER: builtins.int
        AUTOASKSTRUCTUREMODE_FIELD_NUMBER: builtins.int
        autoAskArm: global___StructureModeTrait.AutoAskArm.ValueType
        autoAskLock: global___StructureModeTrait.AutoAskLock.ValueType
        autoAskStructureMode: global___StructureModeTrait.AutoAskStructureMode.ValueType
        def __init__(
            self,
            *,
            autoAskArm: global___StructureModeTrait.AutoAskArm.ValueType = ...,
            autoAskLock: global___StructureModeTrait.AutoAskLock.ValueType = ...,
            autoAskStructureMode: global___StructureModeTrait.AutoAskStructureMode.ValueType = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["autoAskArm", b"autoAskArm", "autoAskLock", b"autoAskLock", "autoAskStructureMode", b"autoAskStructureMode"]) -> None: ...

    @typing.final
    class AutoAskEvent(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        ASKTYPE_FIELD_NUMBER: builtins.int
        USERID_FIELD_NUMBER: builtins.int
        DEVICEID_FIELD_NUMBER: builtins.int
        DRYRUN_FIELD_NUMBER: builtins.int
        AUTOASK_FIELD_NUMBER: builtins.int
        askType: global___StructureModeTrait.AutoAskType.ValueType
        dryRun: builtins.bool
        @property
        def userId(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[weave_common_pb2.ResourceId]: ...
        @property
        def deviceId(self) -> weave_common_pb2.ResourceId: ...
        @property
        def autoAsk(self) -> global___StructureModeTrait.AutoAsk: ...
        def __init__(
            self,
            *,
            askType: global___StructureModeTrait.AutoAskType.ValueType = ...,
            userId: collections.abc.Iterable[weave_common_pb2.ResourceId] | None = ...,
            deviceId: weave_common_pb2.ResourceId | None = ...,
            dryRun: builtins.bool = ...,
            autoAsk: global___StructureModeTrait.AutoAsk | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["autoAsk", b"autoAsk", "deviceId", b"deviceId"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["askType", b"askType", "autoAsk", b"autoAsk", "deviceId", b"deviceId", "dryRun", b"dryRun", "userId", b"userId"]) -> None: ...

    @typing.final
    class ActivityAgnosticStructureModeChangeEvent(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        ACTIVITYAGNOSTICSTRUCTUREMODE_FIELD_NUMBER: builtins.int
        PRIORACTIVITYAGNOSTICSTRUCTUREMODE_FIELD_NUMBER: builtins.int
        REASON_FIELD_NUMBER: builtins.int
        activityAgnosticStructureMode: global___StructureModeTrait.StructureMode.ValueType
        priorActivityAgnosticStructureMode: global___StructureModeTrait.StructureMode.ValueType
        reason: global___StructureModeTrait.StructureModeReason.ValueType
        def __init__(
            self,
            *,
            activityAgnosticStructureMode: global___StructureModeTrait.StructureMode.ValueType = ...,
            priorActivityAgnosticStructureMode: global___StructureModeTrait.StructureMode.ValueType = ...,
            reason: global___StructureModeTrait.StructureModeReason.ValueType = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["activityAgnosticStructureMode", b"activityAgnosticStructureMode", "priorActivityAgnosticStructureMode", b"priorActivityAgnosticStructureMode", "reason", b"reason"]) -> None: ...

    @typing.final
    class StructureModeTraceEventState(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        STRUCTUREMODE_FIELD_NUMBER: builtins.int
        OCCUPANCY_FIELD_NUMBER: builtins.int
        ALLOWANCE_FIELD_NUMBER: builtins.int
        STRUCTUREMODEREASON_FIELD_NUMBER: builtins.int
        STRUCTUREMODESETTER_FIELD_NUMBER: builtins.int
        STRUCTUREMODEEFFECTIVETIME_FIELD_NUMBER: builtins.int
        ACTIVITYAGNOSTICSTRUCTUREMODE_FIELD_NUMBER: builtins.int
        ACTIVITYAGNOSTICSTRUCTUREMODEEFFECTIVETIME_FIELD_NUMBER: builtins.int
        structureMode: global___StructureModeTrait.StructureMode.ValueType
        structureModeReason: global___StructureModeTrait.StructureModeReason.ValueType
        activityAgnosticStructureMode: global___StructureModeTrait.StructureMode.ValueType
        @property
        def occupancy(self) -> global___StructureModeTrait.Occupancy: ...
        @property
        def allowance(self) -> global___StructureModeTrait.Allowance: ...
        @property
        def structureModeSetter(self) -> weave_common_pb2.ResourceId: ...
        @property
        def structureModeEffectiveTime(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
        @property
        def activityAgnosticStructureModeEffectiveTime(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
        def __init__(
            self,
            *,
            structureMode: global___StructureModeTrait.StructureMode.ValueType = ...,
            occupancy: global___StructureModeTrait.Occupancy | None = ...,
            allowance: global___StructureModeTrait.Allowance | None = ...,
            structureModeReason: global___StructureModeTrait.StructureModeReason.ValueType = ...,
            structureModeSetter: weave_common_pb2.ResourceId | None = ...,
            structureModeEffectiveTime: google.protobuf.timestamp_pb2.Timestamp | None = ...,
            activityAgnosticStructureMode: global___StructureModeTrait.StructureMode.ValueType = ...,
            activityAgnosticStructureModeEffectiveTime: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["activityAgnosticStructureModeEffectiveTime", b"activityAgnosticStructureModeEffectiveTime", "allowance", b"allowance", "occupancy", b"occupancy", "structureModeEffectiveTime", b"structureModeEffectiveTime", "structureModeSetter", b"structureModeSetter"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["activityAgnosticStructureMode", b"activityAgnosticStructureMode", "activityAgnosticStructureModeEffectiveTime", b"activityAgnosticStructureModeEffectiveTime", "allowance", b"allowance", "occupancy", b"occupancy", "structureMode", b"structureMode", "structureModeEffectiveTime", b"structureModeEffectiveTime", "structureModeReason", b"structureModeReason", "structureModeSetter", b"structureModeSetter"]) -> None: ...

    @typing.final
    class StructureModeTraceEventStateChange(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        FROM_FIELD_NUMBER: builtins.int
        TO_FIELD_NUMBER: builtins.int
        @property
        def to(self) -> global___StructureModeTrait.StructureModeTraceEventState: ...
        def __init__(
            self,
            *,
            to: global___StructureModeTrait.StructureModeTraceEventState | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["from", b"from", "to", b"to"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["from", b"from", "to", b"to"]) -> None: ...

    @typing.final
    class StructureModeTraceEventStep(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        @typing.final
        class LabelsEntry(google.protobuf.message.Message):
            DESCRIPTOR: google.protobuf.descriptor.Descriptor

            KEY_FIELD_NUMBER: builtins.int
            VALUE_FIELD_NUMBER: builtins.int
            key: builtins.str
            value: builtins.str
            def __init__(
                self,
                *,
                key: builtins.str = ...,
                value: builtins.str = ...,
            ) -> None: ...
            def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

        TIME_FIELD_NUMBER: builtins.int
        LABELS_FIELD_NUMBER: builtins.int
        @property
        def time(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
        @property
        def labels(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]: ...
        def __init__(
            self,
            *,
            time: google.protobuf.timestamp_pb2.Timestamp | None = ...,
            labels: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["time", b"time"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["labels", b"labels", "time", b"time"]) -> None: ...

    @typing.final
    class StructureModeTraceEvent(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        TRIGGER_FIELD_NUMBER: builtins.int
        TRIGGERAGENT_FIELD_NUMBER: builtins.int
        TRIGGEREVENTKEY_FIELD_NUMBER: builtins.int
        TRIGGERTIME_FIELD_NUMBER: builtins.int
        STARTTIME_FIELD_NUMBER: builtins.int
        STATECHANGE_FIELD_NUMBER: builtins.int
        STEPS_FIELD_NUMBER: builtins.int
        SCENARIOID_FIELD_NUMBER: builtins.int
        ERROR_FIELD_NUMBER: builtins.int
        RTSSTRUCTUREID_FIELD_NUMBER: builtins.int
        trigger: builtins.str
        triggerAgent: builtins.str
        triggerEventKey: builtins.str
        error: builtins.str
        rtsStructureId: builtins.str
        @property
        def triggerTime(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
        @property
        def startTime(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
        @property
        def stateChange(self) -> global___StructureModeTrait.StructureModeTraceEventStateChange: ...
        @property
        def steps(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___StructureModeTrait.StructureModeTraceEventStep]: ...
        @property
        def scenarioId(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]: ...
        def __init__(
            self,
            *,
            trigger: builtins.str = ...,
            triggerAgent: builtins.str = ...,
            triggerEventKey: builtins.str = ...,
            triggerTime: google.protobuf.timestamp_pb2.Timestamp | None = ...,
            startTime: google.protobuf.timestamp_pb2.Timestamp | None = ...,
            stateChange: global___StructureModeTrait.StructureModeTraceEventStateChange | None = ...,
            steps: collections.abc.Iterable[global___StructureModeTrait.StructureModeTraceEventStep] | None = ...,
            scenarioId: collections.abc.Iterable[builtins.str] | None = ...,
            error: builtins.str = ...,
            rtsStructureId: builtins.str = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["startTime", b"startTime", "stateChange", b"stateChange", "triggerTime", b"triggerTime"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["error", b"error", "rtsStructureId", b"rtsStructureId", "scenarioId", b"scenarioId", "startTime", b"startTime", "stateChange", b"stateChange", "steps", b"steps", "trigger", b"trigger", "triggerAgent", b"triggerAgent", "triggerEventKey", b"triggerEventKey", "triggerTime", b"triggerTime"]) -> None: ...

    STRUCTUREMODE_FIELD_NUMBER: builtins.int
    OCCUPANCY_FIELD_NUMBER: builtins.int
    ALLOWANCE_FIELD_NUMBER: builtins.int
    STRUCTUREMODEREASON_FIELD_NUMBER: builtins.int
    STRUCTUREMODESETTER_FIELD_NUMBER: builtins.int
    STRUCTUREMODEEFFECTIVETIME_FIELD_NUMBER: builtins.int
    ACTIVITYAGNOSTICSTRUCTUREMODE_FIELD_NUMBER: builtins.int
    ACTIVITYAGNOSTICSTRUCTUREMODEEFFECTIVETIME_FIELD_NUMBER: builtins.int
    PRIVATESTATE_FIELD_NUMBER: builtins.int
    BLAMES_FIELD_NUMBER: builtins.int
    ACTORMETHOD_FIELD_NUMBER: builtins.int
    PRIMARYBLAME_FIELD_NUMBER: builtins.int
    structureMode: global___StructureModeTrait.StructureMode.ValueType
    structureModeReason: global___StructureModeTrait.StructureModeReason.ValueType
    activityAgnosticStructureMode: global___StructureModeTrait.StructureMode.ValueType
    actorMethod: global___StructureModeTrait.StructureModeActorMethod.ValueType
    @property
    def occupancy(self) -> global___StructureModeTrait.Occupancy: ...
    @property
    def allowance(self) -> global___StructureModeTrait.Allowance: ...
    @property
    def structureModeSetter(self) -> weave_common_pb2.ResourceId: ...
    @property
    def structureModeEffectiveTime(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def activityAgnosticStructureModeEffectiveTime(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def privateState(self) -> global___StructureModeTrait.PrivateTraitHandlerState: ...
    @property
    def blames(self) -> google.protobuf.internal.containers.MessageMap[builtins.int, global___StructureModeTrait.StructureModeBlame]: ...
    @property
    def primaryBlame(self) -> global___StructureModeTrait.StructureModeBlame: ...
    def __init__(
        self,
        *,
        structureMode: global___StructureModeTrait.StructureMode.ValueType = ...,
        occupancy: global___StructureModeTrait.Occupancy | None = ...,
        allowance: global___StructureModeTrait.Allowance | None = ...,
        structureModeReason: global___StructureModeTrait.StructureModeReason.ValueType = ...,
        structureModeSetter: weave_common_pb2.ResourceId | None = ...,
        structureModeEffectiveTime: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        activityAgnosticStructureMode: global___StructureModeTrait.StructureMode.ValueType = ...,
        activityAgnosticStructureModeEffectiveTime: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        privateState: global___StructureModeTrait.PrivateTraitHandlerState | None = ...,
        blames: collections.abc.Mapping[builtins.int, global___StructureModeTrait.StructureModeBlame] | None = ...,
        actorMethod: global___StructureModeTrait.StructureModeActorMethod.ValueType = ...,
        primaryBlame: global___StructureModeTrait.StructureModeBlame | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["activityAgnosticStructureModeEffectiveTime", b"activityAgnosticStructureModeEffectiveTime", "allowance", b"allowance", "occupancy", b"occupancy", "primaryBlame", b"primaryBlame", "privateState", b"privateState", "structureModeEffectiveTime", b"structureModeEffectiveTime", "structureModeSetter", b"structureModeSetter"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["activityAgnosticStructureMode", b"activityAgnosticStructureMode", "activityAgnosticStructureModeEffectiveTime", b"activityAgnosticStructureModeEffectiveTime", "actorMethod", b"actorMethod", "allowance", b"allowance", "blames", b"blames", "occupancy", b"occupancy", "primaryBlame", b"primaryBlame", "privateState", b"privateState", "structureMode", b"structureMode", "structureModeEffectiveTime", b"structureModeEffectiveTime", "structureModeReason", b"structureModeReason", "structureModeSetter", b"structureModeSetter"]) -> None: ...

global___StructureModeTrait = StructureModeTrait

@typing.final
class StructureGeofencingTrait(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _GeofenceEnhancedAutoAwayStatus:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _GeofenceEnhancedAutoAwayStatusEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[StructureGeofencingTrait._GeofenceEnhancedAutoAwayStatus.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        GEOFENCE_ENHANCED_AUTO_AWAY_STATUS_UNSPECIFIED: StructureGeofencingTrait._GeofenceEnhancedAutoAwayStatus.ValueType  # 0
        GEOFENCE_ENHANCED_AUTO_AWAY_STATUS_NOT_SET: StructureGeofencingTrait._GeofenceEnhancedAutoAwayStatus.ValueType  # 1
        GEOFENCE_ENHANCED_AUTO_AWAY_STATUS_ENABLED: StructureGeofencingTrait._GeofenceEnhancedAutoAwayStatus.ValueType  # 2
        GEOFENCE_ENHANCED_AUTO_AWAY_STATUS_DISABLED: StructureGeofencingTrait._GeofenceEnhancedAutoAwayStatus.ValueType  # 3

    class GeofenceEnhancedAutoAwayStatus(_GeofenceEnhancedAutoAwayStatus, metaclass=_GeofenceEnhancedAutoAwayStatusEnumTypeWrapper): ...
    GEOFENCE_ENHANCED_AUTO_AWAY_STATUS_UNSPECIFIED: StructureGeofencingTrait.GeofenceEnhancedAutoAwayStatus.ValueType  # 0
    GEOFENCE_ENHANCED_AUTO_AWAY_STATUS_NOT_SET: StructureGeofencingTrait.GeofenceEnhancedAutoAwayStatus.ValueType  # 1
    GEOFENCE_ENHANCED_AUTO_AWAY_STATUS_ENABLED: StructureGeofencingTrait.GeofenceEnhancedAutoAwayStatus.ValueType  # 2
    GEOFENCE_ENHANCED_AUTO_AWAY_STATUS_DISABLED: StructureGeofencingTrait.GeofenceEnhancedAutoAwayStatus.ValueType  # 3

    class _GeofenceSourceType:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _GeofenceSourceTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[StructureGeofencingTrait._GeofenceSourceType.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        GEOFENCE_SOURCE_TYPE_UNSPECIFIED: StructureGeofencingTrait._GeofenceSourceType.ValueType  # 0
        GEOFENCE_SOURCE_TYPE_LEGACY_NEST_APP: StructureGeofencingTrait._GeofenceSourceType.ValueType  # 1
        GEOFENCE_SOURCE_TYPE_GOOGLE_HOME_APP: StructureGeofencingTrait._GeofenceSourceType.ValueType  # 2

    class GeofenceSourceType(_GeofenceSourceType, metaclass=_GeofenceSourceTypeEnumTypeWrapper): ...
    GEOFENCE_SOURCE_TYPE_UNSPECIFIED: StructureGeofencingTrait.GeofenceSourceType.ValueType  # 0
    GEOFENCE_SOURCE_TYPE_LEGACY_NEST_APP: StructureGeofencingTrait.GeofenceSourceType.ValueType  # 1
    GEOFENCE_SOURCE_TYPE_GOOGLE_HOME_APP: StructureGeofencingTrait.GeofenceSourceType.ValueType  # 2

    class _UserGeofenceEnrollmentCause:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _UserGeofenceEnrollmentCauseEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[StructureGeofencingTrait._UserGeofenceEnrollmentCause.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        USER_GEOFENCE_ENROLLMENT_CAUSE_UNSPECIFIED: StructureGeofencingTrait._UserGeofenceEnrollmentCause.ValueType  # 0
        USER_GEOFENCE_ENROLLMENT_CAUSE_USER_OPTED_IN: StructureGeofencingTrait._UserGeofenceEnrollmentCause.ValueType  # 1
        USER_GEOFENCE_ENROLLMENT_CAUSE_USER_ADDED_TO_STRUCTURE: StructureGeofencingTrait._UserGeofenceEnrollmentCause.ValueType  # 2

    class UserGeofenceEnrollmentCause(_UserGeofenceEnrollmentCause, metaclass=_UserGeofenceEnrollmentCauseEnumTypeWrapper): ...
    USER_GEOFENCE_ENROLLMENT_CAUSE_UNSPECIFIED: StructureGeofencingTrait.UserGeofenceEnrollmentCause.ValueType  # 0
    USER_GEOFENCE_ENROLLMENT_CAUSE_USER_OPTED_IN: StructureGeofencingTrait.UserGeofenceEnrollmentCause.ValueType  # 1
    USER_GEOFENCE_ENROLLMENT_CAUSE_USER_ADDED_TO_STRUCTURE: StructureGeofencingTrait.UserGeofenceEnrollmentCause.ValueType  # 2

    class _UserGeofenceDisenrollmentCause:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _UserGeofenceDisenrollmentCauseEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[StructureGeofencingTrait._UserGeofenceDisenrollmentCause.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        USER_GEOFENCE_DISENROLLMENT_CAUSE_UNSPECIFIED: StructureGeofencingTrait._UserGeofenceDisenrollmentCause.ValueType  # 0
        USER_GEOFENCE_DISENROLLMENT_CAUSE_USER_OPTED_OUT: StructureGeofencingTrait._UserGeofenceDisenrollmentCause.ValueType  # 1
        USER_GEOFENCE_DISENROLLMENT_CAUSE_USER_REMOVED_FROM_STRUCTURE: StructureGeofencingTrait._UserGeofenceDisenrollmentCause.ValueType  # 2

    class UserGeofenceDisenrollmentCause(_UserGeofenceDisenrollmentCause, metaclass=_UserGeofenceDisenrollmentCauseEnumTypeWrapper): ...
    USER_GEOFENCE_DISENROLLMENT_CAUSE_UNSPECIFIED: StructureGeofencingTrait.UserGeofenceDisenrollmentCause.ValueType  # 0
    USER_GEOFENCE_DISENROLLMENT_CAUSE_USER_OPTED_OUT: StructureGeofencingTrait.UserGeofenceDisenrollmentCause.ValueType  # 1
    USER_GEOFENCE_DISENROLLMENT_CAUSE_USER_REMOVED_FROM_STRUCTURE: StructureGeofencingTrait.UserGeofenceDisenrollmentCause.ValueType  # 2

    @typing.final
    class GeofenceEnrolledUsersEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.int
        @property
        def value(self) -> global___StructureGeofencingTrait.GeofenceEnrolledUser: ...
        def __init__(
            self,
            *,
            key: builtins.int = ...,
            value: global___StructureGeofencingTrait.GeofenceEnrolledUser | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["value", b"value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    @typing.final
    class GeofenceEnrolledUser(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        USERID_FIELD_NUMBER: builtins.int
        GEOFENCESOURCETYPE_FIELD_NUMBER: builtins.int
        MOBILEDEVICEID_FIELD_NUMBER: builtins.int
        geofenceSourceType: global___StructureGeofencingTrait.GeofenceSourceType.ValueType
        mobileDeviceId: builtins.str
        @property
        def userId(self) -> weave_common_pb2.ResourceId: ...
        def __init__(
            self,
            *,
            userId: weave_common_pb2.ResourceId | None = ...,
            geofenceSourceType: global___StructureGeofencingTrait.GeofenceSourceType.ValueType = ...,
            mobileDeviceId: builtins.str = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["userId", b"userId"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["geofenceSourceType", b"geofenceSourceType", "mobileDeviceId", b"mobileDeviceId", "userId", b"userId"]) -> None: ...

    @typing.final
    class StructureGeofenceStateAssertionEvent(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        STATE_FIELD_NUMBER: builtins.int
        USERID_FIELD_NUMBER: builtins.int
        RTSFENCEID_FIELD_NUMBER: builtins.int
        RTSMOBILEDEVICEID_FIELD_NUMBER: builtins.int
        state: global___Geofencing.GeofenceState.ValueType
        @property
        def userId(self) -> weave_common_pb2.ResourceId: ...
        @property
        def rtsFenceId(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        @property
        def rtsMobileDeviceId(self) -> google.protobuf.wrappers_pb2.StringValue: ...
        def __init__(
            self,
            *,
            state: global___Geofencing.GeofenceState.ValueType = ...,
            userId: weave_common_pb2.ResourceId | None = ...,
            rtsFenceId: google.protobuf.wrappers_pb2.StringValue | None = ...,
            rtsMobileDeviceId: google.protobuf.wrappers_pb2.StringValue | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["rtsFenceId", b"rtsFenceId", "rtsMobileDeviceId", b"rtsMobileDeviceId", "userId", b"userId"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["rtsFenceId", b"rtsFenceId", "rtsMobileDeviceId", b"rtsMobileDeviceId", "state", b"state", "userId", b"userId"]) -> None: ...

    @typing.final
    class UserGeofenceEnrollmentEvent(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        GEOFENCESOURCETYPE_FIELD_NUMBER: builtins.int
        USERID_FIELD_NUMBER: builtins.int
        MOBILEDEVICEID_FIELD_NUMBER: builtins.int
        ENROLLMENTCAUSE_FIELD_NUMBER: builtins.int
        geofenceSourceType: global___StructureGeofencingTrait.GeofenceSourceType.ValueType
        mobileDeviceId: builtins.str
        enrollmentCause: global___StructureGeofencingTrait.UserGeofenceEnrollmentCause.ValueType
        @property
        def userId(self) -> weave_common_pb2.ResourceId: ...
        def __init__(
            self,
            *,
            geofenceSourceType: global___StructureGeofencingTrait.GeofenceSourceType.ValueType = ...,
            userId: weave_common_pb2.ResourceId | None = ...,
            mobileDeviceId: builtins.str = ...,
            enrollmentCause: global___StructureGeofencingTrait.UserGeofenceEnrollmentCause.ValueType = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["userId", b"userId"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["enrollmentCause", b"enrollmentCause", "geofenceSourceType", b"geofenceSourceType", "mobileDeviceId", b"mobileDeviceId", "userId", b"userId"]) -> None: ...

    @typing.final
    class UserGeofenceDisenrollmentEvent(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        GEOFENCESOURCETYPE_FIELD_NUMBER: builtins.int
        USERID_FIELD_NUMBER: builtins.int
        MOBILEDEVICEID_FIELD_NUMBER: builtins.int
        DISENROLLMENTCAUSE_FIELD_NUMBER: builtins.int
        geofenceSourceType: global___StructureGeofencingTrait.GeofenceSourceType.ValueType
        mobileDeviceId: builtins.str
        disenrollmentCause: global___StructureGeofencingTrait.UserGeofenceDisenrollmentCause.ValueType
        @property
        def userId(self) -> weave_common_pb2.ResourceId: ...
        def __init__(
            self,
            *,
            geofenceSourceType: global___StructureGeofencingTrait.GeofenceSourceType.ValueType = ...,
            userId: weave_common_pb2.ResourceId | None = ...,
            mobileDeviceId: builtins.str = ...,
            disenrollmentCause: global___StructureGeofencingTrait.UserGeofenceDisenrollmentCause.ValueType = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["userId", b"userId"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["disenrollmentCause", b"disenrollmentCause", "geofenceSourceType", b"geofenceSourceType", "mobileDeviceId", b"mobileDeviceId", "userId", b"userId"]) -> None: ...

    @typing.final
    class UserGeofenceDeviceChangeEvent(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        GEOFENCESOURCETYPE_FIELD_NUMBER: builtins.int
        USERID_FIELD_NUMBER: builtins.int
        PREVIOUSMOBILEDEVICEID_FIELD_NUMBER: builtins.int
        CURRENTMOBILEDEVICEID_FIELD_NUMBER: builtins.int
        geofenceSourceType: global___StructureGeofencingTrait.GeofenceSourceType.ValueType
        previousMobileDeviceId: builtins.str
        currentMobileDeviceId: builtins.str
        @property
        def userId(self) -> weave_common_pb2.ResourceId: ...
        def __init__(
            self,
            *,
            geofenceSourceType: global___StructureGeofencingTrait.GeofenceSourceType.ValueType = ...,
            userId: weave_common_pb2.ResourceId | None = ...,
            previousMobileDeviceId: builtins.str = ...,
            currentMobileDeviceId: builtins.str = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["userId", b"userId"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["currentMobileDeviceId", b"currentMobileDeviceId", "geofenceSourceType", b"geofenceSourceType", "previousMobileDeviceId", b"previousMobileDeviceId", "userId", b"userId"]) -> None: ...

    @typing.final
    class StructureGeofenceEnrollmentEvent(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        def __init__(
            self,
        ) -> None: ...

    @typing.final
    class StructureGeofenceDisenrollmentEvent(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        def __init__(
            self,
        ) -> None: ...

    @typing.final
    class NestAppGeofenceHealthCheckEvent(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        RTSSTRUCTUREID_FIELD_NUMBER: builtins.int
        RTSUSERID_FIELD_NUMBER: builtins.int
        rtsStructureId: builtins.str
        rtsUserId: builtins.str
        def __init__(
            self,
            *,
            rtsStructureId: builtins.str = ...,
            rtsUserId: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["rtsStructureId", b"rtsStructureId", "rtsUserId", b"rtsUserId"]) -> None: ...

    GEOFENCEENHANCEDAUTOAWAYSTATUS_FIELD_NUMBER: builtins.int
    GEOFENCEENROLLEDUSERS_FIELD_NUMBER: builtins.int
    geofenceEnhancedAutoawayStatus: global___StructureGeofencingTrait.GeofenceEnhancedAutoAwayStatus.ValueType
    @property
    def geofenceEnrolledUsers(self) -> google.protobuf.internal.containers.MessageMap[builtins.int, global___StructureGeofencingTrait.GeofenceEnrolledUser]: ...
    def __init__(
        self,
        *,
        geofenceEnhancedAutoawayStatus: global___StructureGeofencingTrait.GeofenceEnhancedAutoAwayStatus.ValueType = ...,
        geofenceEnrolledUsers: collections.abc.Mapping[builtins.int, global___StructureGeofencingTrait.GeofenceEnrolledUser] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["geofenceEnhancedAutoawayStatus", b"geofenceEnhancedAutoawayStatus", "geofenceEnrolledUsers", b"geofenceEnrolledUsers"]) -> None: ...

global___StructureGeofencingTrait = StructureGeofencingTrait

@typing.final
class StructureModeSettingsTrait(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _BuildUniformDailySleepScheduleResponseType:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _BuildUniformDailySleepScheduleResponseTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[StructureModeSettingsTrait._BuildUniformDailySleepScheduleResponseType.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        BUILD_UNIFORM_DAILY_SLEEP_SCHEDULE_RESPONSE_TYPE_UNSPECIFIED: StructureModeSettingsTrait._BuildUniformDailySleepScheduleResponseType.ValueType  # 0
        BUILD_UNIFORM_DAILY_SLEEP_SCHEDULE_RESPONSE_TYPE_SUCCESS: StructureModeSettingsTrait._BuildUniformDailySleepScheduleResponseType.ValueType  # 1
        BUILD_UNIFORM_DAILY_SLEEP_SCHEDULE_RESPONSE_TYPE_FAIL_ALREADY: StructureModeSettingsTrait._BuildUniformDailySleepScheduleResponseType.ValueType  # 2

    class BuildUniformDailySleepScheduleResponseType(_BuildUniformDailySleepScheduleResponseType, metaclass=_BuildUniformDailySleepScheduleResponseTypeEnumTypeWrapper): ...
    BUILD_UNIFORM_DAILY_SLEEP_SCHEDULE_RESPONSE_TYPE_UNSPECIFIED: StructureModeSettingsTrait.BuildUniformDailySleepScheduleResponseType.ValueType  # 0
    BUILD_UNIFORM_DAILY_SLEEP_SCHEDULE_RESPONSE_TYPE_SUCCESS: StructureModeSettingsTrait.BuildUniformDailySleepScheduleResponseType.ValueType  # 1
    BUILD_UNIFORM_DAILY_SLEEP_SCHEDULE_RESPONSE_TYPE_FAIL_ALREADY: StructureModeSettingsTrait.BuildUniformDailySleepScheduleResponseType.ValueType  # 2

    @typing.final
    class TimeSpan(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        STARTTIME_FIELD_NUMBER: builtins.int
        ENDTIME_FIELD_NUMBER: builtins.int
        @property
        def startTime(self) -> weave_common_pb2.TimeOfDay: ...
        @property
        def endTime(self) -> weave_common_pb2.TimeOfDay: ...
        def __init__(
            self,
            *,
            startTime: weave_common_pb2.TimeOfDay | None = ...,
            endTime: weave_common_pb2.TimeOfDay | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["endTime", b"endTime", "startTime", b"startTime"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["endTime", b"endTime", "startTime", b"startTime"]) -> None: ...

    @typing.final
    class DayTimeSpan(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        STARTDAY_FIELD_NUMBER: builtins.int
        STARTTIME_FIELD_NUMBER: builtins.int
        ENDDAY_FIELD_NUMBER: builtins.int
        ENDTIME_FIELD_NUMBER: builtins.int
        startDay: weave_common_pb2.DayOfWeek.ValueType
        endDay: weave_common_pb2.DayOfWeek.ValueType
        @property
        def startTime(self) -> weave_common_pb2.TimeOfDay: ...
        @property
        def endTime(self) -> weave_common_pb2.TimeOfDay: ...
        def __init__(
            self,
            *,
            startDay: weave_common_pb2.DayOfWeek.ValueType = ...,
            startTime: weave_common_pb2.TimeOfDay | None = ...,
            endDay: weave_common_pb2.DayOfWeek.ValueType = ...,
            endTime: weave_common_pb2.TimeOfDay | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["endTime", b"endTime", "startTime", b"startTime"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["endDay", b"endDay", "endTime", b"endTime", "startDay", b"startDay", "startTime", b"startTime"]) -> None: ...

    @typing.final
    class BuildUniformDailySleepScheduleRequest(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        TIMESPAN_FIELD_NUMBER: builtins.int
        USERID_FIELD_NUMBER: builtins.int
        @property
        def timeSpan(self) -> global___StructureModeSettingsTrait.TimeSpan: ...
        @property
        def userId(self) -> weave_common_pb2.ResourceId: ...
        def __init__(
            self,
            *,
            timeSpan: global___StructureModeSettingsTrait.TimeSpan | None = ...,
            userId: weave_common_pb2.ResourceId | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["timeSpan", b"timeSpan", "userId", b"userId"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["timeSpan", b"timeSpan", "userId", b"userId"]) -> None: ...

    @typing.final
    class BuildUniformDailySleepScheduleResponse(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        RESPONSETYPE_FIELD_NUMBER: builtins.int
        responseType: global___StructureModeSettingsTrait.BuildUniformDailySleepScheduleResponseType.ValueType
        def __init__(
            self,
            *,
            responseType: global___StructureModeSettingsTrait.BuildUniformDailySleepScheduleResponseType.ValueType = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["responseType", b"responseType"]) -> None: ...

    @typing.final
    class SleepScheduleChangeEvent(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        ENABLEAUTOSLEEP_FIELD_NUMBER: builtins.int
        PRIORENABLEAUTOSLEEP_FIELD_NUMBER: builtins.int
        SLEEPSCHEDULE_FIELD_NUMBER: builtins.int
        PRIORSLEEPSCHEDULE_FIELD_NUMBER: builtins.int
        USERID_FIELD_NUMBER: builtins.int
        enableAutoSleep: builtins.bool
        priorEnableAutoSleep: builtins.bool
        @property
        def sleepSchedule(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___StructureModeSettingsTrait.DayTimeSpan]: ...
        @property
        def priorSleepSchedule(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___StructureModeSettingsTrait.DayTimeSpan]: ...
        @property
        def userId(self) -> weave_common_pb2.ResourceId: ...
        def __init__(
            self,
            *,
            enableAutoSleep: builtins.bool = ...,
            priorEnableAutoSleep: builtins.bool = ...,
            sleepSchedule: collections.abc.Iterable[global___StructureModeSettingsTrait.DayTimeSpan] | None = ...,
            priorSleepSchedule: collections.abc.Iterable[global___StructureModeSettingsTrait.DayTimeSpan] | None = ...,
            userId: weave_common_pb2.ResourceId | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["userId", b"userId"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["enableAutoSleep", b"enableAutoSleep", "priorEnableAutoSleep", b"priorEnableAutoSleep", "priorSleepSchedule", b"priorSleepSchedule", "sleepSchedule", b"sleepSchedule", "userId", b"userId"]) -> None: ...

    ENABLEAUTOSLEEP_FIELD_NUMBER: builtins.int
    SLEEPSCHEDULE_FIELD_NUMBER: builtins.int
    DERIVEDDAILYSLEEPSCHEDULE_FIELD_NUMBER: builtins.int
    OCCUPANCYSENSORARMTIMESTAMP_FIELD_NUMBER: builtins.int
    enableAutoSleep: builtins.bool
    @property
    def sleepSchedule(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___StructureModeSettingsTrait.DayTimeSpan]: ...
    @property
    def derivedDailySleepSchedule(self) -> global___StructureModeSettingsTrait.TimeSpan: ...
    @property
    def occupancySensorArmTimestamp(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        enableAutoSleep: builtins.bool = ...,
        sleepSchedule: collections.abc.Iterable[global___StructureModeSettingsTrait.DayTimeSpan] | None = ...,
        derivedDailySleepSchedule: global___StructureModeSettingsTrait.TimeSpan | None = ...,
        occupancySensorArmTimestamp: google.protobuf.timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["derivedDailySleepSchedule", b"derivedDailySleepSchedule", "occupancySensorArmTimestamp", b"occupancySensorArmTimestamp"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["derivedDailySleepSchedule", b"derivedDailySleepSchedule", "enableAutoSleep", b"enableAutoSleep", "occupancySensorArmTimestamp", b"occupancySensorArmTimestamp", "sleepSchedule", b"sleepSchedule"]) -> None: ...

global___StructureModeSettingsTrait = StructureModeSettingsTrait

@typing.final
class Geofencing(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _GeofenceState:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _GeofenceStateEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Geofencing._GeofenceState.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        GEOFENCE_STATE_UNSPECIFIED: Geofencing._GeofenceState.ValueType  # 0
        GEOFENCE_STATE_INSIDE: Geofencing._GeofenceState.ValueType  # 1
        GEOFENCE_STATE_OUTSIDE: Geofencing._GeofenceState.ValueType  # 2
        GEOFENCE_STATE_UNKNOWN: Geofencing._GeofenceState.ValueType  # 3

    class GeofenceState(_GeofenceState, metaclass=_GeofenceStateEnumTypeWrapper): ...
    GEOFENCE_STATE_UNSPECIFIED: Geofencing.GeofenceState.ValueType  # 0
    GEOFENCE_STATE_INSIDE: Geofencing.GeofenceState.ValueType  # 1
    GEOFENCE_STATE_OUTSIDE: Geofencing.GeofenceState.ValueType  # 2
    GEOFENCE_STATE_UNKNOWN: Geofencing.GeofenceState.ValueType  # 3

    def __init__(
        self,
    ) -> None: ...

global___Geofencing = Geofencing

@typing.final
class OccupancyInputSettingsTrait(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class OccupancyInputEnrollmentEvent(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        STRUCTUREID_FIELD_NUMBER: builtins.int
        @property
        def structureId(self) -> weave_common_pb2.ResourceId: ...
        def __init__(
            self,
            *,
            structureId: weave_common_pb2.ResourceId | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["structureId", b"structureId"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["structureId", b"structureId"]) -> None: ...

    @typing.final
    class OccupancyInputDisenrollmentEvent(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        STRUCTUREID_FIELD_NUMBER: builtins.int
        @property
        def structureId(self) -> weave_common_pb2.ResourceId: ...
        def __init__(
            self,
            *,
            structureId: weave_common_pb2.ResourceId | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["structureId", b"structureId"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["structureId", b"structureId"]) -> None: ...

    DEVICEACTIVITYCONSIDERED_FIELD_NUMBER: builtins.int
    deviceActivityConsidered: builtins.bool
    def __init__(
        self,
        *,
        deviceActivityConsidered: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["deviceActivityConsidered", b"deviceActivityConsidered"]) -> None: ...

global___OccupancyInputSettingsTrait = OccupancyInputSettingsTrait

@typing.final
class StructureModeCapabilitiesTrait(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SLEEPSTRUCTUREMODEENABLED_FIELD_NUMBER: builtins.int
    sleepStructureModeEnabled: builtins.bool
    def __init__(
        self,
        *,
        sleepStructureModeEnabled: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["sleepStructureModeEnabled", b"sleepStructureModeEnabled"]) -> None: ...

global___StructureModeCapabilitiesTrait = StructureModeCapabilitiesTrait
